<script setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { onBeforeRouteUpdate, useRoute } from "vue-router";
import { orgSession } from "../api.js";
import { annotationRequest as request, imageDataUrl, loadAuthorizedImage } from "../annotation.js";
import { errorText, orgAccess } from "../org.js";
import { useTaskAuthority } from "../task-authority.js";
import CardEditor from "../components/CardEditor.vue";
import DocumentPreview from "../components/DocumentPreview.vue";
import TaskNavigation from "../components/TaskNavigation.vue";
const route=useRoute(), taskId=String(route.params.taskId), cardId=String(route.params.cardId), jobId=String(route.query.job??"");
const card=ref(null), row=ref(null), sources=ref([]), source=ref(null), sourceImage=ref(null), candidate=ref(null), candidateImage=ref(null), candidateCurrent=ref(null);
const crop=ref(null), boxes=ref([]), preflight=ref(null), reviewed=ref(false), busy=ref(false), error=ref(""), job=ref(null), editorOpen=ref(false), candidates=ref([]), releases=ref([]), cosign=ref(null);
const sourceCursor=ref(null), candidateCursor=ref(null), releaseCursor=ref(null), sourcePrior=ref([]), candidatePrior=ref([]), releasePrior=ref([]), releaseJobs=ref([]);
const currentCursors={source:null,candidate:null,release:null};
let alive=true, epoch=0, timer=null, sourceController=null, candidateController=null, requestController=new AbortController(), requestId=null, requestFingerprint=null;
function clear(exc){epoch++;alive=false;clearTimeout(timer);requestController.abort();sourceController?.abort();candidateController?.abort();card.value=null;row.value=null;sources.value=[];source.value=null;sourceImage.value=null;candidate.value=null;candidateImage.value=null;candidateCurrent.value=null;preflight.value=null;crop.value=null;boxes.value=[];editorOpen.value=false;candidates.value=[];releases.value=[];releaseJobs.value=[];reviewed.value=false;if(exc instanceof Error)error.value=errorText(exc);else error.value="";}
const authority=useTaskAuthority(taskId,clear);
const editable=computed(()=>alive&&authority.canWrite.value&&["admin","bidder","technical"].includes(orgAccess.role)&&card.value&&["draft","rejected","needs_material"].includes(card.value.state)&&card.value.disposition!=="comply_only");
const canSubmit=computed(()=>editable.value&&!busy.value&&!!sourceImage.value&&reviewed.value&&!!preflight.value&&!preflight.value.blocker_codes.length&&!activeJob.value);
const activeJob=computed(()=>["queued","running"].includes(job.value?.status));
const requirementStatus=computed(()=>({confirmed:"要求已确认",unconfirmed:"要求尚未确认",legacy_unconfirmed:"要求尚未确认",invalidated:"要求确认已失效"}[row.value?.review_state]??"要求状态待核对"));
const sourceStyle=computed(()=>source.value?{aspectRatio:`${source.value.preview.width_px}/${source.value.preview.height_px}`} : {});
function rectStyle(rect){if(!source.value)return {};return {left:`${rect.x/source.value.preview.width_px*100}%`,top:`${rect.y/source.value.preview.height_px*100}%`,width:`${rect.width/source.value.preview.width_px*100}%`,height:`${rect.height/source.value.preview.height_px*100}%`};}
function invalidate(){preflight.value=null;reviewed.value=false;}
watch([crop,boxes],invalidate,{deep:true});
async function readCard(){const value=(await request("GET",`/cards/${cardId}`,undefined,requestController.signal)).data;if(!alive)return;if(value.id!==cardId||value.task_id!==taskId||value.org_id!==orgSession.get()?.orgId||value.extraction_job_id!==jobId)throw new Error("响应卡范围不符合契约");card.value=value;const review=(await request("GET",`/requirements/${value.requirement_id}/review`,undefined,requestController.signal)).data;if(!alive)return;const entry=review.requirement;if(entry.task_id!==taskId||entry.extraction_job_id!==jobId)throw new Error("要求范围不符合契约");row.value={id:entry.requirement_id,...entry.content,review_state:entry.state,card:value};cosign.value=(await request("GET",`/cards/${cardId}/signoffs?limit=50`,undefined,requestController.signal)).data.summary;}
async function sourcePage(cursor=null){const query=new URLSearchParams({history:"true",limit:"50"});if(cursor)query.set("cursor",cursor);const response=await request("GET",`/tasks/${taskId}/evidence-sources?${query}`,undefined,requestController.signal);if(!alive)return;const data=response.data,next=data.next_cursor;if(data.history!==true||!Array.isArray(data.active_source_ids)||data.returned!==response.items.length||typeof data.has_more!=="boolean"||!(next===null||typeof next==="string"&&next.length>0&&next.length<=4096)||data.has_more!==(next!==null)||response.items.length>50||new Set(response.items.map(item=>item.id)).size!==response.items.length||response.items.some(item=>item.org_id!==orgSession.get()?.orgId||item.task_id!==taskId)||JSON.stringify(data.active_source_ids)!==JSON.stringify(response.items.filter(item=>item.active_selection).map(item=>item.id)))throw new Error("来源分页范围不符合契约");sources.value=response.items;sourceCursor.value=next;}
async function candidatePage(cursor=null){const query=new URLSearchParams({card_id:cardId,limit:"50"});if(cursor)query.set("cursor",cursor);const response=await request("GET",`/tasks/${taskId}/annotations?${query}`,undefined,requestController.signal);if(!alive)return;if(response.data.task_id!==taskId||response.items.length>50||response.items.some(item=>item.task_id!==taskId||item.org_id!==orgSession.get()?.orgId||item.manifest.target.card_id!==cardId))throw new Error("候选分页范围不符合契约");candidates.value=response.items;candidateCursor.value=response.data.next_cursor;}
async function releasePage(cursor=null){if(!candidate.value)return;const id=candidate.value.id,query=new URLSearchParams({limit:"50"});if(cursor)query.set("cursor",cursor);const response=await request("GET",`/annotations/${id}/releases?${query}`,undefined,requestController.signal);if(!alive||candidate.value?.id!==id)return;if(response.data.annotation_id!==id||response.items.length>50)throw new Error("确认图分页范围不符合契约");releases.value=response.items;releaseCursor.value=response.data.next_cursor;const jobs=await request("GET",`/tasks/${taskId}/jobs?kind=annotation_release&annotation_id=${id}&limit=20`,undefined,requestController.signal);if(alive&&candidate.value?.id===id){if(jobs.items.length>20)throw new Error("确认图作业超过读取上限");releaseJobs.value=jobs.items;}}
async function retryRelease(item){if(!authority.canWrite.value||!candidate.value)return;busy.value=true;error.value="";try{const receipt=(await request("GET",`/jobs/${item.id}`,undefined,requestController.signal)).data;const pin=receipt.result;if(!["failed","cancelled"].includes(receipt.status)||receipt.kind!=="annotation_release"||pin?.annotation_id!==candidate.value.id||pin.card_id!==cardId||pin.expected_card_revision!==card.value.revision||!pin.expected_approval_binding_hash)throw new Error("没有当前完整审批绑定的失败确认图作业；请重新核对审批");await request("POST",`/annotations/${candidate.value.id}/releases`,{evidence_id:pin.evidence_id,card_id:pin.card_id,expected_card_revision:pin.expected_card_revision,expected_approval_binding_hash:pin.expected_approval_binding_hash,job_id:item.id,request_id:crypto.randomUUID(),retry:true},requestController.signal);await releasePage();}catch(exc){if(alive&&exc.name!=="AbortError")error.value=`${errorText(exc)}；确认图重试未自动重发。`;}finally{if(alive)busy.value=false;}}
async function turnPage(kind,forward){const prior={source:sourcePrior,candidate:candidatePrior,release:releasePrior}[kind],next={source:sourceCursor,candidate:candidateCursor,release:releaseCursor}[kind],read={source:sourcePage,candidate:candidatePage,release:releasePage}[kind];try{const cursor=forward?next.value:prior.value.pop();if(forward)prior.value.push(currentCursors[kind]);await read(cursor);currentCursors[kind]=cursor??null;}catch(exc){error.value=errorText(exc);}}
async function choose(value){if(busy.value||activeJob.value)return;const run=++epoch;sourceController?.abort();candidateController?.abort();sourceController=new AbortController();source.value=value;sourceImage.value=null;candidate.value=null;candidateImage.value=null;releases.value=[];crop.value={x:0,y:0,width:value.preview.width_px,height:value.preview.height_px};boxes.value=[];invalidate();error.value="";try{const blob=await loadAuthorizedImage({kind:"certificate_page",archive:value},sourceController.signal);const data=await imageDataUrl(blob);if(alive&&run===epoch)sourceImage.value=data;}catch(exc){if(alive&&run===epoch&&exc.name!=="AbortError")error.value=errorText(exc);}}
function resetPlan(){if(!source.value)return;crop.value={x:0,y:0,width:source.value.preview.width_px,height:source.value.preview.height_px};boxes.value=[];}
function addBox(){if(boxes.value.length>=20||!crop.value)return;boxes.value.push({...crop.value});}
function input(){if(!crop.value||!source.value||!card.value)throw new Error("请先读取原页与当前卡片");const rects=[crop.value,...boxes.value];for(const rect of rects){if(![rect.x,rect.y,rect.width,rect.height].every(Number.isInteger)||rect.x<0||rect.y<0||rect.width<1||rect.height<1||rect.x+rect.width>source.value.preview.width_px||rect.y+rect.height>source.value.preview.height_px)throw new Error("裁剪与框选须使用原页内的整数像素");}for(const rect of boxes.value){if(rect.x<crop.value.x||rect.y<crop.value.y||rect.x+rect.width>crop.value.x+crop.value.width||rect.y+rect.height>crop.value.y+crop.value.height)throw new Error("框选必须在裁剪范围内");}return {extraction_job_id:jobId,card_id:cardId,expected_card_revision:card.value.revision,source:{kind:"certificate_page",evidence_source_id:source.value.id},plan:{crop:{...crop.value},boxes:boxes.value.map(v=>({...v}))}};}
async function refreshCard(){invalidate();error.value="";try{await readCard();}catch(exc){if(alive&&exc.name!=="AbortError")error.value=errorText(exc);}}
async function preview(){if(!editable.value||!sourceImage.value)return;busy.value=true;error.value="";invalidate();const run=epoch;try{const value=(await request("POST",`/tasks/${taskId}/annotations`,{input:input(),dry_run:true},requestController.signal)).data;if(alive&&run===epoch){if(value.manifest.target.card_id!==cardId||value.manifest.source.source_png.sha256!==source.value.preview.sha256)throw new Error("预览来源与当前选择不符");preflight.value=value;}}catch(exc){if(alive&&exc.name!=="AbortError")error.value=errorText(exc);}finally{if(alive)busy.value=false;}}
async function submit(){if(!canSubmit.value)return;busy.value=true;error.value="";const run=epoch;try{const target=input(),fingerprint=JSON.stringify({input:target,hash:preflight.value.input_hash});if(requestFingerprint!==fingerprint){requestId=crypto.randomUUID();requestFingerprint=fingerprint;}const body={input:target,dry_run:false,expected_input_hash:preflight.value.input_hash,reviewed_source_png_sha256:source.value.preview.sha256,request_id:requestId,retry:false};const accepted=(await request("POST",`/tasks/${taskId}/annotations`,body,requestController.signal)).data;if(!alive||run!==epoch)return;job.value={id:accepted.job_id,status:accepted.status};invalidate();await poll();}catch(exc){if(alive&&exc.name!=="AbortError"){error.value=`${errorText(exc)}。输入已保留，未自动重试；请重新预览。`;invalidate();}}finally{if(alive)busy.value=false;}}
async function poll(){if(!alive||!job.value)return;const id=job.value.id;try{const result=await request("GET",`/jobs/${id}`,undefined,requestController.signal);if(!alive||job.value?.id!==id)return;job.value=result.data;if(job.value.status==="succeeded"){const annotationId=job.value.result?.annotation_id;if(!annotationId)throw new Error("作业没有发布候选材料 ID");await inspect(annotationId);await candidatePage();}else if(activeJob.value)timer=setTimeout(poll,1000);else if(job.value.error)error.value=errorText({code:job.value.error.code,message:job.value.error.message});}catch(exc){if(alive&&exc.name!=="AbortError")error.value=errorText(exc);}}
async function cancel(){try{await request("POST",`/jobs/${job.value.id}/cancel`,{},requestController.signal);clearTimeout(timer);await poll();}catch(exc){if(alive)error.value=errorText(exc);}}
async function inspect(id){const run=++epoch;candidateController?.abort();candidateController=new AbortController();candidate.value=null;candidateImage.value=null;releases.value=[];error.value="";try{const data=(await request("GET",`/annotations/${id}`,undefined,candidateController.signal)).data;const value=data.candidate;if(value.task_id!==taskId||value.org_id!==orgSession.get()?.orgId||value.manifest.target.card_id!==cardId||value.manifest.target.extraction_job_id!==jobId)throw new Error("候选图范围不符合契约");candidate.value=value;candidateCurrent.value=data.current;const blob=await loadAuthorizedImage({kind:"annotation_candidate",annotationId:id,expectedHash:value.rendering.image.sha256},candidateController.signal);const image=await imageDataUrl(blob);if(alive&&run===epoch){candidateImage.value=image;try{await releasePage();}catch(exc){if(alive&&run===epoch&&exc.name!=="AbortError")error.value=`确认图状态暂时无法读取：${errorText(exc)}`;}}}catch(exc){if(alive&&run===epoch&&exc.name!=="AbortError"){candidate.value=null;error.value=errorText(exc);}}}
function updated(value){card.value=value;row.value.card=value;readCard().catch(exc=>{error.value=errorText(exc);});releasePage().catch(exc=>{error.value=errorText(exc);});}
onBeforeRouteUpdate((to)=>{if(String(to.params.taskId)!==taskId||String(to.params.cardId)!==cardId||String(to.query.job??"")!==jobId){clear();return true;}});
window.addEventListener("bid:org-reset",clear);
onBeforeUnmount(()=>{clear();window.removeEventListener("bid:org-reset",clear);});
onMounted(async()=>{try{if(!jobId)throw new Error("必须明确指定抽取集合");await readCard();await Promise.all([sourcePage(),candidatePage()]);}catch(exc){if(alive&&exc.name!=="AbortError")error.value=errorText(exc);}});
</script>
<template>
  <div class="page-header"><div><h2>证据标注</h2><p class="subtitle">核对真实证书页，预览裁剪与框选，再生成未确认材料。</p></div><RouterLink :to="`/org/tasks/${taskId}/review?job=${jobId}&requirement=${card?.requirement_id??''}`">返回响应审阅</RouterLink></div>
  <TaskNavigation :task-id="taskId" />
  <el-alert v-if="error" :title="error" type="error" :closable="false" role="alert" />
  <template v-if="card && row">
    <el-card class="section" shadow="never"><p>负责人：{{authority.access.value?.workflow.owner_user_id??'待核对'}} · 审阅职责：{{card.review_domain??'尚未分类'}}</p><p data-testid="annotation-requirement-state">{{requirementStatus}}；要求确认、响应审阅与标注生成各自独立。</p><p data-testid="annotation-cosign-state">会签：{{cosign?.status??'待核对'}} · 待签署：{{cosign?.pending_domains?.join('、')||'无'}}</p><p data-testid="annotation-release-state">确认图：{{releases.length?'已生成；需核对当前有效性':'未生成确认图；完整人工审批后生成'}}</p><DocumentPreview :document-id="card.source.document_id" :page="card.source.page" :block="card.source.location?.block_id??''" label="核对招标原文" /><el-button :disabled="busy||activeJob" @click="refreshCard">重新核对卡片修订</el-button><RouterLink :to="`/org/tasks/${taskId}/requirements?job=${jobId}&requirement=${row.id}`">核对要求确认</RouterLink><p v-if="!editable" class="notice warning">当前身份或卡片状态只允许读取；生成标注需要人工负责人或协作者，以及可编辑卡片。</p></el-card>
    <el-card class="section" shadow="never"><template #header>已有证书页来源</template><ul class="plain-list"><li v-for="item in sources" :key="item.id"><el-button :disabled="busy || activeJob || !item.active_selection" :aria-label="`选择证书页：${item.original.name} 第 ${item.page} 页`" @click="choose(item)">{{item.original.name}} 第 {{item.page}} 页{{item.active_selection?'':' · 已失效'}}</el-button></li></ul><p v-if="!sources.length" class="hint">没有可访问的证书页来源。请在响应卡的材料面板中归档证书页。</p><div class="actions"><el-button :disabled="!sourcePrior.length" @click="turnPage('source',false)">上一页来源</el-button><el-button :disabled="!sourceCursor" @click="turnPage('source',true)">下一页来源</el-button></div></el-card>
    <el-card v-if="source && crop" class="section" shadow="never"><p>第 {{source.page}} 页 · 固定来源 SHA-256：<span class="mono">{{source.preview.sha256}}</span></p><p>服务端原页渲染时间：{{source.rendered_at}} · 原始文件 SHA-256：<span class="mono">{{source.original.sha256}}</span></p><div class="annotation-grid"><figure><figcaption>原页与拟标注范围；下方坐标均为原页像素</figcaption><div class="source-canvas" :style="sourceStyle"><img v-if="sourceImage" :src="sourceImage" alt="证书来源原页" /><span v-else>正在读取受权原页…</span><div v-if="preflight" class="crop-overlay" :style="rectStyle(crop)" /><div v-for="(box,index) in boxes" :key="index" class="box-overlay" :style="rectStyle(box)" /></div></figure><div><fieldset :disabled="!editable || busy || activeJob"><legend>裁剪范围</legend><label v-for="(title,key) in {x:'裁剪横坐标',y:'裁剪纵坐标',width:'裁剪宽度',height:'裁剪高度'}" :key="key">{{title}}<input v-model.number="crop[key]" type="number" :min="key==='width'||key==='height'?1:0" step="1" :aria-label="title" /></label></fieldset><fieldset v-for="(box,index) in boxes" :key="index" :disabled="!editable || busy || activeJob"><legend>框选 {{index+1}}</legend><label v-for="(title,key) in {x:'横坐标',y:'纵坐标',width:'宽度',height:'高度'}" :key="key">{{title}}<input v-model.number="box[key]" type="number" step="1" :aria-label="`框选 ${index+1} ${title}`" /></label><el-button @click="boxes.splice(index,1)">移除框选 {{index+1}}</el-button></fieldset><div class="actions"><el-button :disabled="busy||!editable||boxes.length>=20||activeJob" @click="addBox">添加框选</el-button><el-button :disabled="busy||!editable||activeJob" @click="resetPlan">重置范围</el-button><el-button :disabled="!editable||!sourceImage||busy||activeJob" @click="preview">预览标注</el-button></div><div v-if="preflight" data-testid="annotation-plan-preview"><p>预览已绑定当前来源与卡片修订；服务端输出 {{preflight.predicted_output?.width_px}} × {{preflight.predicted_output?.height_px}} 像素。模型调用与扣费为零。</p><p v-if="preflight.blocker_codes.length" role="alert">{{preflight.blocker_codes.join('；')}}</p><label><input v-model="reviewed" type="checkbox" aria-label="已核对原页与标注范围" />已核对原页与标注范围</label></div><el-button type="primary" :disabled="!canSubmit" @click="submit">生成标注材料</el-button></div></div></el-card>
    <el-card v-if="job" class="section" shadow="never"><p data-testid="annotation-job-state">标注作业：{{job.status}} · {{job.id}}</p><el-button :disabled="!activeJob||!editable" @click="cancel">取消标注作业</el-button><el-button @click="poll">重新读取作业状态</el-button></el-card>
    <el-card v-if="candidateImage && candidate" class="section" shadow="never"><h3>实际标注候选图</h3><p>未确认材料 · {{candidateCurrent?.validity}} · {{candidate.rendering.image.sha256}}</p><p v-if="candidateCurrent?.warning_codes?.length" role="alert">{{candidateCurrent.warning_codes.join('；')}}</p><img class="candidate-image" :src="candidateImage" alt="实际标注候选图" /><el-button :disabled="!editable||candidateCurrent?.validity!=='current'" @click="editorOpen=true">用于此响应卡</el-button><p class="hint">点击后在响应编辑器填写观察说明并显式保存；标注作业不会修改响应卡，也不会确认证据。</p><ul class="plain-list"><li v-for="item in releaseJobs" :key="item.id">确认图作业：{{item.status}} · {{item.id}}<el-button v-if="['failed','cancelled'].includes(item.status)" :disabled="busy||!authority.canWrite.value||candidateCurrent?.validity!=='current'" @click="retryRelease(item)">重试确认图生成</el-button></li></ul><ul class="plain-list"><li v-for="release in releases" :key="release.id">{{release.decision_validity}} · {{release.releasable?'可用确认图':'历史确认图不可用于导出'}}<DocumentPreview v-if="release.releasable" :source="{kind:'annotation_release',releaseId:release.id,expectedHash:release.rendering.image.sha256}" name="已确认标注图" label="核对确认图" /><span v-else>{{release.blocker_codes.join('；')}}</span></li></ul><div class="actions"><el-button :disabled="!releasePrior.length" @click="turnPage('release',false)">上一页确认图</el-button><el-button :disabled="!releaseCursor" @click="turnPage('release',true)">下一页确认图</el-button><el-button @click="releasePage()">重新核对确认图</el-button></div></el-card>
    <el-card class="section" shadow="never"><template #header>已有标注材料</template><ul class="plain-list"><li v-for="item in candidates" :key="item.id"><el-button :disabled="busy||activeJob" @click="inspect(item.id)">核对标注图 {{item.id}}</el-button><span>未确认材料 · {{item.created_at}}</span></li></ul><div class="actions"><el-button :disabled="!candidatePrior.length" @click="turnPage('candidate',false)">上一页候选图</el-button><el-button :disabled="!candidateCursor" @click="turnPage('candidate',true)">下一页候选图</el-button></div></el-card>
    <el-dialog v-model="editorOpen" title="关联标注材料与响应审阅" width="min(1100px,96vw)" destroy-on-close><CardEditor v-if="editorOpen && row" :row="row" :task-id="taskId" :job-id="jobId" :annotation-candidate="candidate" @updated="updated" @denied="clear" @close="editorOpen=false" /></el-dialog>
  </template>
</template>
<style scoped>
.annotation-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(260px,1fr);gap:20px}.source-canvas{position:relative;width:100%;background:#eee}.source-canvas img{display:block;width:100%}.crop-overlay,.box-overlay{position:absolute;pointer-events:none;box-sizing:border-box}.crop-overlay{border:2px dashed #245dd6;box-shadow:0 0 0 1px #fff}.box-overlay{border:2px solid #dc2626}figure{margin:0}fieldset{display:flex;flex-wrap:wrap;gap:10px;margin:12px 0}fieldset label{display:flex;flex-direction:column;gap:4px;width:120px}input[type=number]{width:100%;padding:6px;border:1px solid var(--border);border-radius:4px}input:focus-visible{outline:2px solid #245dd6;outline-offset:2px}.candidate-image{display:block;max-width:100%;max-height:70vh;object-fit:contain;margin:16px 0}.mono{overflow-wrap:anywhere}@media(max-width:760px){.annotation-grid{grid-template-columns:1fr}}
</style>
