<script setup>
import {computed,onMounted,onUnmounted,ref} from 'vue';
import {useRoute} from 'vue-router';
import {orgAccess,orgRequest,errorText,formatTime,confirmAction} from '../org.js';
import {attachmentRequest,checkedPage,scoped,signedBlob,kinds,reviewStates,nextActions,blockers,fields} from '../attachments.js';
const route=useRoute(),id=route.params.attachmentId,root=ref(null),revision=ref(null),history=ref([]),reviews=ref([]),historyMeta=ref(null),reviewMeta=ref(null),error=ref(''),busy=ref(false),inspected=ref(false),accepted=ref(false),image=ref(''),page=ref(1),assignment=ref(false),reviewer=ref(''),custodian=ref(''),profiles=ref([]),profileId=ref(''),profileRevisionNumber=ref(null),profile=ref(null),field=ref('registration_details'),links=ref([]),linkMeta=ref(null),profileMeta=ref(null),revise=ref(false),file=ref(null),label=ref(''),reviseKind=ref('contract'),reason=ref('wrong_document'),receipt=ref('');
const human=computed(()=>['admin','bidder'].includes(orgAccess.role)),canReview=computed(()=>human.value&&root.value?.active&&root.value.reviewer_user_id===orgAccess.userId),current=computed(()=>revision.value?.id===root.value?.current_revision_id);let stopped=false,epoch=0,requestId=crypto.randomUUID();
function dispose(){if(image.value)URL.revokeObjectURL(image.value);image.value='';inspected.value=false;accepted.value=false;}function clear(){epoch++;dispose();root.value=null;revision.value=null;history.value=[];reviews.value=[];profile.value=null;profiles.value=[];links.value=[];file.value=null;error.value='单位会话已改变，请重新打开详情';}
async function run(work){if(busy.value)return;busy.value=true;error.value='';const generation=epoch;try{await work();}catch(exc){if([401,403,404].includes(exc.status))clear();error.value=errorText(exc);}finally{if(!stopped&&generation===epoch)busy.value=false;}}
async function load(revisionId=null){const generation=epoch;const head=scoped((await attachmentRequest('GET',`/resources/attachments/${id}`)).data.attachment);if(stopped||generation!==epoch)return;root.value=head;reviewer.value=head.reviewer_user_id;custodian.value=head.custodian_user_id;if(human.value){const value=scoped((await attachmentRequest('GET',`/resources/attachments/revisions/${revisionId??route.query.revision??head.current_revision_id}`)).data);if(value.attachment_id!==id)throw new Error('精确修订不属于此档案');if(stopped||generation!==epoch)return;dispose();revision.value=value;label.value=value.metadata.label;reviseKind.value=value.kind;await loadReviews();}await loadHistory();}
async function loadHistory(cursor=null){const result=checkedPage(await attachmentRequest('GET',`/resources/attachments/${id}/revisions?limit=25${cursor?'&cursor='+encodeURIComponent(cursor):''}`));if(!stopped){history.value=result.items;historyMeta.value=result.data;}}
async function loadReviews(cursor=null){const result=checkedPage(await attachmentRequest('GET',`/resources/attachments/revisions/${revision.value.id}/reviews?limit=25${cursor?'&cursor='+encodeURIComponent(cursor):''}`));if(!stopped){reviews.value=result.items;reviewMeta.value=result.data;}}
async function preview(){await run(async()=>{const rid=revision.value.id,p=page.value,blob=await signedBlob(`/resources/attachments/revisions/${rid}/pages/${p}/preview-link?zoom=1`,`/resources/attachments/revisions/${rid}/pages/${p}/preview`);if(stopped||revision.value?.id!==rid||page.value!==p)return;dispose();image.value=URL.createObjectURL(blob);inspected.value=true;});}
async function download(){await run(async()=>{const downloadEpoch=epoch;const rid=revision.value.id,blob=await signedBlob(`/resources/attachments/revisions/${rid}/file/download-link`,`/resources/attachments/revisions/${rid}/file/download`);if(stopped||downloadEpoch!==epoch)return;const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=revision.value.original.name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);inspected.value=true;});}
async function decision(action){if(!canReview.value&&action!=='revoke')return;await run(async()=>{const value=revision.value;const result=await attachmentRequest('POST',`/resources/attachments/revisions/${value.id}/reviews`,{request_id:requestId,expected_state_version:root.value.state_version,expected_review_id:value.latest_review_id,file_id:value.file_id,original_sha256:value.original_sha256,metadata_sha256:value.metadata_sha256,decision:action,reason:action==='approve'?'accepted_for_internal_use':action==='revoke'?'withdrawn_by_org':reason.value});receipt.value=`${reviewStates[action==='approve'?'approved':action==='reject'?'rejected':'revoked']} · 审阅者 ${result.data.reviewed_by} · 回执 ${result.data.id}`;requestId=crypto.randomUUID();await load(value.id);});}
async function assign(){await run(async()=>{await attachmentRequest('POST',`/resources/attachments/${id}/assignment`,{request_id:requestId,expected_state_version:root.value.state_version,custodian_user_id:custodian.value,reviewer_user_id:reviewer.value,reason:'responsibility_changed'});requestId=crypto.randomUUID();assignment.value=false;await load(revision.value?.id);});}
async function deactivate(){if(!await confirmAction('停用后不能恢复本档案。保留原件与历史，现有选择不再可用于新的材料。','停用附件档案','确认停用',true))return;await run(async()=>{await attachmentRequest('POST',`/resources/attachments/${id}/deactivate`,{request_id:requestId,expected_state_version:root.value.state_version,reason:'withdrawn_by_org'});requestId=crypto.randomUUID();await load(revision.value?.id);});}
async function saveRevision(){await run(async()=>{const data=new FormData();data.set('metadata',JSON.stringify({request_id:requestId,expected_state_version:root.value.state_version,metadata:{kind:reviseKind.value,label:label.value},reviewer_user_id:reviewer.value,parts:[],dry_run:false}));data.append('files',file.value);const result=await attachmentRequest('POST',`/resources/attachments/${id}/revisions`,data);requestId=crypto.randomUUID();revise.value=false;file.value=null;await load(result.data.revision_id);});}
async function loadProfiles(cursor=null){const result=await orgRequest('POST','/management/resources/profiles/query',{limit:25,cursor,q:null,state:'active'},{contractVersion:4});if(!stopped){profiles.value=result.items;profileMeta.value=result.data;}}
async function openProfile(){await run(async()=>{const result=await orgRequest('GET',`/management/resources/profiles/${profileId.value}${profileRevisionNumber.value?'?revision='+profileRevisionNumber.value:''}`,undefined,{contractVersion:4});if(stopped)return;profile.value=result.data;await loadLinks();});}
async function loadLinks(cursor=null){const result=checkedPage(await attachmentRequest('GET',`/resources/profiles/revisions/${profile.value.detail.revision.id}/attachments?limit=25&history=true${cursor?'&cursor='+encodeURIComponent(cursor):''}`));if(!stopped){links.value=result.items;linkMeta.value=result.data;}}
async function link(){await run(async()=>{await attachmentRequest('POST',`/resources/profiles/revisions/${profile.value.detail.revision.id}/attachments`,{request_id:requestId,field:field.value,attachment_revision_id:revision.value.id,approval_id:revision.value.latest_review_id});requestId=crypto.randomUUID();receipt.value='已关联精确声明；任务仍需显式选择';await loadLinks();});}
async function withdrawLink(row){await run(async()=>{await attachmentRequest('POST',`/profile-attachment-links/${row.id}/deactivate`,{request_id:requestId,expected_state_version:row.state_version,reason:'declaration_changed'});requestId=crypto.randomUUID();await loadLinks();});}
onMounted(()=>{run(async()=>{await load();if(human.value)await loadProfiles();});window.addEventListener('bid:org-reset',clear);});onUnmounted(()=>{stopped=true;clear();window.removeEventListener('bid:org-reset',clear);});
</script>
<template>
 <nav class="breadcrumb"><RouterLink to="/org/attachments">附件档案</RouterLink><span>/</span><span>精确修订与审阅</span></nav><el-alert v-if="error" :title="error" type="error" :closable="false" role="alert" class="section"/><el-alert v-if="receipt" :title="receipt" type="success" :closable="false" role="status" class="section"/>
 <template v-if="root"><div class="page-header"><div><h2>{{revision?.metadata.label??kinds[root.kind]}}</h2><p class="subtitle">当前修订 {{root.current_revision}} · 工作状态版本 {{root.state_version}} · {{root.active?'可用':'已停用'}}</p></div></div><el-card shadow="never" class="section"><p>保管人：{{root.custodian_user_id}} · 审阅者：{{root.reviewer_user_id}}</p><p>{{nextActions[root.readiness.next_action]}} · {{root.readiness.blockers.map(code=>`${blockers[code]}（${code}）`).join('；')}}</p><div v-if="human&&root.active" class="actions"><el-button @click="assignment=!assignment">调整保管人和审阅者</el-button><el-button @click="revise=!revise">上传更正修订</el-button><el-button @click="deactivate">停用档案</el-button></div><el-form v-if="assignment" label-position="top"><el-form-item label="保管人成员 ID"><el-input v-model="custodian" aria-label="保管人成员 ID"/></el-form-item><el-form-item label="在职审阅者成员 ID"><el-input v-model="reviewer" aria-label="在职审阅者成员 ID"/></el-form-item><el-button :loading="busy" @click="assign">保存责任分配</el-button></el-form><el-form v-if="revise" label-position="top"><el-form-item label="更正显示名称"><el-input v-model="label"/></el-form-item><el-form-item label="更正类别"><el-select v-model="reviseKind"><el-option v-for="(text,key) in kinds" :key="key" :label="text" :value="key"/></el-select></el-form-item><input type="file" accept=".pdf" aria-label="更正 PDF 原件" @change="file=$event.target.files[0]??null"><p>新修订必须重新供应完整 PDF；旧声明关联和任务选择保持精确修订。</p><el-button :disabled="!file" :loading="busy" @click="saveRevision">保存更正修订</el-button></el-form></el-card>
 <el-card v-if="revision" shadow="never" class="section"><template #header><h3>修订 {{revision.revision}} · {{reviewStates[revision.review_state]}}</h3></template><p class="mono">修订 ID {{revision.id}} · 原件 ID {{revision.file_id}}</p><p>{{kinds[revision.kind]}} · {{revision.page_count}} 页 · {{revision.size_bytes}} 字节 · {{formatTime(revision.revised_at??revision.created_at)}} · 修订者 {{revision.revised_by??'未知'}}</p><p class="hint mono">原件 SHA-256 {{revision.original_sha256}}<br>元数据 SHA-256 {{revision.metadata_sha256}}</p><el-alert v-if="!current" title="资料库有较新修订；此处仍为精确历史修订，不自动替换关联与任务选择。" type="warning" :closable="false"/><div class="actions"><el-button :disabled="busy" @click="download">下载此修订原件</el-button><el-input-number v-model="page" :min="1" :max="revision.page_count" aria-label="原件页码" @change="dispose"/><el-button :disabled="busy" @click="preview">核对此页原件</el-button></div><img v-if="image" :src="image" alt="限制级原件页预览" class="page-image"/>
 <template v-if="canReview"><p>可以自己审阅，审阅者身份将记录。接受仅表示内部适用性，不证明真实性。</p><label class="check"><input v-model="accepted" type="checkbox" :disabled="!inspected">已核对此精确修订原件，接受内部使用</label><div class="actions"><el-button v-if="revision.review_state!=='approved'" type="primary" :disabled="busy||!accepted||!inspected" @click="decision('approve')">接受内部使用</el-button><el-select v-if="revision.review_state==='pending'" v-model="reason" aria-label="驳回原因"><el-option label="错误原件" value="wrong_document"/><el-option label="原件无法辨读" value="unreadable_document"/><el-option label="元数据不符" value="metadata_mismatch"/><el-option label="隐私问题" value="privacy_concern"/></el-select><el-button v-if="revision.review_state==='pending'" :disabled="busy||!inspected" @click="decision('reject')">驳回此修订</el-button></div></template><el-button v-if="human&&revision.review_state==='approved'" :disabled="busy" @click="decision('revoke')">撤回此修订接受</el-button></el-card>
 <el-card v-if="human&&revision" shadow="never" class="section"><template #header><h3>关联精确单位声明</h3></template><p>只允许接受后的文件关联非空声明字段；关联不复制到后续资料修订。</p><div class="actions"><el-select v-model="profileId" aria-label="单位资料" style="width:320px"><el-option v-for="row in profiles" :key="row.ref?.resource_id??row.id" :value="row.ref?.resource_id??row.id" :label="row.name??row.id"/></el-select><el-input-number v-model="profileRevisionNumber" :min="1" aria-label="资料精确内容修订号" placeholder="当前修订"/><el-button :disabled="!profileId||busy" @click="openProfile">打开资料精确修订</el-button><el-button :disabled="!profileMeta?.next_cursor||busy" @click="loadProfiles(profileMeta.next_cursor)">下一页资料</el-button></div><template v-if="profile"><p>资料修订 {{profile.detail.revision.revision}} · {{profile.detail.revision.id}}</p><el-select v-model="field" aria-label="关联声明字段"><el-option v-for="(text,key) in fields" :key="key" :label="text" :value="key" :disabled="!profile.detail.revision.data[key]"/></el-select><p class="declaration">{{profile.detail.revision.data[field]||'此字段为空，不能关联'}}</p><el-button type="primary" :disabled="busy||revision.review_state!=='approved'||!profile.detail.revision.data[field]||!root.active" @click="link">关联此精确修订与声明</el-button><ul><li v-for="row in links" :key="row.id">{{fields[row.field]}} · 文件修订 {{row.attachment_revision_id}} · {{row.active?'有效':'已停用'}}<el-button v-if="row.active" :disabled="busy" @click="withdrawLink(row)">停用关联</el-button></li></ul><el-button :disabled="!linkMeta?.next_cursor" @click="loadLinks(linkMeta.next_cursor)">下一页声明关联</el-button></template></el-card>
 <el-card shadow="never" class="section"><template #header><h3>内容修订历史</h3></template><el-table v-show="history.length" :data="history" aria-label="附件内容历史"><el-table-column label="修订"><template #default="{row}"><el-button :disabled="!human||busy" @click="run(()=>load(row.id))">修订 {{row.revision}}</el-button></template></el-table-column><el-table-column label="审阅"><template #default="{row}">{{reviewStates[row.review_state]}}</template></el-table-column><el-table-column prop="id" label="精确修订 ID"/></el-table><el-button :disabled="!historyMeta?.next_cursor" @click="loadHistory(historyMeta.next_cursor)">下一页内容历史</el-button><h3>此修订审阅历史</h3><el-table v-show="reviews.length" :data="reviews" aria-label="附件审阅历史"><el-table-column prop="decision" label="决定"/><el-table-column prop="reviewed_by" label="审阅成员"/><el-table-column label="时间"><template #default="{row}">{{formatTime(row.reviewed_at)}}</template></el-table-column></el-table><el-button :disabled="!reviewMeta?.next_cursor" @click="loadReviews(reviewMeta.next_cursor)">下一页审阅历史</el-button></el-card>
 </template>
</template>
<style scoped>.page-image{display:block;max-width:100%;max-height:70vh;margin-top:16px;border:1px solid var(--el-border-color)}.declaration{white-space:pre-wrap}h3{margin:0}</style>
