<script setup>
import {computed,onMounted,onUnmounted,ref,watch} from 'vue';
import {useRoute,useRouter} from 'vue-router';
import {orgAccess,errorText,formatTime} from '../org.js';
import {attachmentRequest,checkedPage,kinds,reviewStates,nextActions,blockers} from '../attachments.js';
const router=useRouter(),route=useRoute(),rows=ref([]),meta=ref(null),cursor=ref(null),previous=ref([]),kind=ref(''),search=ref(''),history=ref(false),error=ref(''),busy=ref(false),upload=ref(false),file=ref(null),label=ref(''),reviewer=ref(''),uploadKind=ref('business_licence');
const canWrite=computed(()=>['admin','bidder'].includes(orgAccess.role));let generation=0,stopped=false,timer=null,requestId=crypto.randomUUID();
async function load(next=null){const run=++generation;busy.value=true;error.value='';rows.value=[];try{const result=checkedPage(await attachmentRequest('POST','/management/resources/attachments/query',{limit:25,history:history.value,kind:kind.value||null,q:search.value.trim()||null,cursor:next}));if(run===generation&&!stopped){rows.value=result.items;meta.value=result.data;cursor.value=next;}}catch(exc){if(exc.name!=='AbortError')error.value=errorText(exc);}finally{if(run===generation)busy.value=false;}}
watch(search,()=>{clearTimeout(timer);generation++;rows.value=[];meta.value=null;timer=setTimeout(restart,300);});
function restart(){previous.value=[];load();}function next(){if(meta.value?.next_cursor){previous.value.push(cursor.value);load(meta.value.next_cursor);}}function back(){if(previous.value.length)load(previous.value.pop());}
async function submit(){if(!file.value||busy.value)return;busy.value=true;error.value='';try{if(file.value.size>40*1024*1024)throw new Error('文件超过 40 MiB');const data=new FormData();data.set('metadata',JSON.stringify({request_id:requestId,metadata:{kind:uploadKind.value,label:label.value},reviewer_user_id:reviewer.value,parts:[],dry_run:false}));data.append('files',file.value);const result=await attachmentRequest('POST','/resources/attachments',data);if(stopped)return;requestId=crypto.randomUUID();upload.value=false;file.value=null;router.push(`/org/attachments/${result.data.attachment_id}`);}catch(exc){error.value=errorText(exc);}finally{busy.value=false;}}
function reset(){clearTimeout(timer);generation++;rows.value=[];meta.value=null;file.value=null;label.value='';reviewer.value='';upload.value=false;error.value='单位会话已改变，请重新打开附件档案';}
onMounted(()=>{load();window.addEventListener('bid:org-reset',reset);});onUnmounted(()=>{stopped=true;reset();window.removeEventListener('bid:org-reset',reset);});
</script>
<template>
 <div class="page-header"><div><h2>附件档案</h2><p class="subtitle">上传者负责保管，指定成员审阅原件；接受内部使用与逐页隐私审阅分别记录，不确认响应证据。</p></div><el-button v-if="canWrite" type="primary" @click="upload=true">上传附件</el-button></div>
 <el-alert v-if="error" :title="error" type="error" :closable="false" role="alert" class="section"/>
 <el-card shadow="never" class="section"><div class="actions"><div><label for="attachment-search">搜索类别或附件 ID 前缀</label><el-input id="attachment-search" v-model="search" aria-label="搜索类别或附件 ID 前缀" maxlength="100" clearable placeholder="contract 或附件 ID 前缀" style="width:260px"/></div><el-select v-model="kind" aria-label="附件类别" style="width:180px" @change="restart"><el-option label="全部类别" value=""/><el-option v-for="(text,key) in kinds" :key="key" :label="text" :value="key"/></el-select><label class="check"><input v-model="history" type="checkbox" @change="restart">包含已停用档案</label><el-button :disabled="busy" @click="restart">从第一页读取</el-button></div>
 <p v-if="busy" role="status">正在读取附件…</p><el-empty v-if="meta&&!rows.length&&!busy" description="暂无附件档案"/>
 <div role="region" aria-label="附件档案列表"><el-table v-show="rows.length>0" :data="rows"><el-table-column label="附件 / 修订" min-width="260"><template #default="{row}"><RouterLink :to="`/org/attachments/${row.id}${route.query.task?'?task='+route.query.task:''}`">{{kinds[row.kind]}} · 修订 {{row.current_revision}}</RouterLink><p class="hint mono">{{row.id}}</p></template></el-table-column><el-table-column label="原件审阅" min-width="160"><template #default="{row}">{{reviewStates[row.review_state]}} · {{row.active?'可用':'已停用'}}</template></el-table-column><el-table-column label="负责人 / 下一步" min-width="260"><template #default="{row}">{{nextActions[row.readiness.next_action]}}<p class="hint">{{row.readiness.responsible_user_id??'暂无'}} · {{row.readiness.blockers.map(code=>`${blockers[code]??code}（${code}）`).join('；')}}</p></template></el-table-column><el-table-column label="创建时间" min-width="160"><template #default="{row}">{{formatTime(row.revised_at??row.created_at)}}<p class="hint">修订者 {{row.revised_by??'未知'}}</p></template></el-table-column></el-table></div>
 <div class="actions"><el-button :disabled="busy||!previous.length" @click="back">上一页</el-button><el-button :disabled="busy||!meta?.next_cursor" @click="next">下一页</el-button><span class="hint">每页最多 25 条；详情才读取限制级原件信息。</span></div></el-card>
 <el-dialog v-model="upload" title="上传一个未旋转 PDF" width="min(600px,calc(100vw - 24px))" :close-on-click-modal="false"><el-form label-position="top"><el-form-item label="附件类别"><el-select v-model="uploadKind" aria-label="上传附件类别"><el-option v-for="(text,key) in kinds" :key="key" :label="text" :value="key"/></el-select></el-form-item><el-form-item label="显示名称（仅原件读者可读）"><el-input v-model="label" aria-label="附件显示名称" maxlength="200"/></el-form-item><el-button :disabled="busy" @click="reviewer=orgAccess.userId">指定自己为审阅者</el-button><el-form-item label="审阅者成员 ID（在职管理员或商务审核，可选择自己）"><el-input v-model="reviewer" aria-label="附件审阅者成员 ID"/></el-form-item><label>PDF 原件<input type="file" accept=".pdf,application/pdf" aria-label="PDF 原件" @change="file=$event.target.files[0]??null"></label></el-form><p>最多 40 MiB、200 页。多文件、图片和旋转尚未启用（attachment_upload_mode_not_enabled）。服务器核验原件后保存。</p><template #footer><el-button :disabled="busy" @click="upload=false">取消</el-button><el-button type="primary" :loading="busy" :disabled="!file||!label.trim()||!reviewer" @click="submit">保存并交审阅者</el-button></template></el-dialog>
</template>
