<script setup>
import {computed,onMounted,onUnmounted,ref} from "vue";
import {useRoute} from "vue-router";
import TaskNavigation from "../components/TaskNavigation.vue";
import {confirmAction,formatTime,jobStatuses,orgRequest} from "../org.js";
import {ApiError} from "../api.js";
import {productTaskAuthority} from "../products.js";
import {checkPage,feedbackKinds,memoryError,memoryReader,rememberCursor,validId} from "../memories.js";
const route=useRoute(),taskId=route.params.taskId,reader=memoryReader(),rows=ref([]),meta=ref(null),cursor=ref(null),previous=ref([]),authority=ref(null),error=ref(""),notice=ref(""),loading=ref(false),busy=ref(false),selected=ref(null),job=ref(null),jobError=ref("");let stopped=false,generation=0,timer=null,failures=0;
const writable=computed(()=>!!authority.value?.canPin),terminal=status=>["succeeded","failed","cancelled"].includes(status);
function clear(){stopped=true;generation++;clearTimeout(timer);reader.stop();rows.value=[];meta.value=null;authority.value=null;selected.value=null;job.value=null;notice.value="";error.value="任务或单位不可访问，请重新打开反馈队列";}
async function load(next=null){if(stopped)return;const run=++generation;loading.value=true;error.value="";rows.value=[];meta.value=null;cursor.value=next;try{if(!validId(taskId))throw new Error("任务 ID 无效");authority.value=await productTaskAuthority(reader,taskId);if(stopped||run!==generation)return;const params=new URLSearchParams({management:"true",limit:"25"});if(next)params.set("cursor",next);const result=checkPage(await reader.read("list","GET",`/tasks/${taskId}/memory-feedback?${params}`),{taskId});if(stopped||run!==generation)return;rows.value=result.items;meta.value=result.data;if(route.query.job&&!selected.value){const match=rows.value.find(row=>row.candidate_job_id===route.query.job);if(match)await openJob(match);else notice.value="指定作业尚不在本页记录中，请翻页核对对应反馈；只允许恢复已有作业。";}}
catch(exc){if(run===generation&&exc.name!=="AbortError"){if([401,403,404].includes(exc.status)){clear();}error.value=memoryError(exc);}}finally{if(run===generation)loading.value=false;}}
function restart(){previous.value=[];load();}function next(){if(meta.value?.next_cursor){rememberCursor(previous.value,cursor.value);load(meta.value.next_cursor);}}function back(){if(previous.value.length)load(previous.value.pop());}
function schedule(delay){clearTimeout(timer);if(!stopped&&!document.hidden)timer=setTimeout(readJob,delay);}
async function readJob(){clearTimeout(timer);if(stopped||!selected.value||document.hidden)return;const record=selected.value;jobError.value="";try{const response=await reader.read("job","GET",`/jobs/${record.candidate_job_id}`);if(stopped||selected.value!==record)return;const value=response.data;if(value.id!==record.candidate_job_id||value.kind!=="memory_candidate"||!Object.hasOwn(jobStatuses,value.status)||!Array.isArray(value.result?.items??[])||(value.result?.items??[]).some(item=>!record.candidate_event_ids.includes(item.event_id)||item.memory_id!=null&&!validId(item.memory_id)))throw new ApiError(502,"invalid_response","候选作业或事件范围不符合契约");job.value=value;failures=0;if(!terminal(value.status))schedule(2000);}
catch(exc){if(exc.name==="AbortError")return;if([401,403,404].includes(exc.status)){clear();error.value=memoryError(exc);return;}jobError.value=memoryError(exc);failures++;if(failures<=5&&(!exc.status||exc.status===429||exc.status>=500))schedule(Math.max(exc.retryAfter||0,Math.min(30000,2000*2**failures)));}}
async function openJob(row){if(!row.candidate_job_id)return;clearTimeout(timer);reader.cancel("job");selected.value=row;job.value=null;jobError.value="";failures=0;await readJob();}
async function retry(){const record=selected.value;if(!record||!writable.value||busy.value)return;if(!await confirmAction(`恢复已保存候选作业 ${record.candidate_job_id}？只使用该作业已记录的 ${record.candidate_event_ids.length} 个反馈事件，不改变卡片决定。`,"恢复候选作业","确认恢复作业"))return;busy.value=true;error.value="";notice.value="";
try{authority.value=await productTaskAuthority(reader,taskId);if(!writable.value){error.value="需要活动任务负责人或协作者，并具备记忆写入权限";return;}const response=await orgRequest("POST",`/tasks/${taskId}/memory-candidates`,{event_ids:[...record.candidate_event_ids],action:{retry:true}},{contractVersion:4});if(stopped)return;if(response.data.job_id!==record.candidate_job_id||response.data.task_id!==taskId||response.data.reused!==true)throw new ApiError(502,"invalid_response","恢复回执必须引用原已保存作业");notice.value="已恢复原候选作业；卡片人工决定保留，候选仍需管理员审核。";await readJob();}
catch(exc){if(exc.name==="AbortError")return;if([401,403,404].includes(exc.status)){clear();error.value=memoryError(exc);return;}if(exc.code==="queue_unavailable"&&exc.payload?.data.job_id===record.candidate_job_id){notice.value="人工卡片决定已保存。原候选作业仍已保存，派发暂未完成，可再次主动恢复此作业。";await readJob();}else{error.value=!exc.status?"恢复结果尚未确定，请先核对原作业状态后再主动操作；不会自动重试。":memoryError(exc);if(!exc.status)await readJob();}}
finally{busy.value=false;}}
function visibility(){if(document.hidden){clearTimeout(timer);reader.cancel("job");}else if(selected.value&&!terminal(job.value?.status))readJob();}
onMounted(()=>{window.addEventListener("bid:org-reset",clear);document.addEventListener("visibilitychange",visibility);load();});onUnmounted(()=>{stopped=true;clearTimeout(timer);reader.stop();window.removeEventListener("bid:org-reset",clear);document.removeEventListener("visibilitychange",visibility);});
</script>
<template>
  <div class="page-header"><div><h2>记忆反馈队列</h2><p class="subtitle">仅查看已记录的人工卡片反馈与候选作业。人工确认仅形成评价样本，不生成记忆候选。</p></div></div><TaskNavigation :task-id="taskId"/>
  <el-alert v-if="error" :title="error" type="error" show-icon :closable="false" role="alert" class="section"/><p v-if="notice" role="status" class="notice">{{notice}}</p>
  <el-card v-if="authority" shadow="never" class="section"><p v-if="authority.workflow.state==='archived'">任务已归档，只读历史，无法恢复作业。</p><p v-else-if="!writable">恢复作业需要任务负责人或协作者及记忆写入权限；审阅者和观察者只读。</p><p v-if="loading" role="status">正在读取已记录反馈…</p>
    <el-table v-show="!loading&&rows.length" :data="rows" row-key="id" aria-label="已记录记忆反馈"><el-table-column label="人工事件 / 精确卡片修订" min-width="270"><template #default="{row}">{{feedbackKinds[row.kind]}}<p class="hint mono">事件 {{row.id}}</p><p class="hint mono">原修订 {{row.before_revision_id}}</p><p class="hint mono">决定修订 {{row.after_revision_id}}</p></template></el-table-column><el-table-column label="操作者 / 时间" min-width="220"><template #default="{row}">{{row.actor_user_id}}<p class="hint">{{formatTime(row.created_at)}}</p></template></el-table-column><el-table-column label="已记录候选作业" min-width="240"><template #default="{row}"><template v-if="row.candidate_job_id"><code>{{row.candidate_job_id}}</code><p>{{jobStatuses[row.candidate_job_status]??row.candidate_job_status}}</p><el-button @click="openJob(row)">查看作业与恢复动作</el-button></template><span v-else>{{row.kind==='card_confirmed'?'仅评价样本，无候选作业':'无候选作业记录'}}</span></template></el-table-column><el-table-column label="结果候选 / 下一步" min-width="170"><template #default="{row}"><RouterLink v-if="row.candidate_memory_id" :to="`/org/memory/${row.candidate_memory_id}`">核对生成候选与审核</RouterLink><span v-else>保留人工决定，查看作业结果</span></template></el-table-column></el-table>
    <el-empty v-if="!loading&&meta&&!rows.length" description="暂无已记录人工反馈"/><div class="actions"><el-button :disabled="loading" @click="restart">从第一页读取反馈</el-button><el-button :disabled="loading||!previous.length" @click="back">上一页反馈</el-button><el-button :disabled="loading||!meta?.next_cursor" @click="next">下一页反馈</el-button><span v-if="meta" class="hint">本页 {{meta.returned}} 条</span></div></el-card>
  <el-card v-if="selected" shadow="never" class="section" aria-label="已保存候选作业"><template #header><h3>已保存候选作业</h3></template><p class="mono">{{selected.candidate_job_id}}</p><p>人工卡片决定已经保存。恢复作业只处理原记录事件，不编辑或补建反馈。</p><p v-if="job" role="status">作业状态：{{jobStatuses[job.status]}}<span v-if="job.result?.completion==='partial'"> · 部分完成，请逐项核对</span></p><el-alert v-if="jobError" :title="jobError" type="error" :closable="false" role="alert"/><p v-if="job?.error">失败代码：{{job.error.code??'未知'}}</p><ul v-if="job?.result?.items?.length"><li v-for="item in job.result.items" :key="item.event_id">事件 {{item.event_id}} · {{item.outcome}} <RouterLink v-if="item.memory_id" :to="`/org/memory/${item.memory_id}`">核对生成候选</RouterLink><span v-if="item.error_code"> · {{item.error_code}}</span></li></ul><div class="actions"><el-button @click="readJob">重新核对原作业</el-button><el-button v-if="writable&&job&&['queued','failed','cancelled'].includes(job.status)" type="primary" :loading="busy" :disabled="busy" @click="retry">恢复已保存作业</el-button></div><p class="hint">feedback-copy-v1 从精确已记录事件生成候选，不调用模型，不自动审核。失败或未确定结果不会自动提交新作业。</p></el-card>
</template>
<style scoped>code{overflow-wrap:anywhere}.mono{overflow-wrap:anywhere}</style>
