<script setup>
import {computed,nextTick,onMounted,onUnmounted,ref,watch} from "vue";
import {onBeforeRouteLeave} from "vue-router";
import {confirmAction,formatTime,orgRequest} from "../org.js";
import {blankMemory,checkMemory,checkPage,kinds,memoryError,memoryPath,memoryReader,memoryWriter,rememberCursor,statuses} from "../memories.js";
import MemoryEditor from "../components/MemoryEditor.vue";
const reader=memoryReader(),search=ref(""),kind=ref(""),status=ref(""),expiry=ref("all"),tags=ref(""),rows=ref([]),meta=ref(null),cursor=ref(null),previous=ref([]),loading=ref(false),busy=ref(false),error=ref(""),editing=ref(false),form=ref(blankMemory()),receipt=ref(null),revoked=ref(false),outcomeUnknown=ref(false),outcomeChecked=ref(false),outcomeNotice=ref("");
let stopped=false,generation=0,timer,changingForOutcome=false;const writable=computed(()=>!revoked.value&&memoryWriter()),dirty=computed(()=>editing.value&&JSON.stringify(form.value)!==JSON.stringify(blankMemory()));
async function load(next=null,checkOutcome=false){if(stopped)return;if(outcomeUnknown.value)outcomeChecked.value=false;const run=++generation;reader.cancel("list");loading.value=true;rows.value=[];meta.value=null;cursor.value=next;error.value="";
try{const selected=tags.value.split(/[,，]/).map(tag=>tag.trim().toLowerCase()).filter(Boolean);if(selected.length>20||selected.some(tag=>tag.length>40)||new Set(selected).size!==selected.length)throw new Error("标签必须唯一且最多 20 个，每个最多 40 字");const result=checkPage(await reader.read("list","POST",`${memoryPath}/query`,{scope:"org",q:search.value.trim()||null,kind:kind.value||null,status:status.value||null,tags:selected,expiry:expiry.value,include_deleted:false,cursor:next,limit:25}));if(stopped||run!==generation)return;rows.value=result.items;meta.value=result.data;if(checkOutcome===true&&outcomeUnknown.value)outcomeChecked.value=true;}
catch(exc){if(run===generation&&exc.name!=="AbortError"){if([401,403,404].includes(exc.status)){revoked.value=true;clear();}error.value=memoryError(exc);if(["management_cursor_invalid","management_cursor_expired"].includes(exc.code)){cursor.value=null;previous.value=[];}}}finally{if(run===generation)loading.value=false;}}
function reset(checkOutcome=false){previous.value=[];return load(null,checkOutcome);}function next(){if(meta.value?.has_more){rememberCursor(previous.value,cursor.value);load(meta.value.next_cursor);}}function back(){if(previous.value.length)load(previous.value.pop());}
watch([search,kind,status,expiry,tags],()=>{if(stopped||changingForOutcome)return;outcomeChecked.value=false;generation++;reader.cancel("list");rows.value=[];meta.value=null;loading.value=true;clearTimeout(timer);timer=setTimeout(reset,300);});
async function save(){if(!writable.value||busy.value||outcomeUnknown.value)return;busy.value=true;error.value="";try{const response=await orgRequest("POST","/memories",{target:{scope:"org"},...form.value},{contractVersion:4});if(stopped)return;receipt.value=checkMemory(response.data.memory);editing.value=false;form.value=blankMemory();outcomeNotice.value="";reset();}catch(exc){if(exc.name==="AbortError")return;error.value=memoryError(exc);if([401,403,404].includes(exc.status)){revoked.value=true;clear();error.value=memoryError(exc);}else if(!exc.status){outcomeUnknown.value=true;outcomeChecked.value=false;outcomeNotice.value="保存结果尚未确定，草稿已保留。请主动重新读取记忆库，核对是否已有候选；完成核对并明确允许前，无法再次提交。不会自动重试。";error.value="";}}finally{busy.value=false;}}
async function cancel(){if(dirty.value&&!await confirmAction("放弃未保存的记忆？","放弃编辑","放弃"))return;editing.value=false;form.value=blankMemory();}
async function rereadOutcome(){if(!outcomeUnknown.value||busy.value||stopped)return;changingForOutcome=true;search.value=form.value.content.conflict_key;kind.value=form.value.content.kind;status.value="candidate";expiry.value="all";tags.value="";await nextTick();changingForOutcome=false;clearTimeout(timer);await reset(true);}
async function acknowledgeOutcome(){if(!outcomeUnknown.value||!outcomeChecked.value||loading.value)return;if(!await confirmAction("前次请求可能已经创建候选。已核对服务器记录，仍允许再次主动提交保留的草稿？","核对未确定结果","允许再次提交"))return;if(stopped||!outcomeUnknown.value||!outcomeChecked.value)return;outcomeUnknown.value=false;outcomeChecked.value=false;outcomeNotice.value="已核对服务器记录并允许再次提交；请主动保存草稿，不会自动重发。";}
function clear(){stopped=true;generation++;clearTimeout(timer);reader.stop();loading.value=false;rows.value=[];meta.value=null;editing.value=false;form.value=blankMemory();receipt.value=null;outcomeUnknown.value=false;outcomeChecked.value=false;outcomeNotice.value="";search.value="";tags.value="";error.value="单位会话已改变，请重新打开记忆库";}
function unload(event){if(dirty.value){event.preventDefault();event.returnValue="";}}
onBeforeRouteLeave(async()=>!dirty.value||await confirmAction("放弃未保存的记忆？","放弃编辑","放弃"));
onMounted(()=>{load();window.addEventListener("bid:org-reset",clear);window.addEventListener("beforeunload",unload);});onUnmounted(()=>{stopped=true;clearTimeout(timer);reader.stop();window.removeEventListener("bid:org-reset",clear);window.removeEventListener("beforeunload",unload);});
</script>
<template>
  <div class="page-header"><div><h2>单位记忆</h2><p class="subtitle">成员提出候选，单位管理员审核。记忆指导工作，不能作为证据或人工确认。</p></div><el-button v-if="writable&&!editing" type="primary" :disabled="outcomeUnknown" @click="editing=true;receipt=null">新增候选记忆</el-button></div>
  <el-alert v-if="error" :title="error" type="error" show-icon :closable="false" role="alert" class="section"/>
  <el-alert v-if="outcomeNotice" :title="outcomeNotice" type="warning" :closable="false" role="status" class="section"/><div v-if="outcomeUnknown" class="actions"><el-button :disabled="loading||busy" @click="rereadOutcome">重新读取并核对未确定保存</el-button><el-button :disabled="!outcomeChecked||loading||busy" @click="acknowledgeOutcome">已核对记录，允许再次提交</el-button></div>
  <p v-if="receipt" role="status">已创建候选修订 {{receipt.current.revision}}；<RouterLink :to="`/org/memory/${receipt.id}?revision=${receipt.current.revision}`">查看候选与审核下一步</RouterLink></p>
  <el-card v-if="editing" shadow="never" class="section"><template #header><h3>新增单位候选</h3></template><MemoryEditor v-model="form" :busy="busy" :blocked="outcomeUnknown" @save="save" @cancel="cancel"/></el-card>
  <el-card shadow="never" class="section"><div class="actions filters"><div><label for="memory-search">搜索记忆</label><el-input id="memory-search" v-model="search" maxlength="200" placeholder="正文、冲突键和标签的前缀词" clearable/></div><div><label for="filter-kind">类型</label><select id="filter-kind" v-model="kind"><option value="">全部</option><option v-for="(label,key) in kinds" :key="key" :value="key">{{label}}</option></select></div><div><label for="filter-status">存储状态</label><select id="filter-status" v-model="status"><option value="">全部</option><option v-for="key in ['candidate','active','disabled']" :key="key" :value="key">{{statuses[key]}}</option></select></div><div><label for="filter-expiry">有效期</label><select id="filter-expiry" v-model="expiry"><option value="all">全部</option><option value="expired">已过期</option><option value="unexpired">未过期</option></select></div><div><label for="filter-tags">包含全部标签</label><input id="filter-tags" v-model="tags" placeholder="逗号分隔" autocomplete="off"/></div><el-button :disabled="loading" @click="reset">重新读取记忆</el-button></div>
    <p v-if="loading" role="status">正在读取记忆…</p>
    <el-table v-show="!loading&&rows.length" :data="rows" row-key="id" aria-label="记忆列表"><el-table-column label="记忆 / 精确修订" min-width="260"><template #default="{row}"><RouterLink :to="`/org/memory/${row.id}?revision=${row.current.revision}`">{{row.current.content.conflict_key}}</RouterLink><p>{{row.current.content.text}}</p><p class="hint">{{kinds[row.current.content.kind]}} · 修订 {{row.current.revision}} · {{row.current.content.tags.join('、')}}</p></template></el-table-column><el-table-column label="存储 / 生效状态" min-width="190"><template #default="{row}">{{statuses[row.current.status]}}<p class="hint">当前：{{statuses[row.effective_status]}}</p></template></el-table-column><el-table-column label="当前修订创建人 / 时间" min-width="230"><template #default="{row}">{{row.current.created_by??'未知'}}<p class="hint">{{formatTime(row.current.created_at)}}</p><p v-if="row.current.expires_at" class="hint">到期 {{formatTime(row.current.expires_at)}}</p></template></el-table-column><el-table-column label="下一步" width="130"><template #default="{row}"><RouterLink :to="`/org/memory/${row.id}?revision=${row.current.revision}`">{{row.current.status==='candidate'?'核对候选':'查看状态与修订'}}</RouterLink></template></el-table-column></el-table>
    <el-empty v-if="!loading&&meta&&!rows.length&&!error" description="没有符合条件的记忆"/><div class="actions"><el-button :disabled="loading||!previous.length" @click="back">上一页记忆</el-button><el-button :disabled="loading||!meta?.has_more" @click="next">下一页记忆</el-button><span v-if="meta" class="hint">本页 {{meta.returned}} 项 · 服务器读取时间 {{formatTime(meta.as_of)}}；过期状态由服务器决定。</span></div>
  </el-card>
</template>
<style scoped>.filters label{display:block;margin-bottom:5px}.filters select,.filters input{padding:7px;border:1px solid var(--border);border-radius:5px;background:var(--surface);color:inherit}.filters>div:first-child{width:min(320px,100%)}</style>
