<script setup>
import {computed,onMounted,onUnmounted,ref} from "vue";
import {onBeforeRouteLeave,useRoute} from "vue-router";
import {confirmAction,formatTime,orgAccess,orgRequest} from "../org.js";
import {blankMemory,checkDetail,checkMemory,checkPage,kinds,memoryError,memoryPath,memoryReader,memoryWriter,rememberCursor,statuses,validId} from "../memories.js";
import MemoryEditor from "../components/MemoryEditor.vue";
const route=useRoute(),id=route.params.memoryId,number=route.query.revision===undefined?null:Number(route.query.revision),reader=memoryReader(),detail=ref(null),history=ref([]),historyMeta=ref(null),historyCursor=ref(null),previous=ref([]),error=ref(""),busy=ref(false),loading=ref(false),editing=ref(false),form=ref(blankMemory()),baseline=ref(""),reason=ref(""),reviewed=ref(false),conflict=ref(null),receipt=ref(null);let stopped=false,generation=0;
const memory=computed(()=>detail.value?.memory),revision=computed(()=>memory.value?.current),current=computed(()=>revision.value?.revision===detail.value?.current_revision),dirty=computed(()=>editing.value&&JSON.stringify(form.value)!==baseline.value),admin=computed(()=>orgAccess.role==="admin");
function allowed(action){return !!detail.value&&current.value&&detail.value.actions.some(hint=>hint.action===action&&hint.allowed)&&(action==="revise"?memoryWriter():admin.value);}
async function readHead(){return checkDetail((await reader.read("detail","GET",`${memoryPath}/${id}`)).data,id);}
async function load(){if(stopped)return;const run=++generation;loading.value=true;error.value="";detail.value=null;reviewed.value=false;reason.value="";try{if(!validId(id)||number!==null&&(!Number.isInteger(number)||number<1))throw new Error("记忆 ID 或修订无效");const response=await reader.read("detail","GET",`${memoryPath}/${id}${number===null?'':`?revision=${number}`}`);const value=checkDetail(response.data,id,number);if(!stopped&&run===generation)detail.value=value;}catch(exc){if(run===generation&&exc.name!=="AbortError")error.value=memoryError(exc);}finally{if(run===generation)loading.value=false;}}
async function loadHistory(cursor=null){if(!detail.value||stopped)return;try{const response=checkPage(await reader.read("history","POST",`${memoryPath}/${id}/history/query`,{cursor,limit:25}),{historyId:id});if(stopped)return;history.value=response.items;historyMeta.value=response.data;historyCursor.value=cursor;}catch(exc){if(exc.name!=="AbortError"){if([401,403,404].includes(exc.status))clear();error.value=memoryError(exc);history.value=[];historyMeta.value=null;if(["management_cursor_invalid","management_cursor_expired"].includes(exc.code))previous.value=[];}}}
function nextHistory(){if(historyMeta.value?.has_more){rememberCursor(previous.value,historyCursor.value);loadHistory(historyMeta.value.next_cursor);}}function backHistory(){if(previous.value.length)loadHistory(previous.value.pop());}
function startEdit(){if(!allowed("revise"))return;form.value={content:JSON.parse(JSON.stringify(revision.value.content)),expires_at:revision.value.expires_at??null};baseline.value=JSON.stringify(form.value);editing.value=true;reviewed.value=false;reason.value="";conflict.value=null;receipt.value=null;}
async function cancel(){if(dirty.value&&!await confirmAction("放弃未保存的候选内容？","放弃编辑","放弃"))return;editing.value=false;form.value=blankMemory();conflict.value=null;}
async function recover(exc){reviewed.value=false;reason.value="";if([401,403,404].includes(exc.status)){clear();error.value=memoryError(exc);return;}if(exc.status===409||!exc.status){try{const head=await readHead();if(stopped)return;conflict.value=head;error.value=!exc.status?"操作结果尚未确定。已读取服务器修订，请核对后再主动操作；不会自动重试。":"修订或状态发生冲突。草稿已保留，审核勾选已清除。请核对服务器修订后主动决定。";}catch(readError){if([401,403,404].includes(readError.status))clear();else{detail.value=null;history.value=[];}error.value=memoryError(readError);}}}
function useHead(){if(!conflict.value)return;detail.value=conflict.value;conflict.value=null;reviewed.value=false;reason.value="";}
async function save(){if(!editing.value||busy.value||!allowed("revise")||conflict.value)return;busy.value=true;error.value="";try{const response=await orgRequest("PUT",`/memories/${id}`,{expected_revision:revision.value.revision,...form.value},{contractVersion:4});if(stopped)return;receipt.value=checkMemory(response.data.memory,id);editing.value=false;form.value=blankMemory();detail.value=await readHead();previous.value=[];await loadHistory();}catch(exc){if(exc.name==="AbortError")return;error.value=memoryError(exc);await recover(exc);}finally{busy.value=false;}}
async function decide(action){if(busy.value||editing.value||conflict.value||!allowed(action)||!reason.value.trim()||action==="approve"&&!reviewed.value)return;if(!await confirmAction(`${action==='approve'?'审核通过':action==='reject'?'驳回并停用':'停用'}精确修订 ${revision.value.revision}？原因仅保留哈希。` ,"记忆人工决定","确认决定",action!=="approve"))return;busy.value=true;error.value="";
try{const response=await orgRequest("POST",`/memories/${id}/${action==='disable'?'disable':'decisions'}`,{expected_revision:revision.value.revision,reason:reason.value.trim(),...(action==='disable'?{}:{action})},{contractVersion:4});if(stopped)return;receipt.value=checkMemory(response.data.memory,id);reviewed.value=false;reason.value="";detail.value=await readHead();previous.value=[];await loadHistory();}catch(exc){if(exc.name==="AbortError")return;error.value=memoryError(exc);if(exc.code==="memory_conflict_key")reviewed.value=false;else await recover(exc);}finally{busy.value=false;}}
function clear(){stopped=true;generation++;reader.stop();detail.value=null;history.value=[];historyMeta.value=null;historyCursor.value=null;previous.value=[];editing.value=false;form.value=blankMemory();baseline.value="";conflict.value=null;receipt.value=null;reviewed.value=false;reason.value="";error.value="单位会话已改变，请重新打开记忆详情";}
function unload(event){if(dirty.value){event.preventDefault();event.returnValue="";}}
onBeforeRouteLeave(async()=>!dirty.value||await confirmAction("放弃未保存的候选内容？","放弃编辑","放弃"));onMounted(async()=>{window.addEventListener("bid:org-reset",clear);window.addEventListener("beforeunload",unload);await load();if(detail.value)await loadHistory();});onUnmounted(()=>{stopped=true;reader.stop();window.removeEventListener("bid:org-reset",clear);window.removeEventListener("beforeunload",unload);});
</script>
<template>
  <nav class="breadcrumb"><RouterLink to="/org/memory">单位记忆</RouterLink><span>/</span><span>精确修订详情</span></nav><p v-if="loading" role="status">正在读取记忆精确修订…</p><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" role="alert" class="section"/>
  <template v-if="detail"><div class="page-header"><div><h2>{{revision.content.conflict_key}}</h2><p class="subtitle">{{kinds[revision.content.kind]}} · 当前展示修订 {{revision.revision}} · 服务器最新修订 {{detail.current_revision}}</p></div><el-tag>{{statuses[detail.current_effective_status]}}</el-tag></div>
    <el-alert title="记忆不能作为证据，也不能替代人工确认" type="warning" :closable="false" class="section"/><el-alert v-if="!current" title="历史修订已被取代，不代表当前生效内容" type="warning" :closable="false" role="status" class="section"/>
    <p v-if="receipt" role="status">已保存修订 {{receipt.current.revision}} · {{statuses[receipt.effective_status]}}</p>
    <el-card shadow="never" class="section"><template #header><div class="section-title"><h3>内容与责任</h3><el-button v-if="allowed('revise')&&!editing" @click="startEdit">编辑为候选</el-button><RouterLink v-if="!current" :to="`/org/memory/${id}?revision=${detail.current_revision}`">查看当前修订</RouterLink></div></template>
      <p class="memory-text">{{revision.content.text}}</p><dl class="kv"><dt>存储状态</dt><dd>{{statuses[revision.status]}}</dd><dt>服务器当前生效状态</dt><dd>{{statuses[detail.current_effective_status]}} · {{formatTime(detail.as_of)}}</dd><dt>修订者 / 时间</dt><dd>{{detail.revised_by??'未知'}} · {{formatTime(detail.revised_at)}}</dd><dt>标签</dt><dd>{{revision.content.tags.join('、')||'无'}}</dd><dt>到期时间</dt><dd>{{revision.expires_at?formatTime(revision.expires_at):'未设'}}</dd><dt>修订 ID</dt><dd class="mono">{{revision.id}}</dd><dt>维护规则</dt><dd>管理员管理；其他提案成员只能编辑自己从未生效的候选。</dd></dl>
      <p v-if="current&&memory.effective_status==='expired'" class="notice warning">存储仍是 active；服务器判断已过期，当前不生效。编辑为候选后须重新审核。</p><p v-if="current&&revision.status==='disabled'" class="notice warning">重新启用必须先编辑为候选，再经管理员审核通过。</p><p v-if="memory.effective_status==='deleted'" class="notice warning">此记忆已逻辑删除，历史保留；页面没有恢复或删除操作。</p>
      <template v-if="editing"><el-alert v-if="revision.status==='active'" title="保存会立即撤下原生效内容，新增候选修订；新候选审核通过前没有生效内容" type="warning" :closable="false" role="alert" class="section"/><MemoryEditor v-model="form" :busy="busy||!!conflict" @save="save" @cancel="cancel"/></template>
      <template v-if="conflict"><h4>服务器精确修订 {{conflict.current_revision}}</h4><p class="memory-text">{{conflict.memory.current.content.text}}</p><el-button @click="useHead">已核对服务器修订，继续保留草稿</el-button></template>
    </el-card>
    <el-card shadow="never" class="section"><template #header><h3>来源</h3></template><p v-if="revision.source.provenance_redacted">任务来源不可访问，来源标识已隐藏。</p><template v-else><p>来源：{{revision.source.origin==='system'?'已记录人工反馈形成的系统候选':'人工提案'}}</p><p v-if="revision.source.task_id"><RouterLink :to="`/org/tasks/${revision.source.task_id}/memory-feedback`">查看已授权来源任务的反馈队列</RouterLink></p><dl class="kv"><template v-if="revision.source.card_revision_id"><dt>来源卡片精确修订</dt><dd class="mono">{{revision.source.card_revision_id}}</dd></template><template v-if="revision.source.feedback_event_id"><dt>已记录反馈事件</dt><dd class="mono">{{revision.source.feedback_event_id}}</dd></template><template v-if="revision.source.proposal_job_id"><dt>候选作业</dt><dd class="mono">{{revision.source.proposal_job_id}}</dd></template></dl></template></el-card>
    <el-card v-if="current&&admin&&!editing&&(allowed('approve')||allowed('reject')||allowed('disable'))" shadow="never" class="section"><template #header><h3>人工决定 · 精确修订 {{revision.revision}}</h3></template><p class="hint">原因必填，仅保存哈希，历史无法读取原始原因。审核不确认任何证据。</p><label v-if="allowed('approve')" class="check"><input v-model="reviewed" type="checkbox" :disabled="busy||!!conflict"/>我已核对本精确修订的内容、冲突键、来源与有效期</label><label for="memory-reason">操作原因</label><el-input id="memory-reason" v-model="reason" type="textarea" maxlength="1000" :disabled="busy||!!conflict"/><div class="actions"><el-button v-if="allowed('approve')" type="success" :disabled="busy||!!conflict||!reviewed||!reason.trim()" @click="decide('approve')">审核通过修订 {{revision.revision}}</el-button><el-button v-if="allowed('reject')" type="danger" plain :disabled="busy||!!conflict||!reason.trim()" @click="decide('reject')">驳回并停用</el-button><el-button v-if="allowed('disable')" :disabled="busy||!!conflict||!reason.trim()" @click="decide('disable')">停用记忆</el-button></div></el-card>
    <el-card shadow="never" class="section"><template #header><h3>不可变修订历史</h3></template><p class="hint">内容、审核与停用均形成修订；原因仅保留 SHA-256 哈希。</p><el-table :data="history" row-key="id" aria-label="记忆修订历史"><el-table-column label="精确修订" width="110"><template #default="{row}"><RouterLink :to="`/org/memory/${id}?revision=${row.revision}`">修订 {{row.revision}}</RouterLink></template></el-table-column><el-table-column label="存储状态 / 决定" min-width="170"><template #default="{row}">{{statuses[row.status]}} · {{row.decision??'编辑候选'}}</template></el-table-column><el-table-column label="修订者 / 时间" min-width="220"><template #default="{row}">{{row.created_by}} · {{formatTime(row.created_at)}}</template></el-table-column><el-table-column label="原因哈希" min-width="260"><template #default="{row}"><code>{{row.decision_reason_sha256??'无决定原因'}}</code></template></el-table-column></el-table><div class="actions"><el-button @click="previous=[];loadHistory()">从第一页读取历史</el-button><el-button :disabled="!previous.length" @click="backHistory">上一页历史</el-button><el-button :disabled="!historyMeta?.has_more" @click="nextHistory">下一页历史</el-button></div></el-card>
  </template>
</template>
<style scoped>.memory-text{white-space:pre-wrap;overflow-wrap:anywhere}code{overflow-wrap:anywhere}label[for=memory-reason]{display:block;margin:12px 0 5px}</style>
