<script setup>
import {computed,onMounted,onUnmounted,ref} from 'vue';
import {onBeforeRouteLeave,onBeforeRouteUpdate,useRoute} from 'vue-router';
import {ApiError,orgSession} from '../api.js';
import {confirmAction,downloadOriginal,errorText,formatTime,orgRequest} from '../org.js';
import {blankQualification,checkCertificateFile,checkQualificationDetail,checkQualificationEvent,checkQualificationPage,checkQualificationRevision,profileTexts,qualificationData,qualificationKinds,qualificationMaintainer,qualificationPath,qualificationReader,qualificationTaskAuthority,reasonLabels,rememberQualificationCursor,validId} from '../qualifications.js';
import QualificationEditor from '../components/QualificationEditor.vue';
import SecretTextEditor from '../components/SecretTextEditor.vue';
import PageViewer from '../components/PageViewer.vue';
const route=useRoute(),kind=route.meta.resourceKind,id=route.params.resourceId,label=qualificationKinds[kind].label,reader=qualificationReader(),path=qualificationPath(kind);
const requestedRevision=route.query.revision===undefined?null:Number(route.query.revision),taskId=typeof route.query.task==='string'?route.query.task:null;
const detail=ref(null),error=ref(''),taskError=ref(''),loading=ref(false),busy=ref(false),editing=ref(false),uploading=ref(false),form=ref(blankQualification(kind)),initial=ref(''),fields=ref([]),receipt=ref(null),conflict=ref(null),authority=ref(null),uploads=ref([]),viewerOpen=ref(false),dateAsOf=ref(''),advisory=ref(null);
const history=ref([]),historyMeta=ref(null),historyCursor=ref(null),historyPrevious=ref([]),lifecycleHistory=ref([]),lifecycleMeta=ref(null),lifecycleCursor=ref(null),lifecyclePrevious=ref([]),tab=ref('content'),pinDialog=ref(false),lot=ref(''),reason=ref('obsolete');
let generation=0,stopped=false;
const revision=computed(()=>detail.value?.detail.revision),original=computed(()=>kind==='certificates'?detail.value?.detail.file:null),current=computed(()=>revision.value?.revision===detail.value?.current_revision),dirty=computed(()=>(editing.value||uploading.value)&&(JSON.stringify(form.value)!==initial.value||uploads.value.length>0));
const allowed=action=>qualificationMaintainer()&&detail.value?.actions.some(hint=>hint.action===action&&hint.allowed);
const canRevise=computed(()=>current.value&&allowed('revise')),canPin=computed(()=>!!authority.value?.canPin&&!!revision.value);
const baseLink=computed(()=>({path:'/org/profiles',query:taskId&&validId(taskId)?{task:taskId}:{}}));
const advisoryText=computed(()=>({unknown:'日期不足，无法判断有效期',expired:'按所填日期已过期',not_yet_valid:'按所填日期尚未生效',valid:'按所填日期处于声明有效期内'}[advisory.value?.state]));
function exactLink(number){return {path:`/org/${kind}/${id}`,query:{revision:String(number),...(taskId&&validId(taskId)?{task:taskId}:{})}};}
async function load(number=requestedRevision){if(stopped)return;const run=++generation;loading.value=true;error.value='';viewerOpen.value=false;advisory.value=null;detail.value=null;
 try{if(!validId(id)||number!==null&&(!Number.isInteger(number)||number<1))throw new ApiError(400,'invalid_input','资源 ID 或修订无效');const result=await reader.read('detail','GET',`${path}/${id}${number===null?'':`?revision=${number}`}`),checked=checkQualificationDetail(result.data,kind,id,number);if(stopped||run!==generation)return;detail.value=checked;}
 catch(exc){if(run===generation&&exc.name!=='AbortError'){error.value=errorText(exc);if([401,403,404].includes(exc.status))discard();history.value=[];lifecycleHistory.value=[];authority.value=null;receipt.value=null;}}
 finally{if(run===generation)loading.value=false;}
}
async function loadHistory(type='content',cursor=null){if(!detail.value||stopped)return;const life=type==='lifecycle',run=generation;
 try{const result=checkQualificationPage(await reader.read(type,'POST',`${path}/${id}/${life?'lifecycle/history':'history'}/query`,{cursor,limit:25}),kind,life?'lifecycle':'history',id);if(stopped||run!==generation)return;if(life){lifecycleHistory.value=result.items;lifecycleMeta.value=result.data;lifecycleCursor.value=cursor;}else{history.value=result.items;historyMeta.value=result.data;historyCursor.value=cursor;}}
 catch(exc){if(run===generation&&exc.name!=='AbortError'){error.value=errorText(exc);if([401,403,404].includes(exc.status)){discard();return;}if(life){lifecycleHistory.value=[];lifecycleMeta.value=null;}else{history.value=[];historyMeta.value=null;}if(['management_cursor_invalid','management_cursor_expired'].includes(exc.code)){if(life)lifecyclePrevious.value=[];else historyPrevious.value=[];}}}
}
function discard(){loading.value=false;stopped=true;generation++;reader.stop();detail.value=null;history.value=[];lifecycleHistory.value=[];historyMeta.value=null;lifecycleMeta.value=null;authority.value=null;form.value=blankQualification(kind);fields.value=[];editing.value=false;uploading.value=false;uploads.value=[];viewerOpen.value=false;pinDialog.value=false;lot.value='';receipt.value=null;conflict.value=null;advisory.value=null;dateAsOf.value='';}
async function refreshAuthority(){authority.value=null;taskError.value='';if(!taskId||stopped)return;
 try{const value=await qualificationTaskAuthority(reader,taskId);if(!stopped)authority.value=value;}catch(exc){if([401,403,404].includes(exc.status)){discard();error.value=errorText(exc);}if(exc.name!=='AbortError')taskError.value=errorText(exc);}}
async function loadFields(){if(kind!=='profiles')return;try{const result=await reader.read('fields','GET','/confidential-fields');if(!stopped)fields.value=result.items.map(({key,label,scope})=>({key,label,scope}));}catch(exc){if([401,403,404].includes(exc.status))discard();if(exc.name!=='AbortError')error.value=errorText(exc);}}
async function startEdit(file=false){if(!canRevise.value||busy.value)return;form.value={...blankQualification(kind),...Object.fromEntries(Object.entries(revision.value.data).map(([key,value])=>[key,value??'']))};initial.value=JSON.stringify(form.value);editing.value=!file;uploading.value=file;conflict.value=null;receipt.value=null;uploads.value=[];await loadFields();}
async function cancel(){if(dirty.value&&!await confirmAction(`放弃未保存的${label}内容及所选文件？`,'放弃未保存编辑','放弃编辑'))return;editing.value=false;uploading.value=false;form.value=blankQualification(kind);fields.value=[];uploads.value=[];conflict.value=null;}
async function freshHead(){const result=await reader.read('head','GET',`${path}/${id}`);return checkQualificationDetail(result.data,kind,id);}
async function failedWrite(exc){error.value=errorText(exc);if([401,403,404].includes(exc.status)){discard();return;}
 if(exc.status===409||!exc.status){try{const head=await freshHead();if(stopped)return;detail.value={...detail.value,current_revision:head.current_revision,lifecycle:head.lifecycle,actions:head.actions};conflict.value={revision:head.current_revision,data:head.detail.revision.data};error.value=exc.status===409?'修订已变化，草稿已保留。请对照当前服务器内容，再主动保存。':'保存结果尚未确定，草稿已保留。已读取当前服务器修订，请核对后再主动决定；不会自动重试。';historyPrevious.value=[];await loadHistory();}catch(readError){discard();error.value=errorText(readError);}}
}
async function save(){if(!editing.value||!allowed('revise')||busy.value||stopped)return;busy.value=true;error.value='';
 try{const result=await orgRequest('POST',`/resources/${kind}/${id}/revisions`,{expected_revision:detail.value.current_revision,data:qualificationData(kind,form.value)},{contractVersion:4});if(stopped)return;const saved=checkQualificationRevision(result.data,kind,id);receipt.value={type:'revision',data:saved};editing.value=false;form.value=blankQualification(kind);fields.value=[];conflict.value=null;historyPrevious.value=[];await load(saved.revision);await loadHistory();}catch(exc){await failedWrite(exc);}finally{busy.value=false;}}
function pick(file){const raw=file.raw;if(busy.value||!raw)return false;
 if(!/\.(pdf|png|jpe?g)$/i.test(raw.name)||!["application/pdf","image/png","image/jpeg"].includes(raw.type)||/[\\/\x00-\x1f\x7f]/.test(raw.name)||raw.name.length>200){error.value='只支持名称安全的 PDF、PNG、JPG 文件';return false;}
 if(uploads.value.length>=20){error.value='一个证照最多 20 个文件';return false;}
 if(!raw.size||uploads.value.reduce((sum,item)=>sum+item.raw.size,raw.size)>40*1024*1024){error.value='所选文件合计最多 40 MiB，文件不能为空';return false;}
 const item={id:crypto.randomUUID(),raw,rotation:0,url:null};uploads.value.push(item);if(raw.type.startsWith('image/')){const image=new FileReader();image.onload=()=>{const entry=uploads.value.find(value=>value.id===item.id);if(entry&&!stopped)entry.url=image.result;};image.readAsDataURL(raw);}return false;
}
function move(index,step){if(busy.value)return;const target=index+step;if(target>=0&&target<uploads.value.length)[uploads.value[index],uploads.value[target]]=[uploads.value[target],uploads.value[index]];}
async function saveOriginal(){if(!uploading.value||!uploads.value.length||!allowed('revise')||busy.value||stopped)return;busy.value=true;error.value='';
 try{const body=new FormData(),data=qualificationData(kind,form.value);body.append('metadata',JSON.stringify({expected_revision:detail.value.current_revision,data,parts:uploads.value.map(item=>({rotation:item.rotation}))}));for(const item of uploads.value)body.append('file',item.raw,item.raw.name);
 const result=await orgRequest('POST',`/resources/certificates/${id}/file-revisions`,body,{contractVersion:4});if(stopped)return;const value=result.data,saved=checkQualificationRevision({id:value.certificate_revision_id,org_id:value.org_id,certificate_id:value.certificate_id,revision:value.revision,data:value.data},kind,id);checkCertificateFile(value,saved);receipt.value={type:'file',data:value};uploads.value=[];uploading.value=false;form.value=blankQualification(kind);conflict.value=null;historyPrevious.value=[];await load(saved.revision);await loadHistory();}
 catch(exc){await failedWrite(exc);}finally{busy.value=false;}}
async function lifecycle(){if(busy.value||!detail.value||stopped)return;const state=detail.value.lifecycle.state==='active'?'inactive':'active',action=state==='inactive'?'deactivate':'restore',text=state==='inactive'?'停用':'恢复';if(!allowed(action))return;
 if(!await confirmAction(`${text}此${label}？已有任务继续保留固定修订；停用阻止新的选择和版本替换，不删除内容或确认任何证据。`,`${text}${label}`,`确认${text}`,state==='inactive'))return;busy.value=true;error.value='';
 try{const result=await orgRequest('POST',`${path}/${id}/lifecycle`,{expected_revision:detail.value.current_revision,expected_lifecycle_revision:detail.value.lifecycle.revision,state,reason_code:state==='active'?'restored':reason.value},{contractVersion:4});if(stopped)return;const value=result.data;checkQualificationEvent(value.event,kind,id);if(value.lifecycle?.state!==state||value.lifecycle.revision!==value.event.revision||value.existing_selections!=='preserved')throw new ApiError(502,'invalid_response','生命周期回执范围不符合契约');receipt.value={type:'lifecycle',data:value};await load(revision.value.revision);lifecyclePrevious.value=[];await loadHistory('lifecycle');}
 catch(exc){if([401,403,404].includes(exc.status)){discard();error.value=errorText(exc);}else if(exc.status===409||!exc.status){try{const head=await freshHead();if(stopped)return;detail.value={...detail.value,current_revision:head.current_revision,lifecycle:head.lifecycle,actions:head.actions};error.value=exc.status===409?'内容或生命周期版本已变化，请核对新状态后重新决定。':'操作结果尚未确定，已重新读取服务器状态；请核对后主动决定，不会自动重试。';}catch(readError){discard();error.value=errorText(readError);}}else error.value=errorText(exc);}finally{busy.value=false;}}
async function openPin(){await refreshAuthority();if(canPin.value){pinDialog.value=true;receipt.value=null;}}
async function pin(){if(!canPin.value||busy.value||stopped)return;busy.value=true;error.value='';
 try{await refreshAuthority();if(!canPin.value){pinDialog.value=false;return;}const number=revision.value.revision,revisionId=revision.value.id,normalizedLot=lot.value.trim()||null,result=await orgRequest('POST',`/tasks/${taskId}/${kind}`,{[qualificationKinds[kind].id]:id,revision:number,lot:normalizedLot},{contractVersion:4});if(stopped)return;const value=result.data,field=kind==='profiles'?'profile_revision_id':'certificate_revision_id';if(value.org_id!==orgSession.get()?.orgId||value.task_id!==taskId||value[field]!==revisionId||value.revision!==number||value.lot!==normalizedLot||!validId(value.id)||typeof value.duplicate!=='boolean'||!(value.replaced_snapshot_id===null||validId(value.replaced_snapshot_id)))throw new ApiError(502,'invalid_response','任务固定回执范围不符合契约');receipt.value={type:'pin',data:value};pinDialog.value=false;lot.value='';window.dispatchEvent(new CustomEvent('bid:task-materials-changed',{detail:{taskId}}));}
 catch(exc){if([401,403,404].includes(exc.status)){discard();error.value=errorText(exc);}else{if(!exc.status||exc.code==='resource_inactive')pinDialog.value=false;error.value=!exc.status?'任务选择结果尚未确定，请核对服务器固定版本后主动决定；不会自动重试。':errorText(exc);}}finally{busy.value=false;}}
async function inspectDate(){advisory.value=null;if(!dateAsOf.value||!revision.value||stopped)return;const number=revision.value.revision,asOf=dateAsOf.value;
 try{const result=await reader.read('date','GET',`${path}/${id}?revision=${number}&as_of=${encodeURIComponent(asOf)}`),checked=checkQualificationDetail(result.data,kind,id,number,asOf);if(!stopped&&dateAsOf.value===asOf&&revision.value?.revision===number)advisory.value=checked.date_advisory;}catch(exc){if([401,403,404].includes(exc.status))discard();if(exc.name!=='AbortError')error.value=errorText(exc);}}
const loadPage=async(page,zoom)=>{try{return await reader.read(`preview-${page}`,'GET',`/resources/certificates/revisions/${revision.value.id}/file/pages/${page}/preview?zoom=${zoom}`,undefined,{binary:true});}catch(exc){if([401,403,404].includes(exc.status)){discard();error.value=errorText(exc);}throw exc;}};
async function download(){if(!original.value)return;const revisionId=revision.value.id;try{await downloadOriginal(`/resources/certificates/revisions/${revisionId}/file/download-link`,original.value.file.name,(method,path,body,options)=>{if(options?.binary&&new URL(path,window.location.origin).pathname!==`/resources/certificates/revisions/${revisionId}/file/download`)throw new ApiError(502,'invalid_response','原件下载链接不属于此精确修订');return reader.read('download',method,path,body,options);});}catch(exc){if([401,403,404].includes(exc.status))discard();error.value=errorText(exc);}}
function nextHistory(type){const life=type==='lifecycle',meta=life?lifecycleMeta.value:historyMeta.value;if(!meta?.has_more)return;rememberQualificationCursor(life?lifecyclePrevious.value:historyPrevious.value,life?lifecycleCursor.value:historyCursor.value);loadHistory(type,meta.next_cursor);}
function restartHistory(type){if(type==='lifecycle')lifecyclePrevious.value=[];else historyPrevious.value=[];loadHistory(type);}
function previousHistory(type){const previous=type==='lifecycle'?lifecyclePrevious.value:historyPrevious.value;if(previous.length)loadHistory(type,previous.pop());}
async function chooseTab(type){tab.value=type;if(type==='lifecycle'&&!lifecycleMeta.value)await loadHistory(type);}
function clear(){discard();error.value='单位会话已改变，请重新打开详情';}
function beforeUnload(event){if(dirty.value){event.preventDefault();event.returnValue='';}}
const canLeave=async()=>!dirty.value||await confirmAction(`放弃未保存的${label}内容及所选文件？`,'放弃未保存编辑','放弃编辑');
onBeforeRouteLeave(canLeave);onBeforeRouteUpdate(canLeave);
onMounted(async()=>{window.addEventListener('bid:org-reset',clear);window.addEventListener('beforeunload',beforeUnload);await load();if(detail.value){await loadHistory();await loadFields();await refreshAuthority();}});
onUnmounted(()=>{discard();window.removeEventListener('bid:org-reset',clear);window.removeEventListener('beforeunload',beforeUnload);});
</script>
<template>
 <nav class="breadcrumb" aria-label="位置"><RouterLink :to="baseLink">单位资料</RouterLink><span>/</span><span>{{label}}详情</span></nav>
 <el-alert v-if="error" :title="error" type="error" show-icon :closable="false" role="alert" class="section"/>
 <p v-if="loading" role="status">正在读取精确{{label}}修订…</p>
 <template v-if="detail">
  <div class="page-header"><div><h2>{{revision.data.name}}</h2><p class="subtitle">由商务审核或单位管理员维护 · 内容修订 {{revision.revision}} · 当前修订 {{detail.current_revision}}</p></div><el-tag :type="detail.lifecycle.state==='active'?'success':'info'">{{detail.lifecycle.state==='active'?'可用':'已停用'}}</el-tag></div>
  <el-alert title="自行声明；真实性、业绩和资质未经核验" description="维护资源、检查日期或选择到任务均不确认响应证据。任务固定所选修订，不会自动升级。" type="warning" :closable="false" class="section"/>
  <el-alert v-if="receipt?.type==='revision'||receipt?.type==='file'" :title="`${receipt.type==='file'?'原件已保存':'已保存内容'} · 内容修订 ${receipt.data.revision} · 修订 ID ${receipt.data.certificate_revision_id??receipt.data.id}`" type="success" :closable="false" role="status" class="section"/>
  <p v-if="receipt?.type==='revision'||receipt?.type==='file'"><RouterLink :to="exactLink(receipt.data.revision)">查看刚保存的精确修订</RouterLink></p>
  <el-alert v-if="receipt?.type==='lifecycle'" :title="`已${receipt.data.lifecycle.state==='active'?'恢复':'停用'} · 生命周期修订 ${receipt.data.lifecycle.revision} · 已有任务固定版本保留`" type="success" :closable="false" role="status" class="section"/>
  <el-alert v-if="receipt?.type==='pin'" :title="`${receipt.data.duplicate?'已有相同固定版本':'任务已固定修订 '+receipt.data.revision} · 选择 ID ${receipt.data.id} · 修订 ID ${receipt.data.profile_revision_id??receipt.data.certificate_revision_id} · 分包 ${receipt.data.lot??'未指定'}${receipt.data.replaced_snapshot_id?' · 替换选择 '+receipt.data.replaced_snapshot_id:''}`" type="success" :closable="false" role="status" class="section"/>
  <el-card shadow="never" class="section"><template #header><div class="section-title"><h3>声明与修订</h3><el-button v-if="canRevise&&!editing&&!uploading" :disabled="busy" @click="startEdit()">修订{{label}}</el-button><RouterLink v-if="!current" :to="exactLink(detail.current_revision)">查看当前修订</RouterLink></div></template>
   <dl class="details"><dt>内容修订 ID</dt><dd class="mono">{{revision.id}}</dd><dt>修订者 / 时间</dt><dd>{{detail.revised_by??'未知'}} · {{formatTime(detail.revised_at)}}</dd><dt>生命周期修订</dt><dd>{{detail.lifecycle.revision}}（与内容修订分别记录）</dd></dl>
   <template v-if="kind==='profiles'"><el-form label-position="top"><el-form-item v-for="text in profileTexts" :key="text.key" :label="text.label"><SecretTextEditor :model-value="revision.data[text.key]??''" :fields="fields" disabled :label="`已保存${text.label}`" :rows="text.rows"/></el-form-item></el-form></template>
   <dl v-else class="details"><dt>类别</dt><dd>{{revision.data.kind==='qualification'?'单位证照':'人员证书'}}</dd><dt>证号</dt><dd>{{revision.data.number}}</dd><dt>有效期起</dt><dd>{{revision.data.valid_from??'未声明'}}</dd><dt>有效期止</dt><dd>{{revision.data.valid_until??'未声明'}}</dd></dl>
   <template v-if="editing||uploading"><el-alert v-if="conflict" :title="`当前服务器内容修订 ${conflict.revision}，草稿已保留`" type="warning" :closable="false" class="section"/><p v-if="conflict"><RouterLink :to="exactLink(conflict.revision)">打开当前服务器精确修订核对</RouterLink></p><dl v-if="conflict" class="details"><template v-for="(value,key) in conflict.data" :key="key"><dt>{{key}}</dt><dd>{{value??'未声明'}}</dd></template></dl><QualificationEditor v-if="editing" v-model="form" :kind="kind" :fields="fields" :busy="busy" @save="save" @cancel="cancel"/></template>
   <div v-if="!editing&&!uploading&&current&&(allowed('deactivate')||allowed('restore'))" class="actions"><el-select v-if="detail.lifecycle.state==='active'" v-model="reason" aria-label="停用原因" style="width:150px"><el-option v-for="code in ['obsolete','duplicate','unavailable','other']" :key="code" :value="code" :label="reasonLabels[code]"/></el-select><el-button :disabled="busy" @click="lifecycle">{{detail.lifecycle.state==='active'?'停用':'恢复'}}{{label}}</el-button></div>
  </el-card>
  <el-card v-if="kind==='certificates'" shadow="never" class="section"><template #header><div class="section-title"><h3>此修订原件</h3><el-button v-if="canRevise&&!editing&&!uploading" :disabled="busy" @click="startEdit(true)">{{original?'替换原件':'上传原件'}}</el-button></div></template>
   <template v-if="original"><p>{{original.file.name}} · {{original.file.page_count}} 页 · 原件 ID {{original.id}}</p><p class="hint mono">SHA-256：{{original.file.sha256}}</p><div class="actions"><el-button @click="viewerOpen=true">预览此修订原件</el-button><el-button @click="download">下载此修订原件</el-button></div><ol v-if="original.parts.length"><li v-for="part in original.parts" :key="part.ordinal">{{part.ordinal}}. {{part.name}} · 第 {{part.page_start}} 页起 / {{part.page_count}} 页 · 顺时针 {{part.rotation}}°</li></ol></template>
   <template v-else><p class="tag warning">此修订没有原件</p><p class="hint">元数据修订不会继承旧原件。可从内容历史打开旧修订核对，或为当前修订上传原件生成新修订。</p></template>
   <template v-if="uploading"><p>上传原件将使用本修订的完整声明创建新内容修订。最多 20 个 PDF、PNG、JPEG 文件，合计 40 MiB、合成后最多 200 页；部署可能设定更小上限。</p><el-upload multiple drag accept=".pdf,.png,.jpg,.jpeg" :auto-upload="false" :show-file-list="false" :on-change="pick" :disabled="busy"><div>拖入或点击选择原件文件</div></el-upload><ol class="uploads"><li v-for="(item,index) in uploads" :key="item.id"><span class="thumb"><img v-if="item.url" :src="item.url" :style="{transform:`rotate(${item.rotation}deg)`}" alt=""/><span v-else>PDF</span></span><span class="name">{{index+1}}. {{item.raw.name}}</span><el-button :aria-label="`旋转文件 ${index+1}`" :disabled="busy" @click="item.rotation=(item.rotation+90)%360">{{item.rotation}}°</el-button><el-button :aria-label="`上移文件 ${index+1}`" :disabled="busy||index===0" @click="move(index,-1)">上移</el-button><el-button :aria-label="`下移文件 ${index+1}`" :disabled="busy||index===uploads.length-1" @click="move(index,1)">下移</el-button><el-button :aria-label="`移除文件 ${index+1}`" :disabled="busy" @click="uploads.splice(index,1)">移除</el-button></li></ol><div class="actions"><el-button type="primary" :loading="busy" :disabled="!uploads.length" @click="saveOriginal">保存原件为新修订</el-button><el-button :disabled="busy" @click="cancel">取消编辑</el-button></div><p class="hint">照片会去掉位置等元数据。文件核验和预览不证明真伪，也不确认任何证据。</p></template>
   <div class="actions"><label for="certificate-as-of">核对日期（仅日期提示）</label><el-input id="certificate-as-of" v-model="dateAsOf" type="date" aria-label="核对日期（仅日期提示）" style="width:180px" @change="inspectDate"/></div><p v-if="advisory">{{advisoryText}} · 核对日期 {{advisory.as_of}}；仅按声明日期判断。</p><p v-else class="hint">明确填写核对日期后读取日期提示，不推断今天、任务截止时间或到期提醒。</p>
  </el-card>
  <el-card v-if="taskId" shadow="never" class="section"><template #header><h3>任务固定版本</h3></template><el-alert v-if="taskError" :title="taskError" type="error" :closable="false" role="alert"/><p class="mono">任务 ID：{{taskId}}</p><template v-if="authority"><p v-if="authority.workflow.state==='archived'">任务已归档，只能读取已有记录。</p><p v-else-if="!canPin">需要任务负责人或协作者并具备单位资源选择权限；审阅者、观察者和非成员管理员不能选择。</p><template v-else><p v-if="detail.lifecycle.state==='inactive'">停用资源只允许核对已有的相同固定版本，新的选择和替换会被服务器拒绝。</p><el-button :disabled="busy||editing||uploading" type="primary" @click="openPin">{{detail.lifecycle.state==='inactive'?'核对已有固定版本':'选择到任务'}}</el-button></template><p><RouterLink :to="`/org/tasks/${taskId}`">返回已授权任务</RouterLink></p></template></el-card>
  <el-card shadow="never" class="section"><div class="actions" role="group" aria-label="历史类型"><el-button :type="tab==='content'?'primary':'default'" @click="chooseTab('content')">内容修订历史</el-button><el-button :type="tab==='lifecycle'?'primary':'default'" @click="chooseTab('lifecycle')">生命周期记录</el-button></div>
   <template v-if="tab==='content'"><el-table :data="history" aria-label="内容修订历史"><el-table-column label="修订" width="100"><template #default="{row}"><RouterLink :to="exactLink(row.revision)">修订 {{row.revision}}</RouterLink></template></el-table-column><el-table-column prop="name" :label="`${label}名称`" min-width="160"/><el-table-column label="修订者 / 时间" min-width="210"><template #default="{row}">{{row.created_by??'未知'}} · {{formatTime(row.created_at)}}</template></el-table-column><el-table-column label="修订状态" width="160"><template #default="{row}">{{row.current?'当前':'历史'}}{{kind==='certificates'?(row.has_file?' · 有原件':' · 无原件'):''}}</template></el-table-column></el-table><div class="actions"><el-button @click="restartHistory('content')">从第一页读取内容历史</el-button><el-button :disabled="!historyPrevious.length" @click="previousHistory('content')">上一页内容历史</el-button><el-button :disabled="!historyMeta?.has_more" @click="nextHistory('content')">下一页内容历史</el-button></div></template>
   <template v-else><el-empty v-if="lifecycleMeta&&!lifecycleHistory.length" description="暂无停用或恢复记录"/><el-table v-else :data="lifecycleHistory" aria-label="生命周期记录"><el-table-column label="状态变化" min-width="140"><template #default="{row}">{{row.before==='active'?'可用':'已停用'}} → {{row.after==='active'?'可用':'已停用'}}</template></el-table-column><el-table-column label="版本" min-width="150"><template #default="{row}">生命周期 {{row.revision}} · 内容 {{row.resource_revision}}</template></el-table-column><el-table-column label="原因" min-width="110"><template #default="{row}">{{reasonLabels[row.reason_code]}}</template></el-table-column><el-table-column label="操作人 / 时间" min-width="220"><template #default="{row}">{{row.actor_user_id}} · {{formatTime(row.created_at)}}</template></el-table-column></el-table><div class="actions"><el-button @click="restartHistory('lifecycle')">从第一页读取生命周期</el-button><el-button :disabled="!lifecyclePrevious.length" @click="previousHistory('lifecycle')">上一页生命周期</el-button><el-button :disabled="!lifecycleMeta?.has_more" @click="nextHistory('lifecycle')">下一页生命周期</el-button></div></template>
  </el-card>
  <el-dialog v-model="pinDialog" :title="`固定精确${label}修订`" width="min(580px, calc(100vw - 24px))" :close-on-click-modal="false" :close-on-press-escape="!busy" :show-close="!busy"><p>将 {{revision.data.name}} · 修订 {{revision.revision}} · 修订 ID {{revision.id}} 固定到此任务。此次选择按任务、资源和分包记录；选择其它资源不会移除此资源。</p><p>替换同一资源与分包的固定版本会触发已有的重新审阅流程，不会确认材料。</p><el-input v-model="lot" aria-label="分包（可选）" maxlength="100" :disabled="busy"/><template #footer><el-button :disabled="busy" @click="pinDialog=false">取消</el-button><el-button type="primary" :loading="busy" @click="pin">确认选择修订 {{revision.revision}}</el-button></template></el-dialog>
  <PageViewer v-if="original" v-model="viewerOpen" :title="`${revision.data.name} · 修订 ${revision.revision} · ${original.file.name}`" :page-count="original.file.page_count" :load="loadPage"/>
 </template>
</template>
<style scoped>
.details{display:grid;grid-template-columns:minmax(110px,160px) minmax(0,1fr);gap:12px;margin:16px 0}.details dt{color:var(--el-text-color-secondary)}.details dd{margin:0;overflow-wrap:anywhere;white-space:pre-wrap}.actions{margin-top:12px}.uploads{list-style:none;padding:0;display:grid;gap:8px}.uploads li{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.thumb{width:44px;height:44px;border:1px solid var(--el-border-color);display:inline-flex;align-items:center;justify-content:center;overflow:hidden}.thumb img{max-width:100%;max-height:100%}.name{flex:1;min-width:120px;overflow-wrap:anywhere}h3{margin:0}@media(max-width:720px){.details{grid-template-columns:1fr;gap:4px}.details dd{margin-bottom:12px}}
</style>
