<script setup>
import { computed, onMounted, ref, watch } from "vue";
import { onBeforeRouteLeave, onBeforeRouteUpdate, useRoute, useRouter } from "vue-router";
import { categories, confirmAction, errorText, label, locationLabel, orgAccess, orgRequest } from "../org.js";
import { checkScope, checkReview, entryOrigins, requirementRequest, reviewStates } from "../requirement-review.js";
import { useTaskAuthority } from "../task-authority.js";
import { useTaskLive } from "../task-live.js";
import TaskNavigation from "../components/TaskNavigation.vue";
import RequirementReviewDetail from "../components/RequirementReviewDetail.vue";
import ManualRequirementEntry from "../components/ManualRequirementEntry.vue";
const route=useRoute(),router=useRouter(),taskId=String(route.params.taskId);
const history=ref([]),documents=ref([]),scope=ref(null),rows=ref([]),responseRows=ref([]),error=ref(""),notice=ref(""),busy=ref(false),cursor=ref(null),prior=ref([]),pageData=ref(null),selectedId=ref(""),detail=ref(null),manual=ref(null),manualOpen=ref(false),rejectedRef=ref(null),rejections=ref([]),rejectedNext=ref(null),rejectedOpen=ref(false),selected=ref([]),inspected=ref(new Map()),batchReason=ref(""),reviewedEach=ref(false),batchStale=ref(false),batchError=ref(""),batchBusy=ref(false),rejectedJob=ref("");
let generation=0;
const job=computed(()=>String(route.query.job??""));
const filters=computed(()=>({state:String(route.query.state??""),category:String(route.query.category??""),origin:String(route.query.origin??""),starred:route.query.starred==='1',rejected_job_id:String(route.query.rejected_job_id??""),rejected_index:route.query.rejected_index == null ? null : Number(route.query.rejected_index),limit:[50,100].includes(Number(route.query.limit))?Number(route.query.limit):50}));
const authority=useTaskAuthority(taskId,denied);
const writable=computed(()=>!error.value&&authority.canWrite.value&&['admin','bidder','technical'].includes(orgAccess.role));
const owner=computed(()=>writable.value&&authority.access.value?.member.role==='owner');
const currentHistory=computed(()=>history.value.find(item=>item.job_id===job.value));
const documentName=id=>documents.value.find(item=>item.id===id)?.name??id;
const responseFor=id=>responseRows.value.find(item=>item.requirement_id===id);
function denied(exc){generation++;scope.value=null;rows.value=[];responseRows.value=[];selectedId.value='';selected.value=[];inspected.value=new Map();reviewedEach.value=false;manualOpen.value=false;rejections.value=[];rejectedOpen.value=false;documents.value=[];history.value=[];error.value=`任务不可访问：${errorText(exc)}`;}
async function load(){
  if(!job.value){scope.value=null;rows.value=[];return null;}
  const run=++generation;busy.value=true;error.value='';
  const params=new URLSearchParams({limit:String(filters.value.limit)});
  for(const [key,value]of Object.entries(filters.value))if(key!=='limit'&&value!==''&&value!==null&&value!==false)params.set(key,String(value));
  if(cursor.value)params.set('cursor',cursor.value);
  try{const [result,responses]=await Promise.all([requirementRequest('GET',`/tasks/${taskId}/extractions/${job.value}/requirement-reviews?${params}`),orgRequest('GET',`/tasks/${taskId}/cards?job=${job.value}`)]);if(run!==generation)return null;checkScope(result.data.scope,taskId,job.value);if(result.items.length>filters.value.limit)throw new Error('要求分页超出契约');for(const item of result.items)checkReview(item,taskId,job.value);
    if(scope.value&&(scope.value.confirmation_sha256!==result.data.scope.confirmation_sha256||scope.value.revision!==result.data.scope.revision)){reviewedEach.value=false;batchStale.value=selected.value.length>0;inspected.value=new Map();batchError.value=selected.value.length?'集合已变化，已保留批次原因，请重新读取并逐项核对。':'';await detail.value?.load();}
    if(responses.items.length>5000 || responses.items.some(item=>!item.requirement_id || item.card && (item.card.task_id!==taskId || item.card.extraction_job_id!==job.value || item.card.requirement_id!==item.requirement_id)))throw new Error('响应状态范围不符合契约');
    responseRows.value=responses.items.map(item=>({requirement_id:item.requirement_id,card_state:item.card?.state??null}));scope.value=result.data.scope;pageData.value=result.data;rows.value=result.items;return result.data.scope.last_event_cursor;
  }catch(exc){if(run===generation){rows.value=[];pageData.value=null;error.value=errorText(exc);if([401,403,404].includes(exc.status)){denied(exc);}else if(exc.status===409){cursor.value=null;prior.value=[];error.value+='；分页已失效，请重新读取首页。';}}throw exc;}
  finally{if(run===generation)busy.value=false;}
}
const live=useTaskLive(taskId,load,denied);
async function discard(){return (!detail.value||await detail.value.discard())&&(!manual.value||await manual.value.discard())&&(!batchReason.value||await confirmAction('尚有未提交的批次原因，确定离开？'));}
onBeforeRouteLeave(discard);
onBeforeRouteUpdate(async(to)=>{if(to.query.job!==route.query.job&&!(await discard()))return false;});
async function update(key,value){if(!(await discard()))return;cursor.value=null;prior.value=[];selected.value=[];inspected.value=new Map();reviewedEach.value=false;batchStale.value=false;const query={...route.query};if(value!==''&&value!==false&&value!==null)query[key]=value===true?'1':String(value);else delete query[key];delete query.requirement;await router.replace({query});}
async function open(row){if(detail.value&&!(await detail.value.discard()))return;selectedId.value=row.requirement_id;await router.replace({query:{...route.query,requirement:row.requirement_id}});}
function inspectedRow(row){if(!row.citation_valid || row.state==='confirmed')return;inspected.value.set(row.requirement_id,{requirement_id:row.requirement_id,expected_revision:row.revision,expected_review_hash:row.review_hash});}
function toggle(row,checked){reviewedEach.value=false;if(checked){if(selected.value.length>=100){notice.value='单批最多 100 项。';return;}if(!inspected.value.has(row.requirement_id)){notice.value='请先打开并核对该要求完整原文。';return;}selected.value.push({...inspected.value.get(row.requirement_id),content:row.content});}else selected.value=selected.value.filter(item=>item.requirement_id!==row.requirement_id);}
async function confirmBatch(){if(!owner.value||batchBusy.value||batchStale.value||!reviewedEach.value||!batchReason.value.trim()||!selected.value.length||selected.value.length>100)return;batchBusy.value=true;batchError.value='';try{const result=await requirementRequest('POST',`/tasks/${taskId}/extractions/${job.value}/requirement-confirmations`,{request_id:crypto.randomUUID(),expected_set_revision:scope.value.revision,items:selected.value.map(({content,...item})=>item),reviewed_each:true,reason:batchReason.value});checkScope(result.data.scope,taskId,job.value);selected.value=[];reviewedEach.value=false;batchReason.value='';await live.refresh();await detail.value?.load();notice.value=`已确认 ${result.data.changed} 项要求；响应与证据仍需分别审阅。`;}catch(exc){reviewedEach.value=false;batchStale.value=true;batchError.value=`${errorText(exc)}；选择与原因已保留，未自动重试。请重新核对各项后重新选入批次。`;if([401,403,404].includes(exc.status))denied(exc);}finally{batchBusy.value=false;}}
async function refreshBatch(){await live.refresh();selected.value=[];inspected.value=new Map();reviewedEach.value=false;batchStale.value=false;batchError.value='已读取当前集合，原因已保留，请逐项重新打开原文并选择。';await detail.value?.load();}
async function next(){if(!pageData.value?.next_cursor)return;prior.value.push(cursor.value);cursor.value=pageData.value.next_cursor;await live.refresh();}
async function previous(){cursor.value=prior.value.pop()??null;await live.refresh();}
async function linkedRequirement(id){try{const result=await requirementRequest('GET',`/requirements/${id}/review`);checkScope(result.data.scope,taskId);checkReview(result.data.requirement,taskId,result.data.scope.extraction_job_id);if(await discard())await router.push({path:`/org/tasks/${taskId}/requirements`,query:{job:result.data.scope.extraction_job_id,requirement:id}});}catch(exc){error.value=errorText(exc);}}
async function filterRejected(item){if(!job.value||!await discard())return;cursor.value=null;prior.value=[];await router.replace({query:{...route.query,rejected_job_id:item.job_id,rejected_index:String(item.index)}});}
async function loadRejected(append=false){error.value='';if(!rejectedJob.value)return;try{const params=new URLSearchParams({limit:'50'});if(append&&rejectedNext.value)params.set('cursor',rejectedNext.value);const result=await requirementRequest('GET',`/tasks/${taskId}/extractions/${rejectedJob.value}/rejected-items?${params}`);if(result.data.task_id!==taskId||result.data.extraction_job_id!==rejectedJob.value||result.items.length>50)throw new Error('拒绝回执范围不符合契约');rejections.value=append?[...rejections.value,...result.items]:result.items;rejectedNext.value=result.data.next_cursor;rejectedOpen.value=true;}catch(exc){rejections.value=[];error.value=errorText(exc);if([401,403,404].includes(exc.status))denied(exc);}}
async function startManual(item=null){if(manual.value&&!(await manual.value.discard()))return;rejectedRef.value=item;manualOpen.value=true;}
async function created(data){notice.value='已保存待确认要求；已确认不代表无遗漏。';manualOpen.value=false;rejectedRef.value=null;history.value=(await orgRequest('GET',`/tasks/${taskId}/extractions`)).items;selected.value=[];inspected.value=new Map();cursor.value=null;prior.value=[];await router.replace({query:{job:data.scope.extraction_job_id,requirement:data.requirement.requirement_id}});await live.refresh();}
async function changed(){await live.refresh();}
watch(()=>route.query,async(to,from)=>{if(to.job!==from.job){selected.value=[];inspected.value=new Map();scope.value=null;manualOpen.value=false;selectedId.value='';}selectedId.value=String(to.requirement??'');if(to.job&&['job','state','category','origin','starred','limit','rejected_job_id','rejected_index'].some(key=>to[key]!==from[key]))await live.start();},{deep:true});
onMounted(async()=>{try{const [jobs,docs]=await Promise.all([orgRequest('GET',`/tasks/${taskId}/extractions`),orgRequest('GET',`/tasks/${taskId}/documents`)]);history.value=jobs.items;documents.value=docs.items;selectedId.value=String(route.query.requirement??'');if(job.value)await live.start();}catch(exc){denied(exc);}});
</script>
<template>
  <TaskNavigation :task-id="taskId" />
  <div class="page-header"><div><h2>要求确认与补录</h2><p class="subtitle">先核对招标要求，再分别审阅响应与证据。已确认不代表无遗漏。</p></div><span role="status" aria-live="polite">{{live.status.value}}</span></div>
  <el-alert v-if="error" :title="error" type="error" :closable="false" role="alert" class="section" /><p v-if="notice" role="status">{{notice}}</p>
  <el-alert v-if="authority.access.value?.workflow.state==='archived'" title="任务已归档，要求审阅与补录均为只读。请从成员与归档恢复任务。" type="info" :closable="false" class="section" />
  <el-card class="section" shadow="never"><el-form label-position="top"><el-form-item label="明确选择要求集合"><el-select :model-value="job" aria-label="要求集合" @update:model-value="update('job',$event)"><el-option v-for="item in history.filter(item=>item.status==='succeeded')" :key="item.job_id" :value="item.job_id" :label="`${item.origin==='manual'?'人工补录集':'模型抽取集'} · ${documentName(item.document_id)} · ${item.job_id}`" /></el-select></el-form-item></el-form><p v-if="!job" class="hint">明确选择成功的集合后读取要求；人工补录集不会自动替代模型抽取集。</p><template v-if="scope"><p>{{scope.origin==='manual'?'人工补录集':'模型抽取集'}} · {{documentName(scope.document_id)}} · 集合修订 {{scope.revision}}</p><p class="hint">模型 {{currentHistory?.model??'无模型'}} · 推理档位 {{currentHistory?.reasoning??'无'}} · 原抽取回执保存 {{currentHistory?.saved??'未知'}} / 拒绝 {{currentHistory?.rejected??'未知'}}</p><p>当前保存 {{scope.summary.total}} · 要求已确认 {{scope.summary.confirmed}} · 待确认 {{scope.summary.unconfirmed}} · 历史待确认 {{scope.summary.legacy_unconfirmed}} · 已失效 {{scope.summary.invalidated}} · 人工补录 {{scope.summary.manual_added}} · 引用无效 {{scope.summary.invalid_citations}}</p></template><div class="actions"><el-button :disabled="busy || !job" @click="cursor=null;prior=[];live.refresh()">重新读取首页</el-button><el-button :disabled="!writable" @click="startManual()">补录遗漏要求</el-button><RouterLink :to="`/org/tasks/${taskId}/members`">负责人和归档恢复</RouterLink></div></el-card>
  <el-card class="section" shadow="never"><template #header><h3>拒绝回执</h3></template><el-select v-model="rejectedJob" aria-label="拒绝回执作业" placeholder="选择原抽取作业（可含失败作业）"><el-option v-for="item in history.filter(item=>item.origin!=='manual')" :key="item.job_id" :value="item.job_id" :label="`${documentName(item.document_id)} · ${item.status} · ${item.job_id}`" /></el-select><el-button :disabled="!rejectedJob" @click="loadRejected()">读取拒绝摘要</el-button><template v-if="rejectedOpen"><p class="hint">摘要经过截断，不是完整候选要求，也不计入保存要求的分母。</p><ul><li v-for="item in rejections" :key="`${item.job_id}:${item.index}`"><p>{{item.position}} · {{item.reason}}</p><blockquote class="quote">{{item.quote}}</blockquote><p>已补录 {{item.entered_requirement_count}} 项</p><div class="actions"><el-button :disabled="!writable" @click="startManual(item)">从原文补录</el-button><el-button v-for="id in item.entered_requirement_ids" :key="id" link @click="linkedRequirement(id)">查看已补录要求 {{id}}</el-button><el-button v-if="job" link @click="filterRejected(item)">筛选当前集合的关联要求</el-button></div></li></ul><p v-if="!rejections.length" class="hint">没有报告拒绝摘要；这不证明没有遗漏。</p><el-button v-if="rejectedNext" @click="loadRejected(true)">继续读取拒绝摘要</el-button></template></el-card>
  <ManualRequirementEntry v-if="manualOpen" ref="manual" :task-id="taskId" :scope="scope" :documents="documents" :rejected="rejectedRef" :writable="writable" @created="created" @denied="denied" />
  <template v-if="scope"><el-card class="section" shadow="never"><el-form class="filters" label-position="top"><el-form-item label="要求状态"><el-select :model-value="filters.state" clearable @update:model-value="update('state',$event)"><el-option v-for="(text,key) in reviewStates" :key="key" :value="key" :label="text" /></el-select></el-form-item><el-form-item label="类别"><el-select :model-value="filters.category" clearable @update:model-value="update('category',$event)"><el-option v-for="(text,key) in categories" :key="key" :value="key" :label="text" /></el-select></el-form-item><el-form-item label="来源"><el-select :model-value="filters.origin" clearable @update:model-value="update('origin',$event)"><el-option v-for="(text,key) in entryOrigins" :key="key" :value="key" :label="text" /></el-select></el-form-item><el-form-item label="每页条数"><el-select :model-value="filters.limit" @update:model-value="update('limit',$event)"><el-option v-for="size in [50,100]" :key="size" :value="size" :label="String(size)" /></el-select></el-form-item></el-form><el-checkbox :model-value="filters.starred" @update:model-value="update('starred',$event)">★ 条款</el-checkbox><p v-if="filters.rejected_job_id" class="hint">按拒绝回执关联筛选：{{filters.rejected_job_id}} / {{filters.rejected_index}}</p></el-card>
  <div class="review-layout"><section><el-card class="section" shadow="never"><p role="status">匹配 {{pageData?.total}} 项，本页 {{rows.length}} 项</p><ul class="requirements"><li v-for="row in rows" :key="row.requirement_id" data-testid="requirement-review-row"><h3>{{row.content.starred?'★ ':''}}{{row.content.text}}</h3><p>要求：{{label(reviewStates,row.state)}} · {{label(entryOrigins,row.origin)}} · {{label(categories,row.content.category)}}</p><p>响应：{{label({draft:'草稿',pending_review:'待审阅',confirmed:'响应已确认',rejected:'已驳回',needs_material:'需补材料'},responseFor(row.requirement_id)?.card_state,'尚无响应卡')}}</p><blockquote class="quote">{{row.content.source.quote}}</blockquote><p class="hint">{{locationLabel(row.content.source)}}</p><p v-if="row.next_actor">下一位：{{row.next_actor.user_id??'单位管理员恢复负责人'}} · {{row.next_actor.action}}</p><div class="actions"><el-button :aria-label="`核对要求：${row.content.text}`" @click="open(row)">核对原文与历史</el-button><input v-if="owner && row.state!=='confirmed' && row.citation_valid" type="checkbox" :checked="selected.some(item=>item.requirement_id===row.requirement_id)" :disabled="!inspected.has(row.requirement_id) || batchStale" :aria-label="`加入确认批次：${row.content.text}`" @change="toggle(row,$event.target.checked)" /><RouterLink :to="`/org/tasks/${taskId}/review?job=${job}&requirement=${row.requirement_id}`">响应与证据</RouterLink></div></li></ul><p v-if="!rows.length" class="hint">当前筛选没有要求。</p><div class="actions"><el-button :disabled="!prior.length || busy" @click="previous">上一页</el-button><el-button :disabled="!pageData?.next_cursor || busy" @click="next">下一页</el-button></div></el-card>
  <el-card v-if="owner" class="section" shadow="never"><template #header><h3>负责人批量确认要求</h3></template><p>固定选择 {{selected.length}} / 100 项；先逐项打开原文，无默认全选。</p><ul><li v-for="item in selected" :key="item.requirement_id"><el-button link @click="open({requirement_id:item.requirement_id})">{{item.content.text}}</el-button> · 修订 {{item.expected_revision}}</li></ul><el-form label-position="top"><el-form-item label="批次确认原因" required><el-input v-model="batchReason" type="textarea" maxlength="10000" /></el-form-item><el-checkbox v-model="reviewedEach" :disabled="batchStale || !selected.length">已逐项核对全部明确选择的要求与来源</el-checkbox></el-form><el-alert v-if="batchError" :title="batchError" type="error" :closable="false" role="alert" /><div class="actions"><el-button :disabled="!selected.length || !reviewedEach || !batchReason.trim() || batchStale || batchBusy" @click="confirmBatch">确认明确选择的要求</el-button><el-button v-if="batchStale" @click="refreshBatch">重新读取批次并核对</el-button></div></el-card></section>
  <RequirementReviewDetail v-if="selectedId" :key="`${job}:${selectedId}`" ref="detail" :task-id="taskId" :job-id="job" :requirement-id="selectedId" :writable="writable" :response="responseFor(selectedId)" @changed="changed" @denied="denied" @inspected="inspectedRow" /></div></template>
</template>
<style scoped>.filters{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.review-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(350px,1fr);gap:16px;align-items:start}.requirements{padding:0;list-style:none}.requirements li{padding:12px 0;border-bottom:1px solid var(--border)}.requirements h3{margin:0}.el-select{max-width:100%}@media(max-width:900px){.review-layout{grid-template-columns:minmax(0,1fr)}.filters{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
