<script setup>
import { computed, onMounted, reactive, ref, watch } from "vue";
import { onBeforeRouteLeave, useRoute } from "vue-router";
import { orgSession } from "../api.js";
import { confirmAction, domains, errorText, label, orgAccess, orgRequest, roles } from "../org.js";
import { taskRoles } from "../task-labels.js";
import { useTaskLive } from "../task-live.js";
import TaskNavigation from "../components/TaskNavigation.vue";
import TaskReviewRule from "../components/TaskReviewRule.vue";
const ruleDirty = ref(false);
const taskId=String(useRoute().params.taskId),workflow=ref(null),members=ref([]),candidates=ref([]),error=ref(""),dialog=ref(""),formError=ref(""),stale=ref(false),busy=ref(false),cursor=ref(null),prior=ref([]),nextCursor=ref(null),candidateCursor=ref(null),candidateNext=ref(null),candidatePrior=ref([]),generation=ref(0),candidateGeneration=ref(0),expected=ref(null);
const form=reactive({user:"",role:"observer",review_domains:[],previous_owner_role:"observer",previous_owner_review_domains:[],reason:""});
const manage=computed(()=>orgAccess.role==='admin'||workflow.value?.owner_user_id===orgAccess.userId);
const archived=computed(()=>workflow.value?.state==='archived');
const eligibleOwners=computed(()=>candidates.value.filter(item=>['admin','bidder'].includes(item.org_role)&&item.user_id!==workflow.value?.owner_user_id));
const domainCeiling=computed(()=>{const candidate=candidates.value.find(item=>item.user_id===form.user);return candidate?.org_role==='bidder'?['commercial']:candidate?.org_role==='technical'?['technical']:members.value.find(item=>item.user_id===form.user)?.review_domains??[];});
const formerCeiling=computed(()=>members.value.find(item=>item.user_id===workflow.value?.owner_user_id)?.review_domains??[]);
function clear(exc){generation.value++;candidateGeneration.value++;workflow.value=null;members.value=[];candidates.value=[];dialog.value="";form.reason="";error.value=`任务不可访问：${errorText(exc)}`;}
async function candidatePage(){const run=++candidateGeneration.value;const params=new URLSearchParams({limit:"50"});if(candidateCursor.value)params.set("cursor",candidateCursor.value);const result=await orgRequest("GET",`/tasks/${taskId}/member-candidates?${params}`);if(run!==candidateGeneration.value)return;candidates.value=result.items;candidateNext.value=result.data.next_cursor;}
async function load(){const run=++generation.value;const params=new URLSearchParams({limit:"50"});if(cursor.value)params.set("cursor",cursor.value);try{const [detail,list]=await Promise.all([orgRequest("GET",`/tasks/${taskId}/workflow`),orgRequest("GET",`/tasks/${taskId}/members?${params}`)]);if(run!==generation.value)return null;if(detail.data.workflow.task_id!==taskId||detail.data.workflow.org_id!==orgSession.get()?.orgId||list.items.length>50)throw new Error("成员范围不符合契约");workflow.value=detail.data.workflow;members.value=list.items;nextCursor.value=list.data.next_cursor;error.value="";if(manage.value&&!archived.value)await candidatePage();return workflow.value.last_event_cursor;}catch(exc){if(run===generation.value){members.value=[];error.value=errorText(exc);}throw exc;}}
const live=useTaskLive(taskId,load,clear);
function open(mode,member=null){dialog.value=mode;expected.value=workflow.value.revision;stale.value=false;formError.value="";Object.assign(form,{user:member?.user_id??"",role:member?.role==='owner'?'observer':member?.role??'observer',review_domains:member?.review_domains??[],previous_owner_role:'observer',previous_owner_review_domains:[],reason:""});}
async function close(){if(form.reason&&!(await confirmAction("关闭会丢弃未保存的修改，继续？","放弃未保存的修改","放弃修改",true)))return;dialog.value="";form.reason="";}
onBeforeRouteLeave(async()=>(!ruleDirty.value && (!dialog.value||!form.reason))||await confirmAction("离开会丢弃未保存的修改，继续？","放弃未保存的修改","放弃修改",true));
async function submit(){if(stale.value||!form.reason.trim())return;busy.value=true;formError.value="";try{let method='POST',path=`/tasks/${taskId}/${dialog.value}`,body={expected_revision:expected.value,reason:form.reason};if(dialog.value==='member'){method='PUT';path=`/tasks/${taskId}/members/${form.user}`;body={...body,role:form.role,review_domains:form.role==='observer'?[]:form.review_domains};}else if(dialog.value==='remove')path=`/tasks/${taskId}/members/${form.user}/remove`;else if(dialog.value==='handover')body={...body,target_user_id:form.user,previous_owner_role:form.previous_owner_role,previous_owner_review_domains:form.previous_owner_role==='observer'?[]:form.previous_owner_review_domains};await orgRequest(method,path,body);dialog.value="";form.reason="";await live.refresh();}catch(exc){formError.value=errorText(exc);if(exc.status===409){stale.value=true;formError.value+="；修改未重试。关闭后重新读取当前成员与修订，再明确提交。";await live.refresh();}else if([401,403,404].includes(exc.status))clear(exc);}finally{busy.value=false;}}
async function next(){prior.value.push(cursor.value);cursor.value=nextCursor.value;await live.refresh();}
async function previous(){cursor.value=prior.value.pop()??null;await live.refresh();}
async function nextCandidates(){candidatePrior.value.push(candidateCursor.value);candidateCursor.value=candidateNext.value;form.user="";await candidatePage();}
async function previousCandidates(){candidateCursor.value=candidatePrior.value.pop()??null;form.user="";await candidatePage();}
watch(()=>workflow.value?.revision,(revision)=>{if(dialog.value&&expected.value!==revision){stale.value=true;formError.value="工作流已更新，请关闭并重新核对成员与修订。";}});
const title=computed(()=>({member:'设置任务成员',remove:'移除任务成员',handover:'交接负责人',archive:'归档任务',unarchive:'恢复任务'}[dialog.value]??''));
const submitLabel=computed(()=>({member:'保存成员',remove:'确认移除',handover:'确认交接',archive:'确认归档',unarchive:'确认恢复'}[dialog.value]??'保存'));
onMounted(live.start);
</script>
<template><div class="page-header"><div><h2>成员与归档</h2><p class="subtitle">任务角色限定参与范围；审阅职责仍受单位角色约束。</p></div><div><span role="status" aria-live="polite">{{live.status.value}}</span><el-button @click="cursor=null;prior=[];live.refresh()">重新读取首页</el-button></div></div><TaskNavigation :task-id="taskId" /><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="section" />
<template v-if="workflow"><el-card shadow="never" class="section"><p>负责人：<span class="mono">{{workflow.owner_user_id}}</span> · <el-tag>{{archived?'已归档':'进行中'}}</el-tag> · 工作流修订 {{workflow.revision}}</p><p v-if="archived" class="hint">已归档任务只读；恢复后才能修改成员或提交新工作。</p><div v-if="manage" class="actions"><el-button :disabled="archived" type="primary" @click="open('member')">添加成员</el-button><el-button :disabled="archived" @click="open('handover')">交接负责人</el-button><el-button v-if="!archived" type="danger" @click="open('archive')">归档任务</el-button><el-button v-else @click="open('unarchive')">恢复任务</el-button></div><p v-else class="hint">只有当前负责人或单位管理员能管理成员和归档。</p></el-card>
<TaskReviewRule :task-id="taskId" :workflow="workflow" :manage="manage" @dirty="ruleDirty=$event" @updated="live.refresh()" @denied="clear" />
<el-card shadow="never" class="section"><div class="table-scroll"><table class="data-table"><caption>当前授权可见的任务成员</caption><thead><tr><th>成员</th><th>任务角色</th><th>审阅职责</th><th>状态</th><th v-if="manage">操作</th></tr></thead><tbody><tr v-for="member in members" :key="member.user_id"><td>{{member.display_label??member.user_id}}</td><td>{{label(taskRoles,member.role)}}</td><td>{{member.review_domains.map(domain=>label(domains,domain)).join('、')||'无'}}</td><td>{{member.active?'有效':'不可用'}}</td><td v-if="manage"><el-button v-if="member.role!=='owner'" :disabled="archived" size="small" @click="open('member',member)">修改成员</el-button><el-button v-if="member.role!=='owner'&&member.active" :disabled="archived" size="small" type="danger" @click="open('remove',member)">移除成员</el-button><span v-if="member.role==='owner'" class="hint">负责人需交接后才能移除</span></td></tr><tr v-if="!members.length"><td :colspan="manage?5:4" class="empty">没有可见的成员。</td></tr></tbody></table></div><div class="actions"><el-button :disabled="!prior.length" @click="previous">上一页</el-button><el-button :disabled="!nextCursor" @click="next">下一页</el-button></div></el-card></template>
<el-dialog :model-value="Boolean(dialog)" :title="title" width="560px" :close-on-click-modal="false" :show-close="false" @close="close"><el-form label-position="top" @submit.prevent="submit"><p class="hint">以工作流修订 {{expected}} 提交；并发修改会停止本次提交。</p>
<template v-if="dialog==='member'||dialog==='handover'"><el-form-item label="有效的本单位成员" required><el-select v-model="form.user" @update:model-value="form.review_domains=[]"><el-option v-if="dialog==='member'&&form.user&&!candidates.some(item=>item.user_id===form.user)" :label="members.find(item=>item.user_id===form.user)?.display_label??form.user" :value="form.user" /><el-option v-for="candidate in (dialog==='handover'?eligibleOwners:candidates)" :key="candidate.user_id" :label="`${candidate.display_label} · ${label(roles,candidate.org_role)}`" :value="candidate.user_id" /></el-select></el-form-item><div class="actions"><el-button size="small" :disabled="!candidatePrior.length" @click="previousCandidates">上一页候选成员</el-button><el-button size="small" :disabled="!candidateNext" @click="nextCandidates">下一页候选成员</el-button></div><p v-if="dialog==='handover'&&!eligibleOwners.length" class="hint">本页没有可接任的单位管理员或商务成员，请翻页；不会自动指定接任者。</p></template>
<template v-if="dialog==='member'"><el-form-item label="任务角色" required><el-select v-model="form.role" @update:model-value="form.review_domains=[]"><el-option v-for="role in ['contributor','reviewer','observer']" :key="role" :label="taskRoles[role]" :value="role" /></el-select></el-form-item><el-form-item label="审阅职责"><el-checkbox-group v-model="form.review_domains"><el-checkbox v-for="domain in ['commercial','technical']" :key="domain" :value="domain" :disabled="form.role==='observer'||!domainCeiling.includes(domain)">{{domains[domain]}}</el-checkbox></el-checkbox-group></el-form-item><p class="hint">审阅者至少选择一个职责；观察者没有审阅职责。负责人无法通过此表单移除或降级。</p></template>
<template v-if="dialog==='handover'"><p>接任者成为唯一负责人；其审阅职责由当前单位角色确定。原负责人保留下列角色。</p><el-form-item label="原负责人保留角色"><el-select v-model="form.previous_owner_role" @update:model-value="form.previous_owner_review_domains=[]"><el-option v-for="role in ['contributor','reviewer','observer']" :key="role" :label="taskRoles[role]" :value="role" /></el-select></el-form-item><el-checkbox-group v-model="form.previous_owner_review_domains"><el-checkbox v-for="domain in ['commercial','technical']" :key="domain" :value="domain" :disabled="form.previous_owner_role==='observer'||!formerCeiling.includes(domain)">{{domains[domain]}}</el-checkbox></el-checkbox-group></template>
<p v-if="dialog==='archive'">归档后保留可授权读取的历史记录，停止上传、成员修改和新作业。存在排队、运行中作业或未确定的调用费用时，后端拒绝归档。</p><p v-if="dialog==='unarchive'">恢复允许重新开展工作，但不会恢复已撤销权限或过期材料。</p><p v-if="dialog==='remove'">移除后该成员立即失去任务访问；不自动交接已有工作。</p>
<el-form-item label="原因" required><el-input v-model="form.reason" data-testid="workflow-reason" type="textarea" maxlength="500" :autosize="{minRows:2,maxRows:5}" /></el-form-item><el-alert v-if="formError" :title="formError" type="error" :closable="false" class="section" /><div class="actions"><el-button :disabled="busy" @click="close">取消</el-button><el-button native-type="submit" type="primary" :loading="busy" :disabled="!manage||(archived&&dialog!=='unarchive')||stale||!form.reason.trim()||(['member','handover'].includes(dialog)&&!form.user)||(dialog==='member'&&form.role==='reviewer'&&!form.review_domains.length)||(dialog==='handover'&&form.previous_owner_role==='reviewer'&&!form.previous_owner_review_domains.length)">{{submitLabel}}</el-button></div></el-form></el-dialog>
</template>
