<script setup>
import {computed,onMounted,onUnmounted,ref} from 'vue';
import {useRoute} from 'vue-router';
import {orgAccess,orgRequest,errorText,formatTime} from '../org.js';
import {useTaskAuthority} from '../task-authority.js';
import {attachmentRequest,checkedPage,scoped,signedBlob,fields,blockers,nextActions} from '../attachments.js';
import TaskNavigation from '../components/TaskNavigation.vue';
const route=useRoute(),taskId=String(route.params.taskId),selections=ref([]),selectionMeta=ref(null),sources=ref([]),sourceMeta=ref(null),profiles=ref([]),profileMeta=ref(null),extractionMeta=ref(null),profileSelection=ref(''),links=ref([]),linkMeta=ref(null),linkId=ref(''),expected=ref(''),page=ref(1),error=ref(''),busy=ref(false),source=ref(null),image=ref(''),reviewed=ref(false),privacy=ref(null),extraction=ref(''),extractions=ref([]),history=ref(false),receipt=ref('');let alive=true,epoch=0,requestId=crypto.randomUUID();
function dispose(){if(image.value)URL.revokeObjectURL(image.value);image.value='';reviewed.value=false;}
function clear(exc){epoch++;dispose();selections.value=[];sources.value=[];profiles.value=[];links.value=[];source.value=null;privacy.value=null;if(exc)error.value=errorText(exc);}
const authority=useTaskAuthority(taskId,clear),originalReader=computed(()=>['admin','bidder'].includes(orgAccess.role)),canWrite=computed(()=>originalReader.value&&authority.canWrite.value),canPrivacy=computed(()=>canWrite.value&&(source.value?.reviewer_user_id??source.value?.readiness.responsible_user_id)===orgAccess.userId);
async function run(work){if(busy.value)return;busy.value=true;error.value='';try{await work();}catch(exc){if([401,403,404].includes(exc.status))clear();error.value=errorText(exc);}finally{busy.value=false;}}
async function selectionPage(cursor=null){const pageEpoch=epoch;const query=new URLSearchParams({limit:'25',history:String(history.value)});if(cursor)query.set('cursor',cursor);const result=checkedPage(await attachmentRequest('GET',`/tasks/${taskId}/attachments?${query}`),taskId);if(alive&&pageEpoch===epoch){selections.value=result.items;selectionMeta.value=result.data;}}
async function sourcePage(cursor=null){const pageEpoch=epoch;const query=new URLSearchParams({limit:'25',history:String(history.value)});if(cursor)query.set('cursor',cursor);const result=checkedPage(await attachmentRequest('GET',`/tasks/${taskId}/attachment-sources?${query}`),taskId);if(alive&&pageEpoch===epoch){sources.value=result.items;sourceMeta.value=result.data;}}
async function profilePage(cursor=null){const pageEpoch=epoch;const query=new URLSearchParams({limit:'25',history:'false'});if(cursor)query.set('cursor',cursor);const result=checkedPage(await attachmentRequest('GET',`/tasks/${taskId}/profiles?${query}`),taskId);if(alive&&pageEpoch===epoch){profiles.value=result.items;profileMeta.value=result.data;}}
async function extractionPage(cursor=null){const pageEpoch=epoch;const query=new URLSearchParams({limit:'25'});if(cursor)query.set('cursor',cursor);const result=await attachmentRequest('GET',`/tasks/${taskId}/progress?${query}`);if(result.items.length>25)throw new Error('作业分页超过上限');if(alive&&pageEpoch===epoch){extractions.value=result.items.filter(job=>job.kind==='extract'&&job.status==='succeeded').map(job=>({job_id:job.id}));extractionMeta.value=result.data;}}
async function load(){await selectionPage();await sourcePage();if(originalReader.value){await profilePage();await extractionPage();}}
async function loadLinks(cursor=null){const pageEpoch=epoch;const selected=profiles.value.find(row=>row.id===profileSelection.value);links.value=[];linkId.value='';if(!selected)return;const result=checkedPage(await attachmentRequest('GET',`/resources/profiles/revisions/${selected.profile_revision_id}/attachments?limit=25${cursor?'&cursor='+encodeURIComponent(cursor):''}`));if(alive&&pageEpoch===epoch&&profileSelection.value===selected.id){links.value=result.items;linkMeta.value=result.data;}}
async function select(){await run(async()=>{await authority.refresh();if(!canWrite.value)throw new Error('当前任务身份不允许选择附件');const result=await attachmentRequest('POST',`/tasks/${taskId}/attachments`,{request_id:requestId,task_org_profile_id:profileSelection.value,profile_attachment_link_id:linkId.value,expected_selection_id:expected.value||null});scoped(result.data,taskId);requestId=crypto.randomUUID();receipt.value=`任务已固定文件修订 ${result.data.attachment_revision_id} · 选择 ${result.data.id}`;await selectionPage();});}
async function deactivate(row){await run(async()=>{await authority.refresh();if(!canWrite.value)return;await attachmentRequest('POST',`/task-attachments/${row.id}/deactivate`,{request_id:requestId,expected_state_version:row.state_version,reason:'selection_replaced'});requestId=crypto.randomUUID();await selectionPage();await sourcePage();});}
async function archive(row){await run(async()=>{await authority.refresh();if(!canWrite.value)return;const result=await attachmentRequest('POST',`/tasks/${taskId}/attachment-sources`,{request_id:requestId,task_attachment_id:row.id,page:page.value});scoped(result.data.source,taskId);requestId=crypto.randomUUID();receipt.value=`已归档第 ${result.data.source.page} 页；固定 150 dpi，尚未隐私放行`;await sourcePage();});}
async function inspect(row){await run(async()=>{dispose();source.value=scoped((await attachmentRequest('GET',`/attachment-sources/${row.id}`)).data,taskId);privacy.value=null;const blob=await signedBlob(`/attachment-sources/${row.id}/preview/download-link${history.value?'?history=true':''}`,`/attachment-sources/${row.id}/preview/download`,source.value.source_png_sha256);if(alive&&source.value?.id===row.id)image.value=URL.createObjectURL(blob);});}
async function privacyReview(mode){await run(async()=>{await authority.refresh();if(!canPrivacy.value||!reviewed.value||!image.value)return;const value=source.value,body={mode,request_id:requestId,reviewed_source_png_sha256:value.source_png_sha256,expected_hold_id:value.latest_privacy_hold_id??null};if(mode==='clear'){body.clearance='safe_for_task_team';body.extraction_job_id=extraction.value;}else body.reason='sensitive_content';const result=await attachmentRequest('POST',`/attachment-sources/${value.id}/privacy`,body);if(!alive)return;requestId=crypto.randomUUID();privacy.value=result.data;source.value=scoped((await attachmentRequest('GET',`/attachment-sources/${value.id}`)).data,taskId);reviewed.value=false;await sourcePage();receipt.value=mode==='clear'?'此精确页已隐私放行，仍未确认证据':'此页需要遮挡；attachment_redaction_not_enabled';});}
async function teamView(row){await run(async()=>{const data=scoped((await attachmentRequest('GET',`/attachment-sources/${row.id}`)).data,taskId);if(!data.cleared_rendition_id||!data.cleared_asset_id)throw new Error('此精确页没有当前有效的隐私放行图');await openRendition({rendition:{id:data.cleared_rendition_id,asset_id:data.cleared_asset_id}});});}
async function openRendition(value){const viewEpoch=epoch;const rid=value.rendition.id,result=await orgRequest('POST',`/screenshot-renditions/${rid}/preview-link`,undefined,{contractVersion:4}),url=new URL(result.data.url,window.location.origin);if(url.origin!==window.location.origin||url.pathname!==`/screenshot-renditions/${rid}/content`)throw new Error('团队图链接范围不符');const blob=await orgRequest('GET',result.data.url,undefined,{binary:true,contractVersion:4});if(alive&&epoch===viewEpoch){dispose();source.value=null;image.value=URL.createObjectURL(blob);}}
function reset(){clear();error.value='单位会话已改变，请重新打开任务附件';}
onMounted(()=>{run(load);window.addEventListener('bid:org-reset',reset);});onUnmounted(()=>{alive=false;clear();window.removeEventListener('bid:org-reset',reset);});
</script>
<template>
 <TaskNavigation :task-id="taskId"/><div class="page-header"><div><h2>任务附件与逐页隐私</h2><p class="subtitle">固定精确资料选择与声明关联；归档、隐私放行和标注就绪分别记录。</p></div><RouterLink :to="`/org/attachments?task=${taskId}`">打开附件资料库</RouterLink></div><el-alert v-if="error" :title="error" type="error" :closable="false" role="alert"/><el-alert v-if="receipt" :title="receipt" type="success" :closable="false" role="status" class="section"/>
 <el-card shadow="never" class="section"><template #header><h3>选择精确声明关联</h3></template><p v-if="!canWrite">需要在职管理员或商务审核，并为此有效任务的负责人或协作者。</p><template v-else><el-select v-model="profileSelection" aria-label="任务固定资料" style="width:350px" @change="loadLinks()"><el-option v-for="row in profiles" :key="row.id" :value="row.id" :label="`${row.data.name} · 修订 ${row.revision} · 分包 ${row.lot??'未指定'}`"/></el-select><el-button :disabled="!profileMeta?.next_cursor||busy" @click="run(()=>profilePage(profileMeta.next_cursor))">下一页任务资料</el-button><p v-if="!profiles.length">本页没有有效资料选择；先在单位资料中显式选择任务资料。</p><div class="actions"><el-select v-model="linkId" aria-label="精确声明附件关联" style="width:400px"><el-option v-for="row in links" :key="row.id" :value="row.id" :label="`${fields[row.field]} · 文件修订 ${row.attachment_revision_id}`" :disabled="!row.active"/></el-select><el-button :disabled="!linkMeta?.next_cursor" @click="loadLinks(linkMeta.next_cursor)">下一页关联</el-button></div><el-input v-model="expected" aria-label="被替换的任务附件选择 ID" placeholder="替换时填写当前选择 ID，空值仅创建空位"/><el-button :disabled="!linkId||busy" type="primary" @click="select">固定此关联到任务</el-button></template></el-card>
 <el-card shadow="never" class="section"><label class="check"><input v-model="history" type="checkbox" :disabled="busy" @change="run(load)">包含失效历史选择与页</label><el-table v-show="selections.length" :data="selections" aria-label="任务固定附件"><el-table-column label="精确修订与声明" min-width="260"><template #default="{row}"><RouterLink :to="`/org/attachments/${row.attachment_id}?revision=${row.attachment_revision_id}&task=${taskId}`">文件修订 {{row.attachment_revision_id}}</RouterLink><p>{{fields[row.field]}} · 分包 {{row.lot??'未指定'}}</p><p class="hint mono">选择 {{row.id}}</p><p v-if="row.library_updated" class="notice warning">附件库有更新（当前修订 {{row.current_library_revision}}）；任务继续固定此精确修订，替换需要显式重新选择与审阅。</p></template></el-table-column><el-table-column label="下一步" min-width="230"><template #default="{row}">{{nextActions[row.readiness.next_action]}}<p>{{row.readiness.blockers.map(code=>`${blockers[code]}（${code}）`).join('；')}}</p></template></el-table-column><el-table-column label="操作" min-width="200"><template #default="{row}"><el-button v-if="canWrite&&row.active" :disabled="busy" @click="archive(row)">归档指定页</el-button><el-button v-if="canWrite&&row.active" :disabled="busy" @click="deactivate(row)">停用选择</el-button></template></el-table-column></el-table><div class="actions"><el-input-number v-if="canWrite" v-model="page" :min="1" :max="200" aria-label="归档页码"/><el-button :disabled="!selectionMeta?.next_cursor||busy" @click="selectionPage(selectionMeta.next_cursor)">下一页任务附件</el-button><el-button :disabled="busy" @click="run(load)">重新读取任务附件</el-button></div></el-card>
 <el-card shadow="never" class="section"><template #header><h3>归档页与 B05 就绪</h3></template><el-table v-show="sources.length" :data="sources" aria-label="附件归档页"><el-table-column label="精确页" min-width="220"><template #default="{row}">第 {{row.page}} 页 · {{formatTime(row.rendered_at)}}<p class="hint mono">{{row.id}}</p></template></el-table-column><el-table-column label="阻塞 / 责任人" min-width="270"><template #default="{row}">{{row.readiness.blockers.map(code=>`${blockers[code]}（${code}）`).join('；')}}<p>{{nextActions[row.readiness.next_action]}} · {{row.readiness.responsible_user_id??'暂无'}}</p></template></el-table-column><el-table-column label="查看" min-width="170"><template #default="{row}"><el-button v-if="originalReader" :disabled="busy" @click="inspect(row)">核对原页隐私</el-button><el-button v-else :disabled="busy||!row.cleared_rendition_id" @click="teamView(row)">查看已放行团队图</el-button><el-button disabled>标注尚未启用</el-button></template></el-table-column></el-table><el-button :disabled="!sourceMeta?.next_cursor||busy" @click="sourcePage(sourceMeta.next_cursor)">下一页归档来源</el-button><p>附件标注选择器未启用（annotation_adapter_not_enabled）；厂商来源未启用（vendor_source_not_enabled）。页面永远不会因归档而进入初稿或导出。</p></el-card>
 <el-card v-if="source||image" shadow="never" class="section"><template #header><h3>{{source?'此精确页的隐私审阅':'已放行团队图'}}</h3></template><img v-if="image" :src="image" class="page-image" :alt="source?'限制级原始附件页':'隐私放行团队图'"/><template v-if="source&&originalReader"><p>第 {{source.page}} 页 · 原始 PNG SHA-256 {{source.source_png_sha256}}</p><p>只审阅此页原始像素；其它页仍需独立审阅。{{source.readiness.blockers.map(code=>`${blockers[code]}（${code}）`).join('；')}}</p><el-select v-model="extraction" aria-label="隐私审阅绑定抽取" style="width:350px"><el-option v-for="job in extractions" :key="job.job_id" :value="job.job_id" :label="`要求抽取 ${job.job_id}`"/></el-select><el-button :disabled="!extractionMeta?.next_cursor||busy" @click="run(()=>extractionPage(extractionMeta.next_cursor))">下一页抽取作业</el-button><p v-if="!extractions.length">本页没有成功的抽取作业；需要先抽取要求，再放行此页。</p><label class="check"><input v-model="reviewed" type="checkbox" :disabled="!image||!canPrivacy">已逐像素核对此页（按此确切 PNG 哈希记录）</label><div class="actions"><el-button :disabled="!reviewed||!extraction||!canPrivacy||!!source.latest_privacy_hold_id||busy" type="primary" @click="privacyReview('clear')">原页安全，允许任务团队查看</el-button><el-button :disabled="!reviewed||!canPrivacy||busy" @click="privacyReview('needs_redaction')">含敏感内容，需要遮挡</el-button></div><p v-if="!canPrivacy">隐私决定需要当前指定档案审阅者与任务协作权限；服务器会核验责任归属。</p><p>遮挡尚未启用（attachment_redaction_not_enabled）；需要遮挡时不会放行原始像素。</p></template><template v-if="privacy?.rendition"><p>隐私回执 {{privacy.rendition.id}} · 审阅者 {{privacy.reviewed_by}}</p><el-button :disabled="busy" @click="run(()=>openRendition(privacy))">查看此回执的团队图</el-button></template></el-card>
</template>
<style scoped>.page-image{display:block;max-width:100%;max-height:75vh;border:1px solid var(--el-border-color)}h3{margin:0}</style>
