// Failure scenarios: cross-org metadata/parent leakage;
// implicit latest-revision use; stale state or removed assignee; unreviewed team
// pixels; global privacy clearance; failed upload inventing success; page retention;
// unchanged uploads converted silently; disabled multipart/redaction/B05 branches.
import {test,expect} from '@playwright/test';
import {createHash} from 'node:crypto';
import {existsSync,mkdirSync,readFileSync,realpathSync,writeFileSync} from 'node:fs';
import {basename,dirname,extname,join,relative,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),work=join(root,'data/work'),artifacts=join(work,'management-pages-validation');
const base=resolve(process.env.E2E_OUTPUT??join(artifacts,'browser')),output=join(base,'attachment');
function inside(a,b){const rel=relative(a,b);return rel!==''&&rel!=='..'&&!rel.startsWith('../')&&!rel.startsWith('/');}
if(!inside(artifacts,base))throw new Error('E2E_OUTPUT must be a run directory in data/work/management-pages-validation');
let ancestor=output;while(!existsSync(ancestor))ancestor=dirname(ancestor);if(!inside(root,realpathSync(ancestor)))throw new Error('Artifact ancestor escapes worktree');
test.use({trace:'off'});
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const O=id(1),U=id(2),T=id(3),A=id(4),R=id(5),F=id(6),P=id(7),PR=id(8),TP=id(9),L=id(10),S=id(11),ES=id(12),J=id(13),RV=id(14),AS=id(15),RE=id(16),R2=id(17),F2=id(18),RV2=id(19),B=id(99),H='a'.repeat(64),MH='b'.repeat(64),date='2026-10-06T00:00:00Z';
const cost={llm_tokens:0,ocr_pages:0,usd:0,basis:'zero',charge:'0',billing_currency:'USD',task_amount:'0',unpriced_calls:0,unresolved_calls:0};
const result=(command,data={},items=[],ok=true)=>({ok,command,data,items,warnings:[],cost,duration_ms:0});
const read=(blockers=[],next_action='review_uploaded_file')=>({blockers,next_action,responsible_user_id:U,can_annotate:false,eligible_for_draft_export:false});
const descriptor={name:'attachment.pdf',media_type:'application/pdf',size_bytes:32,sha256:H,page_count:2};
const meta=(cursor=null)=>({next_cursor:cursor,limit:25,history:false});
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');
const PH=createHash('sha256').update(png).digest('hex');
const records=[];const health=new WeakMap();
test.beforeEach(async({page})=>{await page.context().tracing.start({screenshots:true,snapshots:true,sources:true});const errors=[];health.set(page,errors);page.on('pageerror',err=>errors.push(err.message));await page.addInitScript(({O,U})=>sessionStorage.setItem('bid.org.session',JSON.stringify({session:'synthetic-attachment-session',orgId:O,userId:U,orgName:'合成验收单位'})),{O,U});if(process.env.E2E_STATIC_DIR){const dir=resolve(process.env.E2E_STATIC_DIR);await page.route(url=>url.pathname.startsWith('/app/'),route=>{const path=new URL(route.request().url()).pathname,file=path.startsWith('/app/assets/')?join(dir,'assets',basename(path)):join(dir,'index.html');return route.fulfill({contentType:{'.html':'text/html','.js':'text/javascript','.css':'text/css'}[extname(file)]??'application/octet-stream',body:readFileSync(file)});});}});
test.afterEach(async({page},info)=>{mkdirSync(output,{recursive:true});if(!inside(realpathSync(artifacts),realpathSync(output)))throw new Error('Artifact path escapes worktree');await page.context().tracing.stop({path:join(output,`${info.title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-trace.zip`)});const errors=health.get(page)??[];if(info.status==='passed'&&!errors.length)await page.screenshot({path:join(output,`${info.title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.png`),fullPage:true});records.push({scenario:info.title,status:info.status,console_errors:errors,measurements:info.annotations.filter(row=>row.type==='measurement').map(row=>JSON.parse(row.description))});writeFileSync(join(output,'result.json'),JSON.stringify({mode:'mocked_api',schema_version:'4.0',fixture_version:'attachment-management-v1',fixture_png_sha256:createHash('sha256').update(png).digest('hex'),command:'E2E_OUTPUT=data/work/management-pages-validation/browser npm --prefix web exec -- playwright test e2e/attachment-management.spec.js',scenarios:records,passed:records.every(row=>row.status==='passed'&&!row.console_errors.length)},null,2));expect(errors).toEqual([]);});
async function fixture(page,options={}){
 const requests=[],state={review:options.review??'pending',version:options.updated?4:1,reviewer:options.departed?B:U,privacy:options.cleared?'clear':'pending',hold:null,source:options.source??true,failed:false};
 const summary=()=>({id:A,org_id:options.foreign?B:O,current_revision_id:options.updated?R2:R,current_revision:options.updated?2:1,state_version:state.version,kind:'contract',active:true,custodian_user_id:U,reviewer_user_id:state.reviewer,review_state:state.review,latest_review_id:state.review==='approved'?(options.updated?RV2:RV):null,created_at:date,readiness:read(options.departed?['reviewer_unavailable']:state.review==='approved'?['profile_link_missing']:[`archive_review_${state.review}`],options.departed?'assign_reviewer':state.review==='approved'?'link_declaration':state.review==='rejected'?'upload_corrected_revision':'review_uploaded_file')});
 const revision=(number=1)=>({id:number===2?R2:R,org_id:O,attachment_id:A,revision:number,file_id:number===2?F2:F,kind:'contract',original_sha256:H,metadata_sha256:MH,page_count:2,size_bytes:32,review_state:state.review,latest_review_id:state.review==='approved'?(number===2?RV2:RV):null,created_by:U,created_at:date,metadata:{kind:'contract',label:'合成合同附件'},original:descriptor,parts:[]});
 const link=()=>({id:L,org_id:O,profile_id:P,profile_revision_id:PR,field:'performance_summary',attachment_id:A,attachment_revision_id:R,file_id:F,approval_id:RV,active:true,state_version:1,created_by:U,created_at:date});
 const selection=()=>({id:S,org_id:O,task_id:T,task_org_profile_id:TP,profile_revision_id:PR,profile_attachment_link_id:L,field:'performance_summary',attachment_id:A,attachment_revision_id:R,file_id:F,approval_id:RV,original_sha256:H,lot:null,active:true,state_version:1,selected_by:U,selected_at:date,library_updated:!!options.updated,current_library_revision:options.updated?2:1,readiness:read(['source_not_archived'],'archive_page')});
 const source=()=>({id:ES,org_id:O,task_id:T,task_attachment_id:S,attachment_revision_id:R,page:1,source_kind:'user_supplied_attachment_pdf',original_sha256:H,source_png_sha256:PH,rendered_at:date,active_selection:true,latest_privacy_hold_id:state.hold,cleared_asset_id:state.privacy==='clear'?AS:null,cleared_rendition_id:state.privacy==='clear'?RE:null,readiness:read(state.privacy==='clear'?['annotation_adapter_not_enabled']:state.privacy==='needs_redaction'?['needs_redaction']:['privacy_pending'],state.privacy==='clear'?'wait_for_annotation_enablement':state.privacy==='needs_redaction'?'redact_page':'review_page_privacy'),status:'unconfirmed_source',confirmed_by:null,eligible_for_draft_export:false});
 const rendition=()=>({id:RE,asset_id:AS,image:{sha256:PH,size_bytes:png.length,width_px:1,height_px:1,media_type:'image/png'},profile:'screenshot-markup-v1'});
 await page.route(url=>!url.pathname.startsWith('/app/'),async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname.replace(/^\/v4/,''),method=req.method();requests.push({method,path,query:Object.fromEntries(url.searchParams)});const json=(command,data={},items=[])=>route.fulfill({json:result(command,data,items)});const failure=(code,status=409)=>route.fulfill({status,json:result('attachment',{error:{code,message:code,exit_code:status===404?4:2}},[],false)});
 if(path==='/org/current')return json('org current',{org_id:O,user_id:U,role:options.role??'bidder'});
 if(path===`/tasks/${T}/workflow`)return json('task workflow',{workflow:{org_id:O,task_id:T,state:options.archived?'archived':'active',last_event_cursor:'synthetic-task-head'}});
 if(path===`/tasks/${T}/members`)return json('task member list',{org_id:O,task_id:T,next_cursor:null},options.lost?[]:[{user_id:U,active:true,role:'contributor',review_domains:['commercial']}]);
 if(path===`/tasks/${T}/events`)return route.fulfill({contentType:'text/event-stream',body:''});
 if(path===`/tasks/${T}/events/poll`)return json('task events',{task_id:T,events:[],next_cursor:null});
 if(path==='/management/resources/attachments/query'){const query=req.postDataJSON(),offset=query.cursor?Number(query.cursor.slice(1)):0;requests[requests.length-1].query=query;return json('resource attachment browse',meta(options.paged&&offset<39?`p${offset+1}`:null),options.paged?Array.from({length:25},(_,index)=>({...summary(),id:id(1000+offset*25+index)})):[summary()]);}
 if(path==='/resources/attachments'&&method==='GET'){const cursor=url.searchParams.get('cursor'),offset=cursor?Number(cursor.slice(1)):0;return json('resource attachment list',meta(options.paged&&offset<39?`p${offset+1}`:null),options.paged?Array.from({length:25},(_,index)=>({...summary(),id:id(1000+offset*25+index)})):[summary()]);}
 if(path==='/resources/attachments'&&method==='POST'){if(options.uploadFailure&&!state.failed){state.failed=true;return failure('storage_unavailable',503);}return json('resource attachment upload',{attachment_id:A,revision_id:R,file_id:F,revision:1,state_version:1,review_state:'pending',duplicate:false,next_action:'review_uploaded_file'});}
 if(path===`/resources/attachments/${A}`)return json('resource attachment show',{attachment:summary()});
 if(path===`/resources/attachments/${A}/revisions`&&method==='GET'){const rows=(options.updated?[revision(),revision(2)]:[revision()]).map(({metadata,original,parts,...row})=>row);return json('resource attachment history',meta(),rows);}
 if(options.updated&&path===`/resources/attachments/revisions/${R2}`)return json('resource attachment revision show',revision(2));
 if(path===`/resources/attachments/revisions/${R}`)return json('resource attachment revision show',revision());
 if(path===`/resources/attachments/revisions/${R}/reviews`||(options.updated&&path===`/resources/attachments/revisions/${R2}/reviews`)){if(method==='POST'){const body=req.postDataJSON();expect(body.original_sha256).toBe(H);expect(body.metadata_sha256).toBe(MH);if(options.conflict)return failure('attachment_state_changed');state.review=body.decision==='approve'?'approved':body.decision==='reject'?'rejected':'revoked';state.version++;return json('resource attachment review',{id:RV,reviewed_by:U});}return json('resource attachment reviews',meta(),[]);}
 if(path===`/resources/attachments/${A}/assignment`){const body=req.postDataJSON();expect(body.expected_state_version).toBe(state.version);state.reviewer=body.reviewer_user_id;state.version++;return json('resource attachment assign',{attachment:summary()});}
 if(path===`/resources/attachments/revisions/${R}/pages/1/preview-link`)return json('resource attachment page preview',{url:`/resources/attachments/revisions/${R}/pages/1/preview?zoom=1&signature=synthetic`,expires_in:300});
 if(path===`/resources/attachments/revisions/${R}/pages/1/preview`)return route.fulfill({contentType:'image/png',body:png});
 if(path==='/management/resources/profiles/query')return json('resource profile browse',{next_cursor:null,has_more:false,returned:1},[{ref:{resource_id:P},name:'合成单位声明'}]);
 if(path===`/management/resources/profiles/${P}`)return json('resource profile show',{detail:{revision:{id:PR,revision:1,data:{name:'合成单位声明',registration_details:'登记声明',performance_summary:'非空业绩声明',standard_wording:null}}}});
 if(path===`/resources/profiles/revisions/${PR}/attachments`){if(method==='POST'){const body=req.postDataJSON();expect(body.attachment_revision_id).toBe(R);expect(body.approval_id).toBe(RV);expect(body.field).toBe('performance_summary');return json('resource profile attachment link',link());}return json('resource profile attachment list',meta(),[link()]);}
 if(path===`/tasks/${T}/profiles`)return json('task profile list',meta(),[{id:TP,org_id:O,task_id:T,profile_revision_id:PR,revision:1,lot:null,data:{name:'合成单位声明'}}]);
 if(path===`/tasks/${T}/progress`)return json('task progress',{org_id:O,task_id:T,next_cursor:null},[{id:J,kind:'extract',status:'succeeded'}]);
 if(path===`/tasks/${T}/attachments`){if(method==='POST'){const body=req.postDataJSON();expect(body.task_org_profile_id).toBe(TP);expect(body.profile_attachment_link_id).toBe(L);expect(body.expected_selection_id).toBeNull();return json('task attachment select',selection());}return json('task attachment list',meta(),[selection()]);}
 if(path===`/tasks/${T}/attachment-sources`){if(method==='POST'){const body=req.postDataJSON();expect(body.task_attachment_id).toBe(S);expect(body.page).toBe(1);state.source=true;return json('evidence attachment source create',{source:source(),duplicate:false});}return json('evidence attachment source list',meta(),state.source?[source()]:[]);}
 if(path===`/attachment-sources/${ES}`)return json('evidence attachment source show',source());
 if(path===`/attachment-sources/${ES}/preview/download-link`){if(options.role==='technical')return failure('forbidden',403);return json('evidence attachment source preview',{url:`/attachment-sources/${ES}/preview/download?signature=synthetic`,expires_in:300});}
 if(path===`/attachment-sources/${ES}/preview/download`)return route.fulfill({contentType:'image/png',body:png});
 if(path===`/attachment-sources/${ES}/privacy`){const body=req.postDataJSON();expect(body.reviewed_source_png_sha256).toBe(PH);state.privacy=body.mode;if(body.mode==='needs_redaction'){state.hold=id(17);return json('evidence attachment privacy review',{id:state.hold,state:'needs_redaction'});}expect(body.extraction_job_id).toBe(J);return json('evidence attachment privacy review',{org_id:O,evidence_source_id:ES,task_id:T,source_png_sha256:PH,rendition:rendition(),reviewed_by:U,reviewed_at:date});}
 if(path===`/screenshot-renditions/${RE}/preview-link`&&method==='POST')return json('screenshot preview',{url:`/screenshot-renditions/${RE}/content?signature=synthetic`,expires_in:300});
 if(path===`/screenshot-renditions/${RE}/content`)return route.fulfill({contentType:'image/png',body:png});
 return failure('not_found',404);
 });return{state,requests};
}
async function choose(page,label,optionName){
 const control=page.getByRole('combobox',{name:label,exact:true});
 await expect(control).toHaveCount(1);
 await expect(control).toBeEnabled();
 // The placeholder overlays the semantic input; use the visible user-facing trigger.
 const trigger=page.locator('.el-select').filter({has:control}).locator('.el-select__wrapper');
 await expect(trigger).toBeVisible();
 if(await control.getAttribute('aria-expanded')!=='true')await trigger.click();
 await expect(control).toHaveAttribute('aria-expanded','true');
 await expect(control).toHaveAttribute('aria-controls',/\S+/);
 const popup=page.locator(`[id=${JSON.stringify(await control.getAttribute('aria-controls'))}]`);
 await expect(popup).toHaveAttribute('role','listbox');
 await expect(popup).toBeVisible();
 const option=popup.getByRole('option',{name:optionName,exact:true,includeHidden:true});
 await expect(option).toBeVisible();
 await expect(option).toBeEnabled();
 if(await option.getAttribute('aria-selected')!=='true')await option.click();
 await expect(option).toHaveAttribute('aria-selected','true');
 if(await control.getAttribute('aria-expanded')==='true')await control.press('Escape');
 await expect(control).toHaveAttribute('aria-expanded','false');
}
async function open(page,path){await page.goto(`/app${path}`);}
test('single PDF upload failure retry retains explicit reviewer and request identity',async({page})=>{const {requests}=await fixture(page,{uploadFailure:true});await open(page,'/org/attachments');await page.getByRole('button',{name:'上传附件',exact:true}).click();await page.getByLabel('附件显示名称').fill('合成合同附件');await page.getByLabel('附件审阅者成员 ID').fill(U);await page.getByLabel('PDF 原件').setInputFiles({name:'synthetic.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-synthetic')});await page.getByRole('button',{name:'保存并交审阅者'}).click();await expect(page.getByRole('alert')).toContainText('storage_unavailable');await page.getByRole('button',{name:'保存并交审阅者'}).click();await expect(page.getByRole('heading',{name:'合成合同附件',exact:true})).toBeVisible();expect(requests.filter(req=>req.method==='POST'&&req.path==='/resources/attachments')).toHaveLength(2);});
test('review exact original and link exact nonempty profile declaration',async({page})=>{const {requests}=await fixture(page);await open(page,`/org/attachments/${A}`);await expect(page.getByRole('button',{name:'接受内部使用',exact:true})).toBeDisabled();await page.getByRole('button',{name:'核对此页原件'}).click();await page.getByLabel('已核对此精确修订原件，接受内部使用').check();await page.getByRole('button',{name:'接受内部使用',exact:true}).click();await expect(page.getByRole('status')).toContainText('已接受内部使用');await choose(page,'单位资料','合成单位声明');await page.getByRole('button',{name:'打开资料精确修订'}).click();await choose(page,'关联声明字段','业绩声明');await page.getByRole('button',{name:'关联此精确修订与声明'}).click();await expect(page.getByRole('status')).toContainText('已关联精确声明');expect(requests.some(req=>req.method==='POST'&&req.path.includes('/attachments'))).toBe(true);});
test('rejected revision directs corrected upload and cannot link declarations',async({page})=>{await fixture(page,{review:'rejected'});await open(page,`/org/attachments/${A}`);await expect(page.getByText(/上传更正修订/).first()).toBeVisible();await choose(page,'单位资料','合成单位声明');await page.getByRole('button',{name:'打开资料精确修订'}).click();await expect(page.getByRole('button',{name:'关联此精确修订与声明'})).toBeDisabled();});
test('stale review leaves inspected revision and acceptance input for explicit refresh',async({page})=>{await fixture(page,{conflict:true});await open(page,`/org/attachments/${A}`);await page.getByRole('button',{name:'核对此页原件'}).click();await page.getByLabel('已核对此精确修订原件，接受内部使用').check();await page.getByRole('button',{name:'接受内部使用',exact:true}).click();await expect(page.getByRole('alert')).toContainText('attachment_state_changed');await expect(page.getByLabel('已核对此精确修订原件，接受内部使用')).toBeChecked();await expect(page.getByAltText('限制级原件页预览')).toBeVisible();});
test('departed reviewer blocks pending work and assignment carries expected state',async({page})=>{await fixture(page,{departed:true});await open(page,`/org/attachments/${A}`);await expect(page.getByText(/reviewer_unavailable/)).toBeVisible();await expect(page.getByRole('button',{name:'接受内部使用',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'调整保管人和审阅者'}).click();await page.getByLabel('在职审阅者成员 ID').fill(U);await page.getByRole('button',{name:'保存责任分配'}).click();await expect(page.getByRole('button',{name:'接受内部使用',exact:true})).toBeVisible();});
test('task pin source privacy exact page shows disabled B05 adapter',async({page})=>{await fixture(page,{review:'approved',source:false});await open(page,`/org/tasks/${T}/attachments`);await choose(page,'任务固定资料','合成单位声明 · 修订 1 · 分包 未指定');await choose(page,'精确声明附件关联',`业绩声明 · 文件修订 ${R}`);await page.getByRole('button',{name:'固定此关联到任务'}).click();await page.getByRole('button',{name:'归档指定页'}).click();await page.getByRole('button',{name:'核对原页隐私'}).click();await choose(page,'隐私审阅绑定抽取',`要求抽取 ${J}`);await page.getByLabel('已逐像素核对此页（按此确切 PNG 哈希记录）').check();await page.getByRole('button',{name:'原页安全，允许任务团队查看'}).click();await expect(page.getByText(/annotation_adapter_not_enabled/).first()).toBeVisible();await expect(page.getByRole('button',{name:'标注尚未启用'})).toBeDisabled();await page.getByRole('button',{name:'查看此回执的团队图'}).click();});
test('privacy hold never clears raw pixels and explicitly blocks redaction',async({page})=>{await fixture(page,{review:'approved'});await open(page,`/org/tasks/${T}/attachments`);await page.getByRole('button',{name:'核对原页隐私'}).click();await page.getByLabel('已逐像素核对此页（按此确切 PNG 哈希记录）').check();await page.getByRole('button',{name:'含敏感内容，需要遮挡'}).click();await expect(page.getByText(/needs_redaction/).first()).toBeVisible();await expect(page.getByRole('status')).toContainText('attachment_redaction_not_enabled');await expect(page.getByRole('button',{name:'原页安全，允许任务团队查看'})).toBeDisabled();});
test('technical reader sees metadata and no raw review or task pin controls',async({page})=>{const {requests}=await fixture(page,{role:'technical',cleared:true});await open(page,`/org/tasks/${T}/attachments`);await expect(page.getByRole('button',{name:'核对原页隐私'})).toHaveCount(0);await expect(page.getByRole('button',{name:'固定此关联到任务'})).toHaveCount(0);await expect(page.getByRole('button',{name:'查看已放行团队图'})).toBeVisible();await page.getByRole('button',{name:'查看已放行团队图'}).click();await expect(page.getByAltText('隐私放行团队图')).toBeVisible();expect(requests.some(req=>req.path.includes('/preview/download'))).toBe(false);expect(requests.some(req=>req.path===`/screenshot-renditions/${RE}/content`)).toBe(true);});
test('lost task membership keeps selectors unavailable',async({page})=>{await fixture(page,{lost:true});await open(page,`/org/tasks/${T}/attachments`);await expect(page.getByRole('button',{name:'固定此关联到任务'})).toHaveCount(0);await expect(page.getByRole('button',{name:'归档指定页'})).toHaveCount(0);});
test('cross org metadata response fails closed before original reads',async({page})=>{const {requests}=await fixture(page,{foreign:true});await open(page,`/org/attachments/${A}`);await expect(page.getByRole('alert')).toContainText('范围不符合契约');expect(requests.some(req=>req.path===`/resources/attachments/revisions/${R}`)).toBe(false);});
test('historical revision keeps pinned identity and shows library update notice',async({page})=>{
 const {requests}=await fixture(page,{review:'approved',updated:true});
 await open(page,`/org/attachments/${A}?revision=${R}`);
 const notice=page.getByText('资料库有较新修订；此处仍为精确历史修订，不自动替换关联与任务选择。');
 await expect(notice).toBeVisible();
 await expect(page.getByText(`修订 ID ${R} · 原件 ID ${F}`)).toBeVisible();
 expect(requests.some(req=>req.path===`/resources/attachments/revisions/${R}`)).toBe(true);
 expect(requests.some(req=>req.path===`/resources/attachments/revisions/${R2}`)).toBe(false);
 await open(page,`/org/attachments/${A}`);
 await expect(page.getByText(`修订 ID ${R2} · 原件 ID ${F2}`)).toBeVisible();
 await expect(notice).toHaveCount(0);
});
test('bounded metadata list releases old parsed pages after explicit GC',async({page},info)=>{
 test.setTimeout(120_000);
 await page.addInitScript(()=>{window.__attachmentRetention={refs:[],pages:0,bytes:0};const json=Response.prototype.json;Response.prototype.json=async function(...args){const result=await json.apply(this,args);if(result.command==='resource attachment browse'&&Array.isArray(result.items)){const track=window.__attachmentRetention,bytes=value=>new TextEncoder().encode(JSON.stringify(value)).length;track.pages++;track.bytes+=bytes(result);track.refs.push({target:new WeakRef(result.items),bytes:bytes(result.items)},{target:new WeakRef(result.data),bytes:bytes(result.data)});}return result;};});
 const {requests}=await fixture(page,{paged:true});await open(page,'/org/attachments');const list=page.getByRole('region',{name:'附件档案列表',exact:true});await expect(list).toBeVisible();await expect(list.locator('tbody tr')).toHaveCount(25);
 for(let index=0;index<39;index++){await page.getByRole('button',{name:'下一页',exact:true}).click();await expect(list.locator('tbody tr')).toHaveCount(25);await expect(page.getByText(id(1000+(index+1)*25),{exact:true})).toBeVisible();}
 await expect(page.getByRole('button',{name:'下一页',exact:true})).toBeDisabled();
 const cdp=await page.context().newCDPSession(page);try{await cdp.send('HeapProfiler.collectGarbage');}finally{await cdp.detach();}
 const measured=await page.evaluate(()=>{const track=window.__attachmentRetention,live=track.refs.filter(row=>row.target.deref()!==undefined);return{pages:track.pages,transferred_bytes:track.bytes,retained_bytes:live.reduce((sum,row)=>sum+row.bytes,0),retained_page_arrays:live.filter(row=>Array.isArray(row.target.deref())).length};});
 expect(measured.pages).toBe(40);expect(measured.retained_page_arrays).toBeLessThanOrEqual(1);expect(measured.retained_bytes).toBeLessThanOrEqual(1024*1024);expect(requests.filter(req=>req.path==='/management/resources/attachments/query').every(req=>req.query.limit===25)).toBe(true);info.annotations.push({type:'measurement',description:JSON.stringify({...measured,maximum_request_limit:25,measurement:'WeakRef parsed metadata arrays after explicit GC'})});
});
