// Failure scenarios: legacy unbounded reads; secret prefill or persistence;
// org/task owner mixups and raw history; missing-null CAS and automatic retries;
// archived fields or removed authority; stale replies; uncleared explicit reveal;
// paging/filter reuse, excessive reads, inaccessible/oversized projections;
// inaccessible keyboard/mobile actions and secret-bearing test artifacts.
import { test, expect } from "@playwright/test";
import { createHash, randomUUID } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Playwright otherwise writes error-context.md aria snapshots even with trace
// off. Its teardown reads this switch dynamically before taking a DOM snapshot.
process.env.PLAYWRIGHT_NO_COPY_PROMPT = "1";

// No trace, screenshot, video or HAR can record transient secret entry/reveal.
// This applies to every case so command-line artifact defaults cannot capture it.
test.use({ trace: "off", screenshot: "off", video: "off" });
const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const work = join(root, "data/work"), allowed = join(work, "management-pages-validation");
const output = resolve(process.env.E2E_OUTPUT ?? join(allowed, "confidential"));
function inside(base, path) { const rel = relative(base, path); return rel !== ".." && !rel.startsWith(`..${process.platform === "win32" ? "\\" : "/"}`) && !rel.startsWith("/"); }
if (!inside(allowed, output)) throw new Error("E2E_OUTPUT must be inside data/work/management-pages-validation");
let ancestor = output; while (!existsSync(ancestor)) ancestor = dirname(ancestor);
if (!inside(realpathSync(root), realpathSync(ancestor))) throw new Error("Artifact path resolves outside worktree");
const O="00000000-0000-0000-0000-000000000002", U="00000000-0000-0000-0000-000000000003", T="00000000-0000-0000-0000-000000000001", F="00000000-0000-0000-0000-000000000010", G="00000000-0000-0000-0000-000000000011";
const valueId = n => `00000000-0000-0000-0000-${String(100 + n).padStart(12,"0")}`;
const date="2026-10-06T00:00:00Z";
const cost={llm_tokens:0,ocr_pages:0,usd:0,basis:"zero",charge:"0",billing_currency:"USD",task_amount:"0",unpriced_calls:0,unresolved_calls:0};
const result=(command,data={},items=[],ok=true)=>({ok,command,data,items,warnings:[],cost,duration_ms:0});
const records=[],healthByPage=new WeakMap();
test.beforeEach(async({page})=>{
  const health=[];healthByPage.set(page,health);
  // Retain counts only; browser messages can contain arbitrary response text.
  page.on("pageerror",()=>health.push("pageerror"));page.on("console",message=>{if(["error","warning"].includes(message.type())&&!message.text().startsWith("Failed to load resource"))health.push(message.type());});
  await page.addInitScript(({O,U})=>sessionStorage.setItem("bid.org.session",JSON.stringify({session:"synthetic-confidential-session",orgId:O,userId:U,orgName:"合成验收单位"})),{O,U});
  if(process.env.E2E_STATIC_DIR){const dir=resolve(process.env.E2E_STATIC_DIR);if(!inside(root,dir)||!inside(realpathSync(root),realpathSync(dir)))throw new Error("Static build must be inside worktree");await page.route(url=>url.pathname.startsWith("/app/"),route=>{const path=new URL(route.request().url()).pathname;const file=path.startsWith("/app/assets/")?join(dir,"assets",basename(path)):join(dir,"index.html");return route.fulfill({contentType:{".html":"text/html",".js":"text/javascript",".css":"text/css"}[extname(file)]??"application/octet-stream",body:readFileSync(file)});});}
});
test.afterEach(async({page},info)=>{
  // Run before any artifact work, including when a secret scenario has failed.
  // No DOM text is read; a closed/crashed page cannot prevent safe teardown.
  await page.evaluate(async()=>{window.dispatchEvent(new Event("blur"));window.dispatchEvent(new Event("bid:org-reset"));await Promise.resolve();}).catch(()=>{});
  mkdirSync(output,{recursive:true});if(!inside(realpathSync(work),realpathSync(output)))throw new Error("Artifact symlink escapes data/work");
  const health=healthByPage.get(page)??[],overlay=await page.locator("vite-error-overlay").count();
  records.push({scenario:info.title,status:info.status==="passed"&&(health.length||overlay)?"failed":info.status,console_errors:health.length,framework_overlay:overlay,measurements:info.annotations.filter(item=>item.type==="measurement").map(item=>JSON.parse(item.description))});
  const index=process.env.E2E_STATIC_DIR?join(resolve(process.env.E2E_STATIC_DIR),"index.html"):null;
  writeFileSync(join(output,"result.json"),JSON.stringify({mode:"mocked_api",fixture_version:"confidential-management-v1",schema_version:"4.0",browser:"chromium",browser_version:page.context().browser()?.version()??null,build_sha256:index?createHash("sha256").update(readFileSync(index)).digest("hex"):null,base_url:process.env.E2E_BASE_URL??null,secret_capture:"disabled",command:`cd web && E2E_BASE_URL=http://127.0.0.1:8000 ${index?'E2E_STATIC_DIR="$PWD/dist" ':''}E2E_OUTPUT=../data/work/management-pages-validation/confidential node_modules/.bin/playwright test e2e/confidential-management.spec.js`,scenarios:records,passed:records.every(item=>item.status==="passed")},null,2));
  writeFileSync(join(output,"assertions.json"),JSON.stringify({mode:"mocked_api",scope:"Browser contracts only; database authorization and fixed-scale acceptance are separate",checks:["exact v4 paths and bounded pages","org/task scope and live role UI gates","required-null and exact UUID CAS","no plaintext outside explicit reveal","reveal cleanup and transient submit","no secret screenshots/traces/video/HAR/automatic DOM snapshots"],scenario_count:records.length},null,2));
  expect(health.length,"Browser errors (content omitted)").toBe(0);expect(overlay,"Framework overlay").toBe(0);
});
async function fixture(page,options={}){
  const state={role:"bidder",taskRole:"contributor",taskArchived:false,scope:"org",revision:1,version:2,archived:false,...options};
  const writes=[],queries=[],requests=[];let release,active=0,maxActive=0,conflicted=false,canary=null;
  const field=(id=F)=>({id,key:id===F?state.key??"bid_total":"contact_phone",placeholder:`{{secret.${id===F?state.key??"bid_total":"contact_phone"}}}`,label:id===F?state.label??"合成报价":"后页联系人",kind:id===F?state.kind??"amount":"contact",scope:state.scope,archived:state.archived,revision:state.revision,created_at:date});
  const value=(id=F,n=state.version)=>{const f=field(id);return {field_id:id,key:f.key,placeholder:f.placeholder,label:f.label,kind:f.kind,scope:f.scope,task_id:f.scope==="task"?T:null,status:n?"filled":"missing",value_id:n?valueId(n):null,version:n||null,tail:null,set_by:n?U:null,set_at:n?date:null};};
  const meta=(items,next=null)=>({org_id:state.foreign?G:O,as_of:date,returned:items.length,next_cursor:next,has_more:!!next});
  const fail=(route,code,status=403)=>route.fulfill({status,json:result("confidential write",{error:{code,message:"Safe synthetic failure",exit_code:status===409?2:4}},[],false)});
  await page.route(url=>!url.pathname.startsWith("/app/"),async route=>{
    const req=route.request(),url=new URL(req.url()),path=url.pathname.replace(/^\/v4(?=\/)/,"");requests.push({path,method:req.method(),query:url.search});
    if(path==="/org/current")return route.fulfill({json:result("org current",{org_id:O,user_id:U,role:state.role})});
    if(path===`/tasks/${T}/workflow`){if(state.taskDenied)return fail(route,"not_found",404);return route.fulfill({json:result("task workflow",{workflow:{org_id:O,task_id:T,state:state.taskArchived?"archived":"active",revision:1,last_event_cursor:"opaque",owner_user_id:U}})});}
    if(path===`/tasks/${T}/members`){const items=state.taskRole?[{org_id:O,task_id:T,user_id:U,role:state.taskRole,active:true,review_domains:[],revision:1}]:[];return route.fulfill({json:result("task member list",{...meta(items),task_id:T},items)});}
    if(path==="/management/confidential-fields/query"||path==="/management/confidential-values/query"){
      expect(url.pathname.startsWith("/v4/")).toBe(true);expect(req.method()).toBe("POST");expect(url.search).toBe("");const body=req.postDataJSON();queries.push({path,...body});expect(body.limit).toBe(25);active++;maxActive=Math.max(maxActive,active);
      if(state.delay&&body.q==="旧查询")await new Promise(resolve=>{release=resolve;});active--;
      if(state.queryError)return fail(route,state.queryError,state.queryError==="management_result_too_large"?413:409);
      const fields=path.includes("fields"),id=body.cursor?G:F;
      let items=body.q==="空结果"||state.empty||!fields&&state.scope==="task"&&!body.task_id||state.archived&&!body.archived?[]:[fields?field(id):value(id)];
      if(state.collisions&&body.q&&!body.field_id)items=Array.from({length:25},(_,i)=>({...field(valueId(200+i)),key:`a_${i}`,placeholder:`{{secret.a_${i}}}`,label:field().key}));
      if(body.field_id)items=body.field_id===F?[fields?field():value()]:[];
      if(state.raw&&items.length)items[0].value="forbidden projection";
      if(state.oversize&&items.length)while(items.length<=100)items.push({...items[0]});
      if(state.retentionPages&&!body.field_id&&!body.q){
        const index=body.cursor?Number(body.cursor.slice("retention-".length)):0;
        items=Array.from({length:25},(_,row)=>{const id=valueId(1000+index*25+row),key=`field_${index}_${row}`,common={key,placeholder:`{{secret.${key}}}`,label:`分页${String(index).padStart(2,"0")}-${row}`};return fields?{...field(id),...common}:{...value(id),...common,value_id:valueId(3000+index*25+row)};});
        return route.fulfill({json:result(fields?"confidential field browse":"confidential browse",meta(items,index+1<state.retentionPages?`retention-${index+1}`:null),items)});
      }
      return route.fulfill({json:result(fields?"confidential field browse":"confidential browse",meta(items,state.paginated&&!body.cursor&&!body.q?"opaque-next":null),items)});
    }
    if(path===`/management/confidential-fields/${F}/values/history/query`){const body=req.postDataJSON();expect(body.task_id).toBe(state.scope==="task"?T:null);queries.push({path,...body});const items=state.version?[value(F,body.cursor?1:state.version)]:[];return route.fulfill({json:result("confidential history-page",meta(items,state.historyPaginated&&!body.cursor?"opaque-history":null),items)});}
    if(req.method()==="POST"){
      const body=req.postData()?req.postDataJSON():null;
      // Never retain a secret in a fixture receipt, assertion, log or artifact.
      if(path===`/management/confidential-fields/${F}/values`){const secretMatches=typeof body?.value==="string"&&body.value===canary;writes.push({path,secretMatches,expected_field_revision:body.expected_field_revision,expected_value_id:body.expected_value_id,task_id:body.task_id});
        if(state.mutationDenied)return fail(route,"forbidden");
        if(state.networkLoss){state.networkLoss=false;state.version++;return route.abort("failed");}
        if(state.conflict&&!conflicted){conflicted=true;state.version++;state.revision++;return fail(route,"confidential_value_conflict",409);}
        expect(Object.hasOwn(body,"expected_value_id")).toBe(true);expect(body.expected_value_id).toBe(state.version?valueId(state.version):null);expect(body.expected_field_revision).toBe(state.revision);expect(body.task_id).toBe(state.scope==="task"?T:null);expect(secretMatches,"Transient write uses input once").toBe(true);state.version++;return route.fulfill({json:result("confidential set-checked",value())});}
      if(path.startsWith("/confidential-values/")&&path.endsWith("/reveal")){writes.push({path});if(state.revealDenied)return fail(route,"forbidden");return route.fulfill({json:result("confidential reveal",{field_id:F,value_id:valueId(state.version),key:field().key,value:canary??"synthetic reveal"})});}
      if(path===`/confidential-fields/${F}/revisions`){writes.push({path,...body});if(state.fieldConflict&&!conflicted){conflicted=true;state.revision++;return fail(route,"revision_conflict",409);}expect(body.expected_revision).toBe(state.revision);if(body.label)state.label=body.label;if(body.archived!==undefined)state.archived=body.archived;state.revision++;return route.fulfill({json:result("confidential field update",field())});}
      if(path==="/confidential-fields"){writes.push({path,...body});state.scope=body.scope;state.label=body.label;state.key=body.key;state.kind=body.kind;return route.fulfill({json:result("confidential field add",{...field(),key:body.key,placeholder:`{{secret.${body.key}}}`,kind:body.kind})});}
    }
    throw new Error(`Unexpected confidential request: ${req.method()} ${path}`);
  });
  return {state,writes,queries,requests,release:()=>release?.(),maxActive:()=>maxActive,setCanary:value=>{canary=value;}};
}
async function typeSecret(page,f){const canary=`synthetic-${randomUUID()}`;f.setCanary(canary);await page.getByLabel("新的保密值",{exact:true}).evaluate((input,value)=>{input.value=value;input.dispatchEvent(new Event("input",{bubbles:true}));},canary);return canary;}
async function blankSecret(page){expect(await page.getByLabel("新的保密值",{exact:true}).evaluate(input=>input.value===""),"Secret input is blank (content omitted)").toBe(true);}
async function noSecretLeak(page,canary){const absent=await page.evaluate(value=>!document.body.textContent.includes(value)&&![...document.querySelectorAll("input")].some(input=>input.value===value)&&!JSON.stringify({...localStorage,...sessionStorage}).includes(value)&&!location.href.includes(value),canary);expect(absent,"Transient secret absent from DOM, storage and URL").toBe(true);}

test("bounded browse, debounce, native archive filter and page eviction",async({page})=>{const f=await fixture(page,{paginated:true});await page.goto("/app/org/confidential");await expect(page.getByText("合成报价",{exact:true})).toBeVisible();await page.getByRole("button",{name:"下一页保密字段",exact:true}).click();await expect(page.getByText("后页联系人",{exact:true})).toBeVisible();await expect(page.getByText("合成报价",{exact:true})).toHaveCount(0);await page.getByLabel("搜索保密字段").fill("空结果");await expect(page.getByText("没有符合条件的保密字段")).toBeVisible();await page.getByLabel("包含归档字段").check();await expect.poll(()=>f.queries.at(-1).archived).toBe(true);expect(f.queries.at(-1)).toMatchObject({cursor:null,q:"空结果",limit:25});expect(f.requests.some(item=>item.method==="GET"&&["/confidential-fields","/confidential-values"].includes(item.path))).toBe(false);expect(await page.evaluate(()=>JSON.stringify({...sessionStorage,...localStorage}))).not.toContain("空结果");expect(page.url()).not.toContain("空结果");expect(await page.locator("table[aria-label='保密字段列表'] tbody tr").count()).toBeLessThanOrEqual(25);});
test("blank first entry sends required null CAS and clears immediately",async({page})=>{const f=await fixture(page,{version:0});await page.goto("/app/org/confidential");await page.getByRole("button",{name:"填写新值",exact:true}).click();await blankSecret(page);const canary=await typeSecret(page,f);await page.getByRole("button",{name:"保存新值",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"已保存保密值版本 1"})).toBeVisible();expect(f.writes).toEqual([{path:`/management/confidential-fields/${F}/values`,secretMatches:true,expected_field_revision:1,expected_value_id:null,task_id:null}]);await noSecretLeak(page,canary);await page.getByRole("button",{name:"填写新值",exact:true}).click();await blankSecret(page);});
test("value conflict clears secret, refreshes both preconditions, deliberate retry only",async({page})=>{const f=await fixture(page,{conflict:true});await page.goto("/app/org/confidential");await page.getByRole("button",{name:"填写新值",exact:true}).click();const first=await typeSecret(page,f);await page.getByRole("button",{name:"保存新值",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"输入已清空"})).toBeVisible();await blankSecret(page);expect(f.writes.length).toBe(1);await noSecretLeak(page,first);const second=await typeSecret(page,f);await page.getByRole("button",{name:"保存新值",exact:true}).click();await expect.poll(()=>f.writes.length).toBe(2);expect(f.writes[1]).toMatchObject({expected_field_revision:2,expected_value_id:valueId(3),secretMatches:true});await noSecretLeak(page,second);});
test("metadata name edit and archive are separate from immutable value history",async({page})=>{const f=await fixture(page,{historyPaginated:true});await page.goto("/app/org/confidential");await page.getByRole("button",{name:"字段定义",exact:true}).click();await page.getByRole("button",{name:"修改字段",exact:true}).click();await expect(page.getByText("元数据并发修订 1；该计数器不是可恢复的历史版本。")).toBeVisible();await page.getByLabel("修改字段名称").fill("新的字段名称");await page.getByRole("button",{name:"保存字段名称",exact:true}).click();await expect(page.getByText("新的字段名称",{exact:true})).toBeVisible();expect(f.state.version).toBe(2);await page.getByRole("button",{name:"修改字段",exact:true}).click();await page.getByRole("button",{name:"归档字段",exact:true}).click();await expect(page.getByRole("dialog").filter({hasText:"起草和导出可能被阻止"})).toBeVisible();await page.getByRole("button",{name:"确认归档",exact:true}).click();await page.getByLabel("包含归档字段").check();await expect(page.getByText("已归档",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"填写新值",exact:true})).toHaveCount(0);await page.getByRole("button",{name:"修改字段",exact:true}).click();await page.getByRole("button",{name:"取消归档字段",exact:true}).click();expect(f.state.version).toBe(2);await page.getByRole("button",{name:"值历史",exact:true}).click();await page.getByRole("button",{name:"下一页值历史",exact:true}).click();await expect(page.getByRole("table",{name:"脱敏值历史"}).getByText("1",{exact:true})).toBeVisible();expect(f.queries.filter(q=>q.path.endsWith("history/query")).at(-1)).toMatchObject({cursor:"opaque-history",limit:25});expect(f.requests.some(req=>req.path.endsWith("/reveal"))).toBe(false);});
test("metadata conflict keeps only nonsecret draft",async({page})=>{const f=await fixture(page,{fieldConflict:true});await page.goto("/app/org/confidential");await page.getByRole("button",{name:"字段定义",exact:true}).click();await page.getByRole("button",{name:"修改字段",exact:true}).click();await page.getByLabel("修改字段名称").fill("保留名称草稿");await page.getByRole("button",{name:"保存字段名称",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"未保存名称已保留"})).toBeVisible();await expect(page.getByLabel("修改字段名称")).toHaveValue("保留名称草稿");expect(f.writes.length).toBe(1);await page.getByRole("button",{name:"保存字段名称",exact:true}).click();await expect.poll(()=>f.writes.length).toBe(2);expect(f.writes[1].expected_revision).toBe(2);});
test("new field key kind and scope are explicit and fixed",async({page})=>{const f=await fixture(page);await page.goto("/app/org/confidential");await page.getByRole("button",{name:"登记字段",exact:true}).click();await page.getByLabel("字段名称",{exact:true}).fill("联系人");await page.getByLabel("字段键名",{exact:true}).fill("contact_phone");await page.getByLabel("字段类别",{exact:true}).selectOption("contact");await page.getByLabel("字段范围",{exact:true}).selectOption("org");await page.getByRole("button",{name:"保存字段定义",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"已登记保密字段"})).toBeVisible();expect(f.writes[0]).toMatchObject({path:"/confidential-fields",key:"contact_phone",kind:"contact",scope:"org"});});
for(const role of ["technical","viewer"])test(`masked reader ${role} cannot define set or reveal`,async({page})=>{const f=await fixture(page,{role});await page.goto("/app/org/confidential");await expect(page.getByText("合成报价",{exact:true})).toBeVisible();for(const name of ["登记字段","填写新值","查看明文"])await expect(page.getByRole("button",{name,exact:true})).toHaveCount(0);await page.getByRole("button",{name:"值历史",exact:true}).click();await expect(page.getByRole("table",{name:"脱敏值历史"})).toBeVisible();expect(f.writes.length).toBe(0);});
test("explicit task scope CAS uses exact task owner",async({page})=>{const f=await fixture(page,{scope:"task",role:"admin"});await page.goto(`/app/org/confidential?task=${T}`);await expect(page.getByTestId("confidential-scope")).toContainText(T);await page.getByRole("button",{name:"填写新值",exact:true}).click();const canary=await typeSecret(page,f);await page.getByRole("button",{name:"保存新值",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"已保存保密值版本"})).toBeVisible();expect(f.writes[0]).toMatchObject({task_id:T,expected_value_id:valueId(2)});await noSecretLeak(page,canary);});
for(const options of [{taskRole:"reviewer"},{taskRole:"observer"},{role:"admin",taskRole:null},{taskArchived:true}])test(`task write denial ${options.taskRole??"nonmember"} ${!!options.taskArchived}`,async({page})=>{const f=await fixture(page,{scope:"task",...options});await page.goto(`/app/org/confidential?task=${T}`);await expect(page.getByText("合成报价",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"填写新值",exact:true})).toHaveCount(0);expect(f.writes.length).toBe(0);});
test("org-only page excludes task-owned values but retains definitions",async({page})=>{const f=await fixture(page,{scope:"task"});await page.goto("/app/org/confidential");await expect(page.getByText("没有符合条件的保密字段")).toBeVisible();await page.getByRole("button",{name:"字段定义",exact:true}).click();await expect(page.getByText("合成报价",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"填写新值",exact:true})).toHaveCount(0);expect(f.queries.every(q=>q.task_id===null)).toBe(true);});
test("live org role downgrade clears open entry before submit",async({page})=>{const f=await fixture(page);await page.goto("/app/org/confidential");await page.getByRole("button",{name:"填写新值",exact:true}).click();const canary=await typeSecret(page,f);f.state.role="viewer";await page.getByRole("button",{name:"保存新值",exact:true}).click();await expect(page.getByLabel("新的保密值",{exact:true})).toHaveCount(0);expect(f.writes.length).toBe(0);await noSecretLeak(page,canary);});
test("live task role downgrade clears open entry before submit",async({page})=>{const f=await fixture(page,{scope:"task"});await page.goto(`/app/org/confidential?task=${T}`);await page.getByRole("button",{name:"填写新值",exact:true}).click();const canary=await typeSecret(page,f);f.state.taskRole="observer";await page.getByRole("button",{name:"保存新值",exact:true}).click();await expect(page.getByLabel("新的保密值",{exact:true})).toHaveCount(0);expect(f.writes.length).toBe(0);await noSecretLeak(page,canary);});
for(const action of ["close","blur","hidden","org-reset"])test(`explicit reveal clears on ${action}`,async({page})=>{const f=await fixture(page);const canary=`synthetic-${randomUUID()}`;f.setCanary(canary);await page.goto("/app/org/confidential");expect(f.writes.length).toBe(0);await page.getByRole("button",{name:"查看明文",exact:true}).click();await expect(page.getByRole("dialog",{name:"查看保密值",exact:true})).toBeVisible();expect(await page.getByTestId("revealed-confidential-value").evaluate((node,value)=>node.textContent===value,canary),"Only explicit reveal displays a value").toBe(true);expect(f.writes.length).toBe(1);if(action==="close")await page.getByRole("button",{name:"关闭明文",exact:true}).click();else if(action==="blur")await page.evaluate(()=>window.dispatchEvent(new Event("blur")));else if(action==="hidden")await page.evaluate(()=>{Object.defineProperty(document,"hidden",{configurable:true,value:true});document.dispatchEvent(new Event("visibilitychange"));});else await page.evaluate(()=>window.dispatchEvent(new Event("bid:org-reset")));await expect(page.getByRole("dialog",{name:"查看保密值",exact:true})).toHaveCount(0);await noSecretLeak(page,canary);});
test("denied reveal clears cached identity without exposing response text",async({page})=>{const f=await fixture(page,{revealDenied:true});await page.goto("/app/org/confidential");await page.getByRole("button",{name:"查看明文",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"无权"})).toBeVisible();await expect(page.getByText("合成报价",{exact:true})).toHaveCount(0);expect(f.writes.length).toBe(1);});
test("close cancel and org switch discard transient entry",async({page})=>{const f=await fixture(page);await page.goto("/app/org/confidential");await page.getByRole("button",{name:"填写新值",exact:true}).click();const canary=await typeSecret(page,f);await page.getByRole("button",{name:"取消填写",exact:true}).click();await noSecretLeak(page,canary);await page.getByRole("button",{name:"填写新值",exact:true}).click();await typeSecret(page,f);await page.evaluate(()=>window.dispatchEvent(new Event("bid:org-reset")));await expect(page.getByRole("dialog")).toHaveCount(0);expect(f.writes.length).toBe(0);});
test("obsolete search and org reset discard late responses with two reads maximum",async({page})=>{const f=await fixture(page,{delay:true});await page.goto("/app/org/confidential");await page.getByLabel("搜索保密字段").fill("旧查询");await expect.poll(()=>f.queries.some(q=>q.q==="旧查询")).toBe(true);await page.getByLabel("搜索保密字段").fill("空结果");await expect(page.getByText("没有符合条件的保密字段")).toBeVisible();f.release();await page.evaluate(()=>window.dispatchEvent(new Event("bid:org-reset")));await expect(page.getByText("合成报价",{exact:true})).toHaveCount(0);expect(f.maxActive()).toBeLessThanOrEqual(2);});
for(const options of [{foreign:true},{raw:true},{oversize:true},{queryError:"management_result_too_large"},{queryError:"management_cursor_expired"},{taskDenied:true}])test(`inaccessible or malformed bounded projection ${options.queryError ?? Object.keys(options)[0]}`,async({page})=>{await fixture(page,options);await page.goto(options.taskDenied?`/app/org/confidential?task=${T}`:"/app/org/confidential");await expect(page.getByRole("alert")).toBeVisible();await expect(page.getByText("合成报价",{exact:true})).toHaveCount(0);});
test("narrow keyboard entry and navigation discard guard",async({page})=>{const f=await fixture(page);await page.setViewportSize({width:390,height:844});await page.goto("/app/org/confidential");await page.getByRole("button",{name:"登记字段",exact:true}).click();await page.getByLabel("字段名称",{exact:true}).fill("未保存定义");await page.getByLabel("字段名称",{exact:true}).press("Tab");await expect(page.getByLabel("字段键名",{exact:true})).toBeFocused();await page.getByRole("button",{name:"取消登记",exact:true}).click();await page.getByRole("button",{name:"填写新值",exact:true}).click();const canary=await typeSecret(page,f);await page.evaluate(()=>document.querySelector('a[href="/app/org/products"]')?.click());await expect(page.getByRole("dialog").filter({hasText:"放弃未保存编辑"})).toBeVisible();await page.getByRole("button",{name:"取消",exact:true}).last().click();await page.getByRole("button",{name:"取消填写",exact:true}).click();await noSecretLeak(page,canary);expect(f.writes.length).toBe(0);});
test("fixed built list meets actionable row budget",async({page},info)=>{await fixture(page);const started=performance.now();await page.goto("/app/org/confidential");await expect(page.getByRole("button",{name:"填写新值",exact:true})).toBeVisible();const elapsed=performance.now()-started;info.annotations.push({type:"measurement",description:JSON.stringify({first_actionable_ms:Math.round(elapsed),limit_ms:1500})});expect(elapsed).toBeLessThanOrEqual(1500);expect(await page.locator("table[aria-label='保密字段列表'] tbody tr").count()).toBeLessThanOrEqual(25);});

test("exact field filter survives twenty-five prefix label collisions",async({page})=>{const f=await fixture(page,{collisions:true});await page.goto("/app/org/confidential");await page.getByRole("button",{name:"填写新值",exact:true}).click();await blankSecret(page);const exact=f.queries.filter(q=>q.field_id===F);expect(exact.length).toBe(2);expect(exact.every(q=>q.q===null)).toBe(true);const canary=await typeSecret(page,f);await page.getByRole("button",{name:"保存新值",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"已保存保密值版本"})).toBeVisible();await noSecretLeak(page,canary);});

for(const action of ["navigation","logout"])test(`explicit reveal clears on ${action}`,async({page})=>{const f=await fixture(page);const canary=`synthetic-${randomUUID()}`;f.setCanary(canary);await page.goto("/app/org/confidential");await page.getByRole("button",{name:"查看明文",exact:true}).click();await expect(page.getByRole("dialog",{name:"查看保密值",exact:true})).toBeVisible();if(action==="logout")await page.getByRole("button",{name:"退出 / 切换单位",exact:true}).evaluate(button=>button.click());else await page.goto("/app/org/login");await expect(page).toHaveURL(/\/app\/org\/login/);if(action==="logout")expect(await page.evaluate(()=>sessionStorage.getItem("bid.org.session"))).toBeNull();await noSecretLeak(page,canary);expect(f.writes.length).toBe(1);});
test("network save outcome rereads and never automatically submits a second value",async({page})=>{const f=await fixture(page,{networkLoss:true});await page.goto("/app/org/confidential");await page.getByRole("button",{name:"填写新值",exact:true}).click();const first=await typeSecret(page,f);await page.getByRole("button",{name:"保存新值",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"结果未确定"})).toBeVisible();await expect(page.getByLabel("新的保密值",{exact:true})).toHaveCount(0);expect(f.writes.length).toBe(1);await noSecretLeak(page,first);await page.getByRole("button",{name:"填写新值",exact:true}).click();const second=await typeSecret(page,f);await page.getByRole("button",{name:"保存新值",exact:true}).click();await expect.poll(()=>f.writes.length).toBe(2);expect(f.writes[1].expected_value_id).toBe(valueId(3));await noSecretLeak(page,second);});
test("server write denial clears cached metadata and transient entry",async({page})=>{const f=await fixture(page,{mutationDenied:true});await page.goto("/app/org/confidential");await page.getByRole("button",{name:"填写新值",exact:true}).click();const canary=await typeSecret(page,f);await page.getByRole("button",{name:"保存新值",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"无权"})).toBeVisible();await expect(page.getByText("合成报价",{exact:true})).toHaveCount(0);await noSecretLeak(page,canary);expect(f.writes.length).toBe(1);});

test("thirty pages release old parsed arrays after explicit GC",async({page},info)=>{
  test.setTimeout(120_000);
  await page.addInitScript(()=>{
    window.__confidentialRetention={pages:0,transferred:0,refs:[]};
    const json=Response.prototype.json;
    Response.prototype.json=async function(...args){
      const payload=await json.apply(this,args);
      if(payload.command==="confidential browse"&&Array.isArray(payload.items)&&payload.data?.as_of){
        const tracker=window.__confidentialRetention,bytes=value=>new TextEncoder().encode(JSON.stringify(value)).length;
        tracker.pages++;tracker.transferred+=bytes(payload);
        tracker.refs.push({target:new WeakRef(payload.items),bytes:bytes(payload.items),array:true},{target:new WeakRef(payload.data),bytes:bytes(payload.data),array:false});
      }
      return payload;
    };
  });
  const pages=30;await fixture(page,{retentionPages:pages});await page.goto("/app/org/confidential");
  await expect(page.getByText("分页00-0",{exact:true})).toBeVisible();
  for(let index=1;index<pages;index++){
    await page.getByRole("button",{name:"下一页保密字段",exact:true}).click();
    await expect(page.getByText(`分页${String(index).padStart(2,"0")}-0`,{exact:true})).toBeVisible();
    await expect(page.getByText(`分页${String(index-1).padStart(2,"0")}-0`,{exact:true})).toHaveCount(0);
  }
  await expect(page.getByRole("button",{name:"下一页保密字段",exact:true})).toBeDisabled();
  const cdp=await page.context().newCDPSession(page);
  try{await cdp.send("HeapProfiler.collectGarbage");}finally{await cdp.detach();}
  const measured=await page.evaluate(()=>{
    const tracker=window.__confidentialRetention,live=tracker.refs.filter(item=>item.target.deref()!==undefined);
    return {page_responses:tracker.pages,transferred_page_bytes:tracker.transferred,retained_parsed_page_bytes:live.reduce((sum,item)=>sum+item.bytes,0),retained_page_arrays:live.filter(item=>item.array).length};
  });
  expect(measured.page_responses).toBe(pages);expect(measured.retained_parsed_page_bytes).toBeGreaterThan(0);expect(measured.retained_parsed_page_bytes).toBeLessThanOrEqual(2*1024*1024);expect(measured.retained_page_arrays).toBeLessThanOrEqual(1);
  expect(await page.locator("table[aria-label='保密字段列表'] tbody tr").count()).toBe(25);
  info.annotations.push({type:"measurement",description:JSON.stringify({...measured,fixture_pages:pages,rows_per_page:25,retained_limit_bytes:2*1024*1024,measurement:"WeakRef live parsed arrays and metadata after explicit GC"})});
});
