// Failure scenarios: foreign org/revision and unsafe provenance; unbounded or
// stale pages; authority loss; effective-history ownership; stale exact approval;
// active-edit withdrawal; conflict-key races; expiry; disabled reactivation;
// reason disclosure; invented feedback; dispatch failure; unknown write outcome.
import {cosignFixture,ids as reviewIds} from "./cosign-fixture.js";
import {result as reviewResult,uuid as reviewUuid} from "./assessment-fixture.js";
import {test,expect} from "@playwright/test";
import {createHash} from "node:crypto";
import {existsSync,mkdirSync,readFileSync,realpathSync,writeFileSync} from "node:fs";
import {basename,dirname,extname,join,relative,resolve} from "node:path";
import {fileURLToPath} from "node:url";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"../.."),work=join(root,"data/work"),base=resolve(process.env.E2E_OUTPUT??join(work,"management-pages-validation/browser")),output=join(base,"memory");
const inside=(parent,path)=>{const rel=relative(parent,path);return rel!==".."&&!rel.startsWith("../")&&!rel.startsWith("/");};
if(!inside(join(work,"management-pages-validation"),base))throw new Error("E2E_OUTPUT must be inside data/work/management-pages-validation");
let ancestor=output;while(!existsSync(ancestor))ancestor=dirname(ancestor);if(!inside(realpathSync(root),realpathSync(ancestor)))throw new Error("Artifact path resolves outside worktree");
process.env.PLAYWRIGHT_JSON_OUTPUT_NAME??=join(output,"playwright-report.json");
const staticDir=process.env.E2E_STATIC_DIR?resolve(process.env.E2E_STATIC_DIR):null;
if(staticDir&&(!inside(root,staticDir)||!existsSync(staticDir)||!inside(realpathSync(root),realpathSync(staticDir))))throw new Error("E2E_STATIC_DIR must resolve inside the worktree");
const O="00000000-0000-0000-0000-000000000002",U="00000000-0000-0000-0000-000000000003",T="00000000-0000-0000-0000-000000000001",M="00000000-0000-0000-0000-000000000010",F="00000000-0000-0000-0000-000000000011",J="00000000-0000-0000-0000-000000000012",C="00000000-0000-0000-0000-000000000013",OTHER="00000000-0000-0000-0000-000000000014";
const rid=n=>`00000000-0000-0000-0000-${String(100+n).padStart(12,"0")}`,date="2026-10-06T00:00:00Z",hash="a".repeat(64);
const cost={llm_tokens:0,ocr_pages:0,usd:0,basis:"zero",charge:"0",billing_currency:"USD",task_amount:"0",unpriced_calls:0,unresolved_calls:0};
const result=(command,data={},items=[],ok=true)=>({ok,command,data,items,warnings:[],cost,duration_ms:0});
const records=[],scenarios=[],health=new WeakMap();function scenario(name,fn){scenarios.push(name);test(name,fn);}
test.beforeEach(async({page},info)=>{const errors=[];health.set(page,errors);page.on("pageerror",e=>errors.push(e.message));page.on("console",m=>{if(["error","warning"].includes(m.type())&&!m.text().startsWith("Failed to load resource"))errors.push(m.text());});if(!info.title.startsWith("card decision"))await page.addInitScript(({O,U})=>sessionStorage.setItem("bid.org.session",JSON.stringify({session:"synthetic-memory-session",orgId:O,userId:U,orgName:"合成记忆验收单位"})),{O,U});if(staticDir)await page.route(url=>url.pathname.startsWith("/app/"),route=>{const pathname=new URL(route.request().url()).pathname,file=pathname.startsWith("/app/assets/")?join(staticDir,"assets",basename(pathname)):join(staticDir,"index.html");return route.fulfill({contentType:{".html":"text/html",".js":"text/javascript",".css":"text/css"}[extname(file)]??"application/octet-stream",body:readFileSync(file)});});});
test.afterEach(async({page},info)=>{mkdirSync(output,{recursive:true});if(!inside(realpathSync(work),realpathSync(output)))throw new Error("Artifact symlink escapes data/work");const errors=health.get(page)??[],overlay=await page.locator("vite-error-overlay").count();if(info.status==="passed"&&!errors.length&&!overlay)await page.screenshot({path:join(output,`${info.title.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}.png`),fullPage:true});records.push({scenario:info.title,status:info.status==="passed"&&(errors.length||overlay)?"failed":info.status,console_errors:errors.length,framework_overlay:overlay,measurements:info.annotations.filter(a=>a.type==="measurement").map(a=>JSON.parse(a.description))});const index=staticDir?join(staticDir,"index.html"):existsSync(join(root,"web/dist/index.html"))?join(root,"web/dist/index.html"):null;if(index&&!inside(realpathSync(root),realpathSync(index)))throw new Error("Build artifact resolves outside worktree");writeFileSync(join(output,"result.json"),JSON.stringify({mode:"mocked_api",fixture_version:"memory-management-v1",schema_version:"4.0",browser:"chromium",browser_version:page.context().browser()?.version()??null,build_sha256:index?createHash("sha256").update(readFileSync(index)).digest("hex"):null,base_url:process.env.E2E_BASE_URL??null,command:'cd web && E2E_BASE_URL=http://127.0.0.1:8000 E2E_STATIC_DIR="$PWD/dist" E2E_OUTPUT=../data/work/management-pages-validation/browser node_modules/.bin/playwright test e2e/memory-management.spec.js --reporter=list,json',schema_assertion_summary:{envelope_keys:Object.keys(result("schema")),cost_keys:Object.keys(cost),checked_via:"api.js Result 4 parser and memory org/revision/source/page validators",scenario_results:records.map(({scenario,status})=>({scenario,status}))},permission_assertion_summary:records.filter(r=>/authority|owner|foreign|archived/.test(r.scenario)).map(({scenario,status})=>({scenario,status})),expected_scenarios:scenarios.length,complete:records.length===scenarios.length,scenarios:records,passed:records.length===scenarios.length&&records.every(r=>r.status==="passed")},null,2));expect(errors,"Unexpected browser runtime or console error").toEqual([]);expect(overlay).toBe(0);});

async function fixture(page,options={}){
 const state={role:"admin",head:1,status:"candidate",taskRole:"owner",own:true,everActive:false,jobStatus:"queued",...options},writes=[],reads=[],queries=[];let release=null;
 const storedStatus=n=>n===state.head?state.status:state.historicalActive?"active":"candidate";
 const revision=(n=state.head,memoryId=M)=>({id:rid(n),org_id:state.foreign?OTHER:O,memory_id:memoryId,revision:n,target:{scope:"org"},content:{kind:"rule",conflict_key:"source.review",text:state.largeText?"规则".repeat(900):n===1?"先核对真实来源，再编写响应。":state.text??"更新后的规则",tags:["review"]},status:storedStatus(n),source:state.redacted?{origin:"human",provenance_redacted:true}:{origin:"human"},content_sha256:hash,created_at:date,created_by:state.own?U:OTHER,actor_kind:"session",confirmed_by:storedStatus(n)==="active"?U:null,confirmed_at:storedStatus(n)==="active"?date:null,decision:storedStatus(n)==="active"?"approve":state.status==="disabled"&&n===state.head?"reject":null,decision_reason_sha256:n>1?hash:null,expires_at:state.expired?"2026-01-01T00:00:00Z":null});
 const memory=(n=state.head,memoryId=M)=>({id:memoryId,org_id:state.foreign?OTHER:O,current:revision(n,memoryId),effective_status:n===state.head&&state.expired&&state.status==="active"?"expired":storedStatus(n),deleted_at:null});
 const actions=n=>["revise","approve","reject","disable"].map(action=>{const allowed=n===state.head&&(action==="revise"?(state.role==="admin"||state.role!=="viewer"&&state.own&&!state.everActive&&state.status==="candidate"):state.role==="admin"&&((action==="approve"||action==="reject")?state.status==="candidate":state.status!=="disabled"));return {action,allowed,...(allowed?{}:{reason:"role_or_state_required"})};});
 const meta=(items,next=null)=>({org_id:O,as_of:date,returned:items.length,next_cursor:next,has_more:next!==null});
 const event=()=>({id:F,org_id:O,task_id:T,card_id:C,before_revision_id:rid(8),after_revision_id:rid(9),actor_user_id:U,actor_kind:"session",kind:state.confirmed?"card_confirmed":"card_rejected",review_domain:"technical",created_at:date,sanitized_sha256:hash,sanitizer_version:"feedback-v1",candidate_job_id:state.confirmed||state.noJob?null:J,candidate_job_status:state.jobStatus,candidate_event_ids:state.confirmed||state.noJob?[]:[F],candidate_memory_id:state.jobStatus==="succeeded"?M:null});
 await page.route(url=>!url.pathname.startsWith("/app/"),async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname.replace(/^\/v4(?=\/)/,"");reads.push({path,method:req.method()});const send=(command,data={},items=[])=>route.fulfill({json:result(command,data,items)});const fail=(code,status=409,data={})=>route.fulfill({status,json:result("memory error",{error:{code,message:code,exit_code:status===503?3:2},...data},[],false)});
 if(path==="/org/current")return send("org current",{org_id:O,user_id:U,role:state.role});
 if(path==="/management/memories/query"){const body=req.postDataJSON();queries.push(body);if(state.queryDenied)return fail("forbidden",state.queryDenied);if(state.delay)await new Promise(resolve=>{release=resolve;});if(state.cursorError&&body.cursor)return fail("management_cursor_expired");if(state.oversize)return fail("management_result_too_large",413);const p=Number(body.cursor?.split("-").at(-1)??1),items=body.q==="无匹配"?[]:state.pages?Array.from({length:25},(_,i)=>memory(1,rid(1000+p*25+i))):[memory()];return send("memory browse",meta(items,state.pages&&p<state.pages?`memory-page-${p+1}`:null),items);}
 if(path===`/management/memories/${M}`){if(state.headDenied)return fail("forbidden",state.headDenied);const n=Number(url.searchParams.get("revision")??state.head);return send("memory show",{memory:memory(n),current_revision:state.head,current_effective_status:memory().effective_status,revised_at:date,revised_by:state.unknownEditor?null:U,as_of:date,actions:actions(n)});}
 if(path===`/management/memories/${M}/history/query`){queries.push(req.postDataJSON());if(state.historyDenied)return fail("forbidden",state.historyDenied);const items=Array.from({length:state.head},(_,i)=>revision(state.head-i));return send("memory history",meta(items),items);}
 if(path==="/memories"&&req.method()==="POST"){const body=req.postDataJSON();writes.push({path,body});expect(body.target).toEqual({scope:"org"});expect(body).not.toHaveProperty("status");state.text=body.content.text;if(state.createNetwork){state.createNetwork=false;return route.abort("failed");}return send("memory add",{memory:memory()});}
 if(path===`/memories/${M}`&&req.method()==="PUT"){const body=req.postDataJSON();writes.push({path,body});if(state.denied)return fail("forbidden",403);if(state.network){state.network=false;state.head++;return route.abort("failed");}if(state.conflict){state.conflict=false;state.head++;return fail("memory_revision_conflict");}if(state.sensitive)return fail("memory_sensitive_value",400);expect(body.expected_revision).toBe(state.head);state.head++;state.status="candidate";state.text=body.content.text;return send("memory update",{memory:memory()});}
 if(path===`/memories/${M}/decisions`||path===`/memories/${M}/disable`){const body=req.postDataJSON();writes.push({path,body});expect(body.reason.trim()).not.toBe("");if(state.conflict){state.conflict=false;state.head++;return fail("memory_revision_conflict");}if(state.keyConflict)return fail("memory_conflict_key");expect(body.expected_revision).toBe(state.head);state.head++;state.status=path.endsWith("disable")||body.action==="reject"?"disabled":"active";state.everActive=state.status==="active"||state.everActive;return send("memory decision",{memory:memory()});}
 if(path===`/tasks/${T}/workflow`)return state.taskDenied?fail("not_found",404):send("task workflow",{workflow:{org_id:O,task_id:T,state:state.archived?"archived":"active",revision:1,owner_user_id:U}});
 if(path===`/tasks/${T}/members`){const items=state.taskRole?[{org_id:O,task_id:T,user_id:U,role:state.taskRole,active:true,revision:1,review_domains:["technical"]}]:[];return send("task members",{...meta(items),task_id:T},items);}
 if(path===`/tasks/${T}/memory-feedback`){expect(url.searchParams.get("management")).toBe("true");return send("memory feedback list",meta([event()]),[event()]);}
 if(path===`/jobs/${J}`){const value={id:J,kind:"memory_candidate",status:state.jobStatus,error:state.jobStatus==="failed"?{code:"job_failed",exit_code:4}:null,attempts:0,reasoning:null,result:state.jobStatus==="succeeded"?{completion:state.partial?"partial":"complete",items:[{event_id:F,outcome:"created",memory_id:M}]}:{}};const response=result("job status",value,[],!["failed","cancelled"].includes(state.jobStatus)&&!state.partial);return route.fulfill({json:response});}
 if(path===`/tasks/${T}/memory-candidates`){const body=req.postDataJSON();writes.push({path,body});expect(body).toEqual({event_ids:[F],action:{retry:true}});if(state.dispatchFail)return fail("queue_unavailable",503,{job_id:J});state.jobStatus="succeeded";return send("memory candidates run",{job_id:J,task_id:T,reused:true,dry_run:false,event_count:1});}
 if(req.method()==="GET"&&path==="/health")return route.fulfill({json:{ok:true,command:"health",data:{status:"ok",version:"4.0",real_llm_configured:false,org_signup_enabled:false},items:[],warnings:[],cost:{llm_tokens:0,ocr_pages:0,usd:0},duration_ms:0}});
 throw new Error(`Unexpected memory request ${req.method()} ${path}`);
 });return {state,writes,reads,queries,release:()=>release?.()};
}
const detail=`/app/org/memory/${M}`,queue=`/app/org/tasks/${T}/memory-feedback`;
async function decide(page){await page.getByLabel("我已核对本精确修订的内容、冲突键、来源与有效期").check();await page.getByLabel("操作原因",{exact:true}).fill("人工核对过规则");await page.getByRole("button",{name:/审核通过修订/}).click();await page.getByRole("button",{name:"确认决定",exact:true}).click();}
scenario("bounded prefix browse filters private storage",async({page})=>{const f=await fixture(page);await page.goto("/app/org/memory");await expect(page.getByRole("heading",{name:"单位记忆",exact:true})).toBeVisible();await page.getByLabel("搜索记忆",{exact:true}).fill("无匹配");await expect(page.getByText("没有符合条件的记忆")).toBeVisible();await page.getByLabel("包含全部标签").fill("review, source");await expect.poll(()=>f.queries.at(-1)?.tags).toEqual(["review","source"]);expect(f.queries.at(-1)).toMatchObject({scope:"org",q:"无匹配",limit:25,cursor:null,include_deleted:false});expect(f.reads.some(r=>r.path==="/memories"&&r.method==="GET")).toBe(false);expect(await page.evaluate(()=>JSON.stringify({...sessionStorage,...localStorage}))).not.toContain("无匹配");});
scenario("creation always candidate no deletion UI",async({page})=>{const f=await fixture(page);await page.goto("/app/org/memory");await page.getByRole("button",{name:"新增候选记忆"}).click();await page.getByLabel("冲突键",{exact:true}).fill("source.review");await page.getByLabel("记忆正文").fill("先核对原件");await page.getByRole("button",{name:"保存候选记忆"}).click();await expect(page.getByRole("status").filter({hasText:"已创建候选"})).toBeVisible();expect(f.writes).toHaveLength(1);await expect(page.getByRole("button",{name:/删除|恢复记忆/})).toHaveCount(0);});
scenario("creation unknown outcome preserves draft until explicit reread acknowledgement",async({page})=>{const f=await fixture(page,{createNetwork:true});await page.goto("/app/org/memory");await page.getByRole("button",{name:"新增候选记忆"}).click();await page.getByLabel("冲突键",{exact:true}).fill("source.review");await page.getByLabel("记忆正文").fill("保留未确定保存的候选草稿");await page.getByRole("button",{name:"保存候选记忆"}).click();await expect(page.getByRole("status").filter({hasText:"保存结果尚未确定，草稿已保留"})).toBeVisible();await expect(page.getByLabel("记忆正文")).toHaveValue("保留未确定保存的候选草稿");await expect(page.getByRole("button",{name:"保存候选记忆"})).toBeDisabled();const acknowledge=page.getByRole("button",{name:"已核对记录，允许再次提交",exact:true});await expect(acknowledge).toBeDisabled();expect(f.queries).toHaveLength(1);expect(f.writes).toHaveLength(1);await page.getByRole("button",{name:"重新读取并核对未确定保存"}).click();await expect(acknowledge).toBeEnabled();expect(f.queries.at(-1)).toMatchObject({q:"source.review",kind:"rule",status:"candidate",expiry:"all",tags:[],cursor:null});await expect(page.getByRole("status").filter({hasText:"保存结果尚未确定，草稿已保留"})).toBeVisible();await expect(page.getByRole("button",{name:"保存候选记忆"})).toBeDisabled();await acknowledge.click();await page.getByRole("dialog").getByRole("button",{name:"允许再次提交",exact:true}).click();await expect(page.getByRole("button",{name:"保存候选记忆"})).toBeEnabled();expect(f.writes).toHaveLength(1);await page.getByRole("button",{name:"保存候选记忆"}).click();await expect(page.getByRole("status").filter({hasText:"已创建候选"})).toBeVisible();expect(f.writes).toHaveLength(2);});
for(const role of ["bidder","technical","viewer"])scenario(`memory authority ${role} own candidate`,async({page})=>{const f=await fixture(page,{role});await page.goto(detail);await expect(page.getByRole("heading",{name:"source.review",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"编辑为候选"})).toHaveCount(role==="viewer"?0:1);await expect(page.getByRole("button",{name:/审核通过|驳回并停用|停用记忆/})).toHaveCount(0);expect(f.writes).toHaveLength(0);});
scenario("other owner and ever effective candidate deny nonadmin edit",async({page})=>{const f=await fixture(page,{role:"technical",own:false});await page.goto(detail);await expect(page.getByRole("button",{name:"编辑为候选"})).toHaveCount(0);f.state.own=true;f.state.everActive=true;await page.reload();await expect(page.getByRole("button",{name:"编辑为候选"})).toHaveCount(0);});
scenario("exact approval revision and reasons hash only",async({page})=>{const f=await fixture(page);await page.goto(detail);const approve=page.getByRole("button",{name:"审核通过修订 1"});await expect(approve).toBeDisabled();await decide(page);await expect(page.getByRole("status").filter({hasText:"已保存修订 2"})).toBeVisible();expect(f.writes.at(-1).body).toMatchObject({expected_revision:1,action:"approve",reason:"人工核对过规则"});await expect(page.getByLabel("记忆修订历史")).toContainText(hash);expect(await page.locator("body").innerText()).not.toContain("人工核对过规则");expect(await page.evaluate(()=>JSON.stringify({...sessionStorage,...localStorage}))).not.toContain("人工核对过规则");});
scenario("historical exact revision no mutations",async({page})=>{const f=await fixture(page,{head:2,status:"active"});await page.goto(`${detail}?revision=1`);await expect(page.getByText("规则 · 当前展示修订 1 · 服务器最新修订 2")).toBeVisible();await expect(page.getByRole("button",{name:"编辑为候选"})).toHaveCount(0);await expect(page.getByRole("button",{name:/审核通过|驳回并停用/})).toHaveCount(0);expect(f.reads.some(r=>r.path===`/management/memories/${M}`)).toBe(true);});
scenario("historical active revision distinguishes current withdrawn candidate",async({page})=>{await fixture(page,{head:2,status:"candidate",historicalActive:true});await page.goto(`${detail}?revision=1`);await expect(page.getByRole("status").filter({hasText:"历史修订已被取代，不代表当前生效内容"})).toBeVisible();const stored=page.locator("dt").filter({hasText:/^存储状态$/}),effective=page.locator("dt").filter({hasText:/^服务器当前生效状态$/});await expect(stored.locator("xpath=following-sibling::dd[1]")).toHaveText("已生效");await expect(effective.locator("xpath=following-sibling::dd[1]")).toContainText("候选，待管理员审核");await expect(page.getByRole("button",{name:"编辑为候选"})).toHaveCount(0);await expect(page.getByRole("button",{name:/审核通过|驳回并停用/})).toHaveCount(0);});
scenario("approval race clears checks no automatic retry",async({page})=>{const f=await fixture(page,{conflict:true});await page.goto(detail);await decide(page);await expect(page.getByRole("alert").filter({hasText:/审核勾选已清除/})).toBeVisible();await expect(page.getByLabel("我已核对本精确修订的内容、冲突键、来源与有效期")).not.toBeChecked();expect(f.writes).toHaveLength(1);});
scenario("same kind conflict key requires human decision",async({page})=>{const f=await fixture(page,{keyConflict:true});await page.goto(detail);await decide(page);await expect(page.getByRole("alert").filter({hasText:/管理员决定保留哪一项/})).toBeVisible();expect(f.writes).toHaveLength(1);await expect(page.getByLabel("我已核对本精确修订的内容、冲突键、来源与有效期")).not.toBeChecked();});
scenario("active edit announces immediate withdrawal then candidate",async({page})=>{const f=await fixture(page,{status:"active"});await page.goto(detail);await page.getByRole("button",{name:"编辑为候选"}).click();await expect(page.getByRole("alert").filter({hasText:"保存会立即撤下原生效内容"})).toBeVisible();await page.getByLabel("记忆正文").fill("更新后的来源规则");await page.getByRole("button",{name:"保存候选记忆"}).click();await expect(page.getByRole("status").filter({hasText:"候选，待管理员审核"})).toBeVisible();expect(f.writes.at(-1).body.expected_revision).toBe(1);expect(f.state.status).toBe("candidate");});
scenario("disabled requires edited candidate before human approval",async({page})=>{const f=await fixture(page,{status:"disabled"});await page.goto(detail);await expect(page.getByRole("button",{name:/审核通过/})).toHaveCount(0);await expect(page.getByText("重新启用必须先编辑为候选，再经管理员审核通过。")).toBeVisible();await page.getByRole("button",{name:"编辑为候选"}).click();await page.getByLabel("记忆正文").fill("改正后的规则");await page.getByRole("button",{name:"保存候选记忆"}).click();await decide(page);expect(f.writes.map(w=>w.body.action??"edit")).toEqual(["edit","approve"]);});
scenario("reject creates disabled and keeps hash history",async({page})=>{const f=await fixture(page);await page.goto(detail);await page.getByLabel("操作原因",{exact:true}).fill("规则不适用");await page.getByRole("button",{name:"驳回并停用"}).click();await page.getByRole("button",{name:"确认决定",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"已停用"})).toBeVisible();expect(f.state.status).toBe("disabled");});
scenario("server expiry distinct from stored active",async({page})=>{await fixture(page,{status:"active",expired:true});await page.addInitScript(()=>{Date.now=()=>0;});await page.goto(detail);await expect(page.getByText("存储仍是 active；服务器判断已过期，当前不生效。编辑为候选后须重新审核。")).toBeVisible();await expect(page.getByRole("button",{name:/审核通过/})).toHaveCount(0);});
scenario("redacted inaccessible provenance has no source identifiers",async({page})=>{await fixture(page,{redacted:true});await page.goto(detail);await expect(page.getByText("任务来源不可访问，来源标识已隐藏。")).toBeVisible();await expect(page.getByRole("link",{name:/来源任务/})).toHaveCount(0);expect(await page.locator("body").innerText()).not.toContain(T);});
scenario("foreign org projection blocked before rendering",async({page})=>{await fixture(page,{foreign:true});await page.goto(detail);await expect(page.getByRole("alert").filter({hasText:/范围或响应边界/})).toBeVisible();await expect(page.getByRole("heading",{name:"source.review",exact:true})).toHaveCount(0);});
scenario("safety correction does not suggest redaction off",async({page})=>{const f=await fixture(page,{sensitive:true});await page.goto(detail);await page.getByRole("button",{name:"编辑为候选"}).click();await page.getByLabel("记忆正文").fill("需要改正的提案");await page.getByRole("button",{name:"保存候选记忆"}).click();await expect(page.getByRole("alert").filter({hasText:/移除敏感信息/})).toBeVisible();expect(await page.locator("body").innerText()).not.toMatch(/关闭遮挡|禁用遮挡|关闭脱敏/);await expect(page.getByLabel("记忆正文")).toHaveValue("需要改正的提案");expect(f.writes).toHaveLength(1);});
scenario("edit conflict retains unsaved text and requires deliberate save",async({page})=>{const f=await fixture(page,{conflict:true});await page.goto(detail);await page.getByRole("button",{name:"编辑为候选"}).click();await page.getByLabel("记忆正文").fill("本地未保存提案");await page.getByRole("button",{name:"保存候选记忆"}).click();await expect(page.getByLabel("记忆正文")).toHaveValue("本地未保存提案");await expect(page.getByRole("button",{name:"保存候选记忆"})).toBeDisabled();await page.getByRole("button",{name:"已核对服务器修订，继续保留草稿"}).click();await page.getByRole("button",{name:"保存候选记忆"}).click();expect(f.writes.map(w=>w.body.expected_revision)).toEqual([1,2]);});
scenario("network save outcome requires reread no retry",async({page})=>{const f=await fixture(page,{network:true});await page.goto(detail);await page.getByRole("button",{name:"编辑为候选"}).click();await page.getByRole("button",{name:"保存候选记忆"}).click();await expect(page.getByRole("alert").filter({hasText:/操作结果尚未确定/})).toBeVisible();expect(f.writes).toHaveLength(1);await expect(page.getByRole("button",{name:"保存候选记忆"})).toBeDisabled();});
scenario("revoked authority clears memory content and draft",async({page})=>{const f=await fixture(page,{denied:true});await page.goto(detail);await page.getByRole("button",{name:"编辑为候选"}).click();await page.getByLabel("记忆正文").fill("必须清除的草稿");await page.getByRole("button",{name:"保存候选记忆"}).click();await expect(page.getByLabel("记忆正文")).toHaveCount(0);expect(await page.locator("body").innerText()).not.toContain("必须清除的草稿");expect(f.writes).toHaveLength(1);});
for(const status of [403,404]){
scenario(`list authority loss ${status} clears cached rows and create draft`,async({page})=>{const f=await fixture(page);await page.goto("/app/org/memory");await expect(page.getByLabel("记忆列表")).toBeVisible();await page.getByRole("button",{name:"新增候选记忆"}).click();await page.getByLabel("冲突键",{exact:true}).fill("draft.clear");await page.getByLabel("记忆正文").fill("列表失权必须清除的草稿");f.state.queryDenied=status;await page.getByRole("button",{name:"重新读取记忆",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:status===404?"不可访问":"当前角色无权执行此操作"})).toBeVisible();await expect(page.getByLabel("记忆正文")).toHaveCount(0);await expect(page.getByLabel("记忆列表")).not.toBeVisible();expect(await page.locator("body").innerText()).not.toContain("列表失权必须清除的草稿");expect(f.writes).toHaveLength(0);});
scenario(`history authority loss ${status} clears detail and edit draft`,async({page})=>{const f=await fixture(page);await page.goto(detail);await page.getByRole("button",{name:"编辑为候选"}).click();await page.getByLabel("记忆正文").fill("历史失权必须清除的草稿");f.state.historyDenied=status;await page.getByRole("button",{name:"从第一页读取历史",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:status===404?"不可访问":"当前角色无权执行此操作"})).toBeVisible();await expect(page.getByLabel("记忆正文")).toHaveCount(0);await expect(page.getByRole("heading",{name:"source.review",exact:true})).toHaveCount(0);expect(await page.locator("body").innerText()).not.toContain("历史失权必须清除的草稿");expect(f.writes).toHaveLength(0);});
scenario(`conflict recovery authority loss ${status} clears retained draft`,async({page})=>{const f=await fixture(page,{conflict:true});await page.goto(detail);await page.getByRole("button",{name:"编辑为候选"}).click();await page.getByLabel("记忆正文").fill("冲突重新读取失权必须清除的草稿");f.state.headDenied=status;await page.getByRole("button",{name:"保存候选记忆"}).click();await expect(page.getByRole("alert").filter({hasText:status===404?"不可访问":"当前角色无权执行此操作"})).toBeVisible();await expect(page.getByLabel("记忆正文")).toHaveCount(0);await expect(page.getByRole("heading",{name:"source.review",exact:true})).toHaveCount(0);expect(await page.locator("body").innerText()).not.toContain("冲突重新读取失权必须清除的草稿");expect(f.writes).toHaveLength(1);});
}
scenario("saved dispatch job explicit exact events recovery and candidate link",async({page})=>{const f=await fixture(page,{dispatchFail:true});await page.goto(`${queue}?job=${J}`);await expect(page.getByRole("heading",{name:"已保存候选作业"})).toBeVisible();await page.getByRole("button",{name:"恢复已保存作业",exact:true}).click();await page.getByRole("dialog",{name:"恢复候选作业"}).getByRole("button",{name:"确认恢复作业",exact:true}).click();await expect(page.getByRole("status").filter({hasText:/人工卡片决定已保存/})).toBeVisible();expect(f.writes).toHaveLength(1);expect(f.writes[0].body).toEqual({event_ids:[F],action:{retry:true}});f.state.dispatchFail=false;await page.getByRole("button",{name:"恢复已保存作业",exact:true}).click();await page.getByRole("dialog",{name:"恢复候选作业"}).getByRole("button",{name:"确认恢复作业",exact:true}).click();await expect(page.getByRole("link",{name:"核对生成候选",exact:true})).toBeVisible();expect(f.writes).toHaveLength(2);expect(f.writes.every(w=>w.path.endsWith("memory-candidates"))).toBe(true);});
scenario("card decision persists on candidate dispatch failure",async({page})=>{
 if(!process.env.E2E_STATIC_DIR)process.env.E2E_STATIC_DIR=join(root,"web/dist");
 const f=await cosignFixture(page,{required:false}),savedJob=reviewUuid(200),actions=[];
 await page.route(url=>url.pathname===`/cards/${reviewIds.card}/actions`,async route=>{const body=route.request().postDataJSON();actions.push(body);expect(body.action).toBe("reject");expect(body.expected_revision).toBe(f.card.revision);f.card.revision++;f.card.state="rejected";f.card.reason=body.reason;f.card.eligibility="unconfirmed";return route.fulfill({json:reviewResult("card action",structuredClone(f.card),[],{warnings:[`memory_candidate_dispatch_pending:${savedJob}`]})});});
 await page.goto(`/app/org/tasks/${reviewIds.task}/review?job=${reviewIds.extract}&requirement=${reviewIds.requirement}`);
 await expect(page.getByRole("button",{name:"驳回",exact:true})).toBeVisible();await page.getByRole("textbox",{name:"操作原因 / 警示处理理由",exact:true}).fill("需要重新核对真实来源");await page.getByRole("button",{name:"驳回",exact:true}).click();await page.getByRole("dialog").getByRole("button",{name:"确定",exact:true}).click();
 await expect(page.getByRole("status").filter({hasText:"人工卡片决定已保存"})).toBeVisible();await expect(page.getByRole("link",{name:"查看已保存作业并恢复派发"})).toHaveAttribute("href",`/app/org/tasks/${reviewIds.task}/memory-feedback?job=${savedJob}`);expect(f.card.state).toBe("rejected");expect(actions).toHaveLength(1);expect(f.base.requests.some(request=>request.path.endsWith("memory-candidates"))).toBe(false);f.verify();
});
scenario("recorded failed partial job readable with result candidates",async({page})=>{const f=await fixture(page,{jobStatus:"succeeded",partial:true});await page.goto(`${queue}?job=${J}`);await expect(page.getByRole("status").filter({hasText:/部分完成/})).toBeVisible();await expect(page.getByRole("link",{name:"核对生成候选",exact:true})).toBeVisible();expect(f.writes).toHaveLength(0);});
scenario("failed recorded job remains visible for deliberate recovery",async({page})=>{const f=await fixture(page,{jobStatus:"failed"});await page.goto(`${queue}?job=${J}`);await expect(page.getByText("失败代码：job_failed")).toBeVisible();await expect(page.getByRole("button",{name:"恢复已保存作业",exact:true})).toBeVisible();expect(f.writes).toHaveLength(0);});
for(const taskRole of ["reviewer","observer",null])scenario(`feedback task authority ${taskRole??"nonmember"} read without recovery`,async({page})=>{await fixture(page,{taskRole});await page.goto(`${queue}?job=${J}`);await expect(page.getByRole("button",{name:"恢复已保存作业",exact:true})).toHaveCount(0);});
scenario("archived feedback read only",async({page})=>{await fixture(page,{archived:true});await page.goto(`${queue}?job=${J}`);await expect(page.getByText("任务已归档，只读历史，无法恢复作业。")).toBeVisible();await expect(page.getByRole("button",{name:"恢复已保存作业",exact:true})).toHaveCount(0);});
scenario("confirmation only evaluation no invented candidate or event",async({page})=>{const f=await fixture(page,{confirmed:true});await page.goto(queue);await expect(page.getByText("仅评价样本，无候选作业")).toBeVisible();await expect(page.getByRole("button",{name:/生成候选|恢复已保存作业|新增反馈|编辑事件/})).toHaveCount(0);expect(f.writes).toHaveLength(0);});
scenario("foreign inaccessible task unavailable before feedback query",async({page})=>{const f=await fixture(page,{taskDenied:true});await page.goto(queue);await expect(page.getByRole("alert").filter({hasText:"不可访问"})).toBeVisible();expect(f.reads.some(r=>r.path.endsWith("memory-feedback"))).toBe(false);});
scenario("cursor expiry and oversize report failure with no truncated rows",async({page})=>{const f=await fixture(page,{pages:2,cursorError:true});await page.goto("/app/org/memory");await page.getByRole("button",{name:"下一页记忆"}).click();await expect(page.getByRole("alert").filter({hasText:/分页已过期/})).toBeVisible();await expect(page.getByRole("button",{name:"上一页记忆"})).toBeDisabled();f.state.oversize=true;await page.getByRole("button",{name:"重新读取记忆"}).click();await expect(page.getByRole("alert").filter({hasText:/结果超过显示上限/})).toBeVisible();await expect(page.getByLabel("记忆列表")).not.toBeVisible();});
scenario("org reset cancels late list response and clears data",async({page})=>{const f=await fixture(page,{delay:true});await page.goto("/app/org/memory");await expect.poll(()=>f.queries.length).toBe(1);await page.evaluate(()=>window.dispatchEvent(new Event("bid:org-reset")));f.release();await expect(page.getByText("先核对真实来源，再编写响应。")).toHaveCount(0);});
scenario("bounded pages evict previous arrays after explicit GC",async({page},info)=>{const f=await fixture(page,{pages:60,largeText:true});test.setTimeout(120_000);const cdp=await page.context().newCDPSession(page);await cdp.send("Runtime.enable");await page.addInitScript(()=>{window.memoryRetained={refs:[],transferred:0};const original=Response.prototype.json;Response.prototype.json=async function(){const value=await original.call(this);if(this.url.includes("/management/memories/query")){window.memoryRetained.transferred+=new TextEncoder().encode(JSON.stringify(value)).length;for(const data of [value.items,value.data])window.memoryRetained.refs.push({target:new WeakRef(data),bytes:new TextEncoder().encode(JSON.stringify(data)).length});}return value;};});await page.goto("/app/org/memory");await expect(page.getByLabel("记忆列表")).toBeVisible();for(let p=2;p<=60;p++){await page.getByRole("button",{name:"下一页记忆"}).click();await expect.poll(()=>f.queries.length).toBe(p);await expect(page.getByLabel("记忆列表")).toBeVisible();}await cdp.send("HeapProfiler.collectGarbage");await cdp.send("HeapProfiler.collectGarbage");const measured=await page.evaluate(()=>{const live=window.memoryRetained.refs.filter(r=>r.target.deref());return {parsed_pages:window.memoryRetained.refs.length/2,transferred_page_bytes:window.memoryRetained.transferred,retained_objects:live.length,retained_bytes:live.reduce((sum,r)=>sum+r.bytes,0),rendered_rows:document.querySelectorAll('.el-table__body tbody tr').length};});expect(measured.parsed_pages).toBe(60);expect(measured.transferred_page_bytes).toBeGreaterThan(2*1024*1024);expect(measured.retained_objects).toBeLessThanOrEqual(2);expect(measured.retained_bytes).toBeLessThanOrEqual(2*1024*1024);expect(measured.rendered_rows).toBeLessThanOrEqual(100);info.annotations.push({type:"measurement",description:JSON.stringify({...measured,fixture_pages:60,rows_per_page:25,measurement:"WeakRef live parsed arrays and metadata after explicit GC"})});});
