// Failure scenarios: implicit/manual scope selection; cross-scope/role data; false
// extraction-completeness claims; stale single/batch/manual decisions; guessed Source
// fields; preview failures; automatic select-all; archive writes; source markup XSS;
// source repair authority; lost edits; and requirement approval bypassing response gates.
import { test, expect } from "@playwright/test";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve, join } from "node:path";
import { rubricFixture, scoreFixture } from "./assessment-rubric-fixture.js";
import { requirementFixture, ids, manualQuote } from "./requirement-confirmation-fixture.js";
const output=resolve("../data/work/requirement-confirmation/browser");
const path=()=>`/app/org/tasks/${ids.task}/requirements?job=${ids.extract}`;
async function openFirst(page){await page.getByRole("button",{name:"核对要求：合成要求 1",exact:true}).click();await expect(page.getByTestId("requirement-detail")).toContainText("创建待确认要求");}
async function manualForm(page,{newScope=false,rejected=false}={}){if(rejected){await page.getByRole("combobox",{name:"拒绝回执作业"}).click();await page.getByRole("option").first().click();await page.getByRole("button",{name:"读取拒绝摘要",exact:true}).click();await page.getByRole("button",{name:"从原文补录",exact:true}).click();}else await page.getByRole("button",{name:"补录遗漏要求",exact:true}).click();if(newScope)await page.getByRole("radio",{name:"新建人工补录集",exact:true}).check();await page.getByRole("combobox",{name:"补录招标文件"}).click();await page.getByRole("option").first().click();await page.getByRole("combobox",{name:"补录原文位置"}).click();await page.getByRole("option").first().click();await page.getByRole("textbox",{name:"逐字引文",exact:true}).fill(manualQuote);await page.getByRole("textbox",{name:"要求正文",exact:true}).fill("人工补录可核对的要求");await page.getByRole("textbox",{name:"补录原因",exact:true}).fill("人工核对发现遗漏");}
async function artifact(page,state,name){state.verify();mkdirSync(output,{recursive:true});await page.screenshot({path:join(output,`${name}.png`),fullPage:true});writeFileSync(join(output,`${name}.json`),JSON.stringify({passed:true,seed:"requirement-review-mocked-api-v1",scenario:name,contract:"4.0",scope:state.scope(),decisions:state.decisions.map(item=>({path:item.path,action:item.body.action,expected_revision:item.body.expected_revision})),manual_writes:state.manuals.length,batches:state.batches.map(item=>({size:item.body.items.length,reviewed_each:item.body.reviewed_each})),checks:["exact-v4-paths","bounded-explicit-scope","human-explicit-actions","no-paid-model-call"],repeat:{command:"E2E_BASE_URL=http://console.test E2E_STATIC_DIR=web/dist npm --prefix web run e2e -- requirement-confirmation.spec.js",static_fixture:true}},null,2));}
test("explicit source review, confirm and reopen keep response gate separate",async({page})=>{const state=await requirementFixture(page);await page.goto(path());await expect(page.getByText("已确认不代表无遗漏",{exact:false}).first()).toBeVisible();await expect(page.getByTestId("requirement-review-row")).toHaveCount(5);expect(state.decisions).toHaveLength(0);await openFirst(page);const detail=page.getByTestId("requirement-detail");await expect(detail.getByRole("button",{name:"确认要求",exact:true})).toBeDisabled();await detail.getByRole("textbox",{name:"要求审阅原因",exact:true}).fill("逐字核对原件与条件");await detail.getByRole("checkbox",{name:/已核对正文/}).check();await detail.getByRole("button",{name:"确认要求",exact:true}).click();await expect(detail.getByRole("button",{name:"重新打开要求",exact:true})).toBeVisible();expect(state.decisions[0].body.expected_revision).toBe(1);await expect(detail.getByRole("link",{name:"进入响应与证据审阅"})).toBeVisible();await detail.getByRole("textbox",{name:"要求审阅原因",exact:true}).fill("重新核对来源变化");await detail.getByRole("button",{name:"重新打开要求",exact:true}).click();await expect(detail.getByRole("button",{name:"确认要求",exact:true})).toBeVisible();expect(state.decisions.map(item=>item.body.action)).toEqual(["confirm","reopen"]);await artifact(page,state,"single-confirm-reopen");});
test("409 clears acknowledgement and retains exact reason without replay",async({page})=>{const state=await requirementFixture(page,{conflict:true});await page.goto(path());await openFirst(page);const detail=page.getByTestId("requirement-detail");await detail.getByRole("textbox",{name:"要求审阅原因",exact:true}).fill("冲突时保留的核对原因");await detail.getByRole("checkbox",{name:/已核对正文/}).check();await detail.getByRole("button",{name:"确认要求",exact:true}).click();await expect(detail.getByRole("alert")).toContainText("未自动重试");await expect(detail.getByRole("textbox",{name:"要求审阅原因",exact:true})).toHaveValue("冲突时保留的核对原因");await expect(detail.getByRole("checkbox",{name:/已核对正文/})).not.toBeChecked();await expect(detail.getByRole("button",{name:"确认要求",exact:true})).toBeDisabled();await detail.getByRole("button",{name:"重新读取要求修订",exact:true}).click();await expect(detail.getByRole("textbox",{name:"要求审阅原因",exact:true})).toHaveValue("冲突时保留的核对原因");expect(state.decisions).toHaveLength(1);await artifact(page,state,"conflict-retained");});
test("owner explicit batch requires each source, acknowledgement and reason",async({page})=>{const state=await requirementFixture(page);await page.goto(path());const checkbox=page.getByRole("checkbox",{name:"加入确认批次：合成要求 1",exact:true});await expect(checkbox).toBeDisabled();await openFirst(page);await checkbox.check();await page.getByRole("textbox",{name:"批次确认原因",exact:true}).fill("逐项核对本批原文");await expect(page.getByRole("button",{name:"确认明确选择的要求",exact:true})).toBeDisabled();await page.getByRole("checkbox",{name:"已逐项核对全部明确选择的要求与来源",exact:true}).check();await page.getByRole("button",{name:"确认明确选择的要求",exact:true}).click();await expect.poll(()=>state.batches.length).toBe(1);expect(state.batches[0].body.items).toHaveLength(1);expect(state.batches[0].body.reviewed_each).toBe(true);await artifact(page,state,"owner-explicit-batch");});
test("batch conflict retains reason but requires newly inspected snapshots",async({page})=>{const state=await requirementFixture(page,{batchConflict:true});await page.goto(path());await openFirst(page);await page.getByRole("checkbox",{name:"加入确认批次：合成要求 1",exact:true}).check();await page.getByRole("textbox",{name:"批次确认原因",exact:true}).fill("批次冲突保留原因");await page.getByRole("checkbox",{name:"已逐项核对全部明确选择的要求与来源",exact:true}).check();await page.getByRole("button",{name:"确认明确选择的要求",exact:true}).click();await expect(page.getByRole("alert").last()).toContainText("未自动重试");await expect(page.getByRole("textbox",{name:"批次确认原因",exact:true})).toHaveValue("批次冲突保留原因");await expect(page.getByRole("checkbox",{name:"已逐项核对全部明确选择的要求与来源",exact:true})).not.toBeChecked();expect(state.batches).toHaveLength(1);await artifact(page,state,"batch-conflict");});
test("rejected summary recovers a full source and saves unconfirmed Word requirement",async({page})=>{const state=await requirementFixture(page,{word:true,taskRole:"contributor",role:"technical"});await page.goto(path());await manualForm(page,{rejected:true});await page.getByRole("button",{name:"核验补录来源",exact:true}).click();await expect(page.getByText(/原文精确跨度/)).toBeVisible();await page.getByRole("button",{name:"保存待确认要求",exact:true}).click();await expect.poll(()=>state.manuals.length).toBe(1);expect(state.manuals[0].body.content.source.location.block_id).toBe("p-17");expect(state.manuals[0].body.content.source.page).toBeNull();expect(state.manuals[0].body.rejected_item.index).toBe(0);expect(state.entries.at(-1).state).toBe("unconfirmed");expect(state.decisions).toHaveLength(0);await artifact(page,state,"rejected-word-manual");});
test("all-rejected failure creates explicit manual scope without changing failed receipt",async({page})=>{const state=await requirementFixture(page,{allRejected:true});await page.goto(`/app/org/tasks/${ids.task}/requirements`);await manualForm(page,{newScope:true,rejected:true});await page.getByRole("button",{name:"核验补录来源",exact:true}).click();await expect(page.getByRole("button",{name:"保存待确认要求",exact:true})).toBeEnabled();await page.getByRole("button",{name:"保存待确认要求",exact:true}).click();await expect(page).toHaveURL(new RegExp(`job=${state.scopes[0]}`));await expect(page.getByText(/人工补录集 · 合成招标文件/).first()).toBeVisible();expect(state.allRejected).toBe(true);expect(state.manuals[0].body.extraction_job_id).toBeNull();expect(state.manuals[0].body.expected_set_revision).toBeNull();expect(state.entries.at(-1).state).toBe("unconfirmed");await artifact(page,state,"all-rejected-manual-scope");});
test("manual preview write conflict keep input without paid retry",async({page})=>{const state=await requirementFixture(page,{manualConflict:true});await page.goto(path());await manualForm(page);await page.getByRole("button",{name:"核验补录来源",exact:true}).click();await page.getByRole("button",{name:"保存待确认要求",exact:true}).click();await expect(page.getByRole("alert").last()).toContainText("输入已保留");await expect(page.getByRole("textbox",{name:"要求正文",exact:true})).toHaveValue("人工补录可核对的要求");await expect(page.getByRole("button",{name:"保存待确认要求",exact:true})).toHaveCount(0);expect(state.manuals).toHaveLength(1);await artifact(page,state,"manual-write-conflict");});
for(const options of [{name:"viewer",role:"viewer"},{name:"archived",archived:true},{name:"invalid-citation",sourceInvalid:true}])test(`${options.name} keeps requirement decisions read-only and names recovery`,async({page})=>{const state=await requirementFixture(page,options);await page.goto(path());await openFirst(page);const detail=page.getByTestId("requirement-detail");await expect(detail.getByRole("button",{name:"确认要求",exact:true})).toBeDisabled();if(options.sourceInvalid)await expect(detail).toContainText("协调管理员修复引用");else await expect(page.getByRole("button",{name:"补录遗漏要求",exact:true})).toBeDisabled();expect(state.decisions).toHaveLength(0);expect(state.manuals).toHaveLength(0);await artifact(page,state,options.name);});
test("board uses opt-in requirement bucket and links outstanding review",async({page})=>{const state=await requirementFixture(page);await page.goto(`/app/org/tasks/${ids.task}/board?job=${ids.extract}`);await expect(page.getByTestId("bucket-requirement_review")).toContainText("4");await page.getByRole("link",{name:"核对并确认要求",exact:true}).first().click();await expect(page).toHaveURL(/\/requirements\?job=.*&requirement=/);await expect(page.getByTestId("requirement-detail")).toBeVisible();expect(state.reads.some(item=>item.path.endsWith("/board")&&item.query.view==="requirement-review")).toBe(true);await artifact(page,state,"board-requirement-overlay");});
test("org reset clears source, history and unsaved form",async({page})=>{const state=await requirementFixture(page);await page.goto(path());await manualForm(page);await page.evaluate(()=>window.dispatchEvent(new Event("bid:org-reset")));await expect(page.getByRole("textbox",{name:"要求正文",exact:true})).toHaveCount(0);await expect(page.getByTestId("requirement-review-row")).toHaveCount(0);expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain("人工补录可核对的要求");await artifact(page,state,"org-reset-clears-content");});

test("failed preview keeps editable input and exposes no save",async({page})=>{const state=await requirementFixture(page,{previewFailure:true});await page.goto(path());await manualForm(page);await page.getByRole("button",{name:"核验补录来源",exact:true}).click();await expect(page.getByRole("alert").last()).toContainText("nonverbatim_quote");await expect(page.getByRole("textbox",{name:"逐字引文",exact:true})).toHaveValue(manualQuote);await expect(page.getByRole("button",{name:"保存待确认要求",exact:true})).toHaveCount(0);expect(state.manuals).toHaveLength(0);await artifact(page,state,"failed-manual-preview");});
test("owner selection stops at 100 explicit inspected sources across server pages",async({page})=>{test.setTimeout(240000);const state=await requirementFixture(page,{count:101});await page.goto(path());for(let index=0;index<101;index++){if(index===50||index===100)await page.getByRole("button",{name:"下一页",exact:true}).click();const title=`合成要求 ${index+1}`;await page.getByRole("button",{name:`核对要求：${title}`,exact:true}).click();const checkbox=page.getByRole("checkbox",{name:`加入确认批次：${title}`,exact:true});await expect(checkbox).toBeEnabled();await checkbox.check();}await expect(page.getByText("单批最多 100 项。",{exact:true})).toBeVisible();await expect(page.getByRole("checkbox",{name:"加入确认批次：合成要求 101",exact:true})).not.toBeChecked();await page.getByRole("textbox",{name:"批次确认原因",exact:true}).fill("只确认逐项核对的 100 项");await page.getByRole("checkbox",{name:"已逐项核对全部明确选择的要求与来源",exact:true}).check();await page.getByRole("button",{name:"确认明确选择的要求",exact:true}).click();await expect.poll(()=>state.batches.length).toBe(1);expect(state.batches[0].body.items).toHaveLength(100);await artifact(page,state,"batch-100-bound");});

async function rubricArtifact(page,state,name){state.verify();mkdirSync(output,{recursive:true});await page.screenshot({path:join(output,`${name}.png`),fullPage:true});writeFileSync(join(output,`${name}.json`),JSON.stringify({passed:true,seed:"requirement-review-rubric-v1",scenario:name,requirement_review:state.requirementReview,writes:state.writes,previews:state.previews,checks:["explicit-source-readiness","preparation-keeps-child-edits","no-automatic-score-retry"]},null,2));}
for(const status of ["preparation","stale",null])test(`rubric source ${status??"unknown"} blocks whole-set confirmation and keeps revision preparation`,async({page})=>{const requirementReview=status?{state:status,fixed_count:2,confirmed_count:status==="preparation"?1:2,invalidation_codes:status==="stale"?["requirement_invalidated"]:[]}:null;const state=await rubricFixture(page,{requirementReview});state.sections.forEach(row=>row.state="confirmed");state.rubricItems.forEach(row=>row.state="confirmed");state.rubricCoverage.forEach((row,index)=>{row.disposition="mapped";row.rubric_item_ids=[state.rubricItems[index].id];});await page.goto(`/app/org/tasks/${ids.task}/score-rubrics/${ids.rubric}`);await expect(page.getByTestId("rubric-source-state")).toContainText(status==="preparation"?"评分来源准备中":status==="stale"?"评分来源已过期":"评分来源待核对");await expect(page.getByRole("button",{name:"确认整套评分规则",exact:true})).toBeDisabled();await expect(page.getByRole("button",{name:"完整修订评分规则",exact:true})).toBeEnabled();await expect(page.getByRole("link",{name:"核对评分来源要求",exact:true})).toHaveAttribute("href",`/app/org/tasks/${ids.task}/requirements?job=${ids.extract}`);expect(state.writes).toBe(0);await rubricArtifact(page,state,`rubric-source-${status??"unknown"}`);});
test("preparation rubric still permits child preparation and classification",async({page})=>{const state=await rubricFixture(page,{requirementReview:{state:"preparation",fixed_count:2,confirmed_count:0,invalidation_codes:[]}});await page.goto(`/app/org/tasks/${ids.task}/score-rubrics/${ids.rubric}`);await expect(page.getByRole("button",{name:"确认分节",exact:true}).first()).toBeEnabled();await page.getByRole("button",{name:"确认分节",exact:true}).first().click();await page.getByRole("dialog").getByRole("textbox",{name:"处理理由",exact:true}).fill("先完成候选分节的准备核对");await page.getByRole("dialog").getByRole("button",{name:"提交决定",exact:true}).click();await expect.poll(()=>state.writes).toBe(1);await expect(page.getByRole("button",{name:"确认整套评分规则",exact:true})).toBeDisabled();state.role="admin";await page.reload();await expect(page.getByRole("button",{name:"分配职责",exact:true}).first()).toBeEnabled();await rubricArtifact(page,state,"rubric-preparation-child-actions");});
for(const status of ["preparation","stale",null])test(`score source ${status??"unknown"} prevents preview and submission until explicit refreshed readiness`,async({page})=>{const state=await scoreFixture(page,{requirementReview:status?{state:status,fixed_count:2,confirmed_count:1,invalidation_codes:status==="stale"?["requirement_invalidated"]:[]}:null});await page.goto(`/app/org/tasks/${ids.task}/scores?job=${ids.extract}&rubric=${ids.rubric}`);await expect(page.getByTestId("score-source-state")).toContainText(status==="preparation"?"评分来源准备中":status==="stale"?"评分来源已过期":"评分来源待核对");await expect(page.getByRole("button",{name:"预览评分",exact:true})).toBeDisabled();await expect(page.getByRole("link",{name:"核对评分来源要求",exact:true})).toHaveAttribute("href",`/app/org/tasks/${ids.task}/requirements?job=${ids.extract}`);expect(state.previews).toBe(0);expect(state.submissions).toBe(0);state.requirementReview={state:"ready",fixed_count:2,confirmed_count:2,invalidation_codes:[]};await page.getByRole("button",{name:"重新核对评分规则来源",exact:true}).click();await expect(page.getByRole("button",{name:"预览评分",exact:true})).toBeEnabled();expect(state.previews).toBe(0);await rubricArtifact(page,state,`score-source-${status??"unknown"}`);});
for(const code of ["requirement_unconfirmed","requirement_invalidated","review_changed"])test(`score ${code} clears preview and requires explicit source refresh`,async({page})=>{const state=await scoreFixture(page,{scoreSourceError:code});await page.goto(`/app/org/tasks/${ids.task}/scores?job=${ids.extract}&rubric=${ids.rubric}`);await page.getByLabel("本次作业平台扣费上限",{exact:true}).fill("1");await page.getByRole("button",{name:"预览评分",exact:true}).click();await expect(page.getByRole("alert").first()).toContainText(code);await expect(page.getByRole("button",{name:"预览评分",exact:true})).toBeDisabled();await expect(page.getByRole("button",{name:"提交评分",exact:true})).toHaveCount(0);await expect(page.getByLabel("本次作业平台扣费上限",{exact:true})).toHaveValue("1");expect(state.submissions).toBe(0);expect(state.requests.filter(row=>row.method==="POST"&&row.path.endsWith("/scores/preview"))).toHaveLength(1);state.scoreSourceError=null;await page.getByRole("button",{name:"重新核对评分规则来源",exact:true}).click();await expect(page.getByRole("button",{name:"预览评分",exact:true})).toBeEnabled();expect(state.requests.filter(row=>row.method==="POST"&&row.path.endsWith("/scores/preview"))).toHaveLength(1);await rubricArtifact(page,state,`score-source-error-${code}`);});

test("manual recovery preserves its request ID after an uncertain transport result", async ({ page }) => {
  const state = await requirementFixture(page);
  const requests = [];
  await page.route(`**/v4/tasks/${ids.task}/requirements/manual`, async route => {
    requests.push(route.request().postDataJSON().request_id);
    if (requests.length === 1) {
      await route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ ok: false, command: "req add", data: { error: { code: "service_unavailable", message: "Synthetic uncertain transport result", exit_code: 3 } }, items: [], warnings: [], cost: { llm_tokens: 0, ocr_pages: 0, usd: 0, basis: "zero", charge: "0", billing_currency: "USD", task_amount: "0", unpriced_calls: 0, unresolved_calls: 0 }, duration_ms: 0 }) });
      return;
    }
    await route.fallback();
  });
  await page.goto(path());
  await manualForm(page, { newScope: true });
  await page.getByRole("button", { name: "核验补录来源", exact: true }).click();
  await page.getByRole("button", { name: "保存待确认要求", exact: true }).click();
  await expect(page.getByRole("alert").last()).toContainText("未自动重试");
  await page.getByRole("button", { name: "核验补录来源", exact: true }).click();
  await page.getByRole("button", { name: "保存待确认要求", exact: true }).click();
  await expect.poll(() => state.manuals.length).toBe(1);
  expect(requests).toHaveLength(2);
  expect(requests[0]).toBe(requests[1]);
  await artifact(page, state, "manual-uncertain-replay-identity");
});
