// Failure scenarios specified before implementation: implicit extraction selection,
// unbounded filters/page fetches, invented progress, hidden-tab polling, unauthenticated
// SSE, duplicate event reload storms, permission-loss stale content, stale revision
// write retry, archived member writes, and future-slice placeholder controls.
import { test, expect } from "@playwright/test";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, join, extname, basename } from "node:path";
const output = resolve(process.env.E2E_OUTPUT ?? "../data/work/team-workflow-acceptance/browser");
const T = "00000000-0000-0000-0000-000000000001", O = "00000000-0000-0000-0000-000000000002", U = "00000000-0000-0000-0000-000000000003", J = "00000000-0000-0000-0000-000000000004";
const K="00000000-0000-0000-0000-000000000005";
const result = (command, data={}, items=[], ok=true) => ({ok,command,data,items,warnings:[],cost:{llm_tokens:0,ocr_pages:0,usd:"0",basis:"actual",charge:"0",task_amount:"0",billing_currency:null,unpriced_calls:0,unresolved_calls:0},duration_ms:0});
const workflow = () => ({org_id:O,task_id:T,owner_user_id:U,state:"active",revision:1,access_epoch:1,last_event_cursor:"opaque-snapshot",co_sign_starred:false,rule_revision:1,archived_at:null,archived_by_user_id:null});
const row = () => ({requirement_id:U,title:"合成验收要求",category:"technical",starred:true,bucket:"gap",card_id:null,card_revision:null,card_state:null,eligibility:null,assignment_revision:0,co_sign:null,comment_thread_count:0,flags:{human_needs_material:false,model_needs_material_hint:false,certificate_date_advisory:false,final_export_prototype_blocked:false},owner_user_id:null,review_domain:"technical",blockers:["missing_card"],next_actions:[{code:"create_card",target:{kind:"requirement",id:U},eligible_user_ids:[U],eligible_domains:[]}]});
test.beforeEach(async ({page}) => {
  await page.addInitScript(({O,U})=>sessionStorage.setItem("bid.org.session", JSON.stringify({session:"synthetic-only-session",orgId:O,userId:U})),{O,U});
  if(process.env.E2E_STATIC_DIR) { const directory=resolve(process.env.E2E_STATIC_DIR); await page.route(url=>url.pathname.startsWith("/app/"),route=>{const pathname=new URL(route.request().url()).pathname;const file=pathname.startsWith("/app/assets/")?join(directory,"assets",basename(pathname)):join(directory,"index.html");return route.fulfill({contentType:{".html":"text/html",".js":"text/javascript",".css":"text/css"}[extname(file)]??"application/octet-stream",body:readFileSync(file)});}); }
});
async function fixture(page,{denial=false,streamFrames=null,conflict=false,role="bidder",paginated=false,archived=false,taskRole="owner"}={}) {
  let boards=0, streams=0, mutations=[];
  let state={...workflow(),state:archived?"archived":"active",archived_at:archived?"2026-10-05T00:00:00Z":null,archived_by_user_id:archived?U:null};
  let memberRows=[{org_id:O,task_id:T,user_id:U,display_label:"合成负责人",role:taskRole,active:true,review_domains:taskRole==="observer"?[]:["commercial"],revision:1}];
  let pollCalls=0;
  if(taskRole!=="owner")state.owner_user_id=K;
  if(role==="viewer"){state.owner_user_id=K;memberRows[0].role="observer";memberRows[0].review_domains=[];}
  const boardQueries=[];
  await page.route(url=>!url.pathname.startsWith("/app/"),async route=>{
    const request=route.request(),url=new URL(request.url()),path=url.pathname;
    expect(request.headers().authorization).toBe("Bearer synthetic-only-session");expect(request.headers()["x-org-id"]).toBe(O);
    if(path==="/org/current")return route.fulfill({json:result("org current",{org_id:O,user_id:U,role})});
    if(path===`/tasks/${T}`)return route.fulfill({json:result("task show",{id:T,name:"合成验收任务",model_redaction_enabled:true})});
    if(path===`/tasks/${T}/documents`||path===`/tasks/${T}/jobs`||path===`/tasks/${T}/exports`)return route.fulfill({json:result("task list",{},[])});
    if(path==="/confidential-fields"||path==="/confidential-values")return route.fulfill({json:result("confidential list",{},[])});
    if(path===`/tasks/${T}/extractions`)return route.fulfill({json:result("req history",{},[{job_id:J,status:"succeeded"}])});
    if(path===`/tasks/${T}/events`){streams++;expect(request.headers()["last-event-id"]).toBeTruthy();if(streamFrames)return route.fulfill({contentType:"text/event-stream",body:streamFrames(streams)});return route.fulfill({status:denial?403:503,json:result("task events",{error:{code:denial?"forbidden":"network_unavailable",message:"unavailable",exit_code:denial?4:3}},[],false)});}
    if(path===`/tasks/${T}/events/poll`){pollCalls++;return route.fulfill({json:result("task events",{org_id:O,task_id:T,next_cursor:"opaque-next",head_cursor:"opaque-next",has_more:false,reset_required:null})});}
    if(path===`/tasks/${T}/workflow`)return route.fulfill({json:result("task workflow",{workflow:state})});
    if(path===`/tasks/${T}/board`){boards++;boardQueries.push(Object.fromEntries(url.searchParams));expect(url.searchParams.get("extraction_job_id")).toBe(J);expect(Number(url.searchParams.get("limit"))).toBeLessThanOrEqual(100);return route.fulfill({json:result("task board",{org_id:O,task_id:T,extraction_job_id:J,workflow:state,counts:{total:1,gap:1,draft_card:0,pending_review:0,needs_material:0,confirmed:0,comply_only:0},matching:1,returned:1,next_cursor:paginated&&!url.searchParams.has("cursor")?"opaque-page2":null,event_cursor:"opaque-snapshot",budget:{org_id:O,task_id:T,revision:1,limit:"100",currency:"USD",state:"active",spent:"0",reserved:"0",available:"100",unpriced_calls:0,unresolved_calls:0,history_complete:true,as_of:new Date().toISOString()},jobs:[],activity:[],as_of:new Date().toISOString(),refresh_by:new Date(Date.now()+30000).toISOString()},[row()])});}
    if(path===`/tasks/${T}/progress`)return route.fulfill({json:result("task progress",{org_id:O,task_id:T,workflow:state,event_cursor:"opaque-snapshot",next_cursor:null,as_of:new Date().toISOString(),returned:1},[{job_id:J,state:"running",attempts:1,progress:{completed:1,total:null}}])});
    if(path===`/tasks/${T}/members`)return route.fulfill({json:result("task member list",{org_id:O,task_id:T,next_cursor:null,returned:memberRows.length,has_more:false},memberRows)});
    if(path===`/tasks/${T}/member-candidates`)return route.fulfill({json:result("task member candidates",{org_id:O,task_id:T,next_cursor:null,returned:2,has_more:false},[{org_id:O,user_id:J,display_label:"合成技术成员",org_role:"technical",active:true},{org_id:O,user_id:K,display_label:"合成商务接任者",org_role:"bidder",active:true}])});
    if(request.method()!=="GET"){mutations.push({path,body:request.postDataJSON()});if(conflict)return route.fulfill({status:409,json:result("task member set",{error:{code:"revision_conflict",message:"Conflict",exit_code:2}},[],false)});if(path.endsWith(`/members/${J}`))memberRows.push({org_id:O,task_id:T,user_id:J,display_label:"合成技术成员",role:request.postDataJSON().role,active:true,review_domains:request.postDataJSON().review_domains,revision:1});if(path.endsWith('/handover')){state.owner_user_id=request.postDataJSON().target_user_id;if(!memberRows.some(m=>m.user_id===state.owner_user_id))memberRows.push({org_id:O,task_id:T,user_id:K,display_label:"合成商务接任者",active:true,review_domains:["commercial"],role:"owner",revision:1});memberRows=memberRows.map(m=>({...m,role:m.user_id===state.owner_user_id?'owner':m.user_id===U?request.postDataJSON().previous_owner_role:m.role}));}state={...state,revision:state.revision+1,state:path.endsWith("/archive")?"archived":state.state,archived_at:path.endsWith("/archive")?new Date().toISOString():state.archived_at,archived_by_user_id:path.endsWith("/archive")?U:state.archived_by_user_id};return route.fulfill({json:result("task archive",{workflow:state})});}
    return route.fulfill({status:404,json:result("task read",{error:{code:"not_found",message:"Not found",exit_code:4}},[],false)});
  });return {boards:()=>boards,streams:()=>streams,mutations,polls:()=>pollCalls,boardQueries};
}
test("explicit extraction, bounded filters and progress fallback",async({page})=>{
  const f=await fixture(page);await page.goto(`/app/org/tasks/${T}/board`);await expect(page.getByRole("heading",{name:"任务看板"})).toBeVisible();expect(f.boards()).toBe(0);
  await page.getByTestId("extraction-select").click();await page.getByRole("option").first().click();await expect(page.getByText("合成验收要求")).toBeVisible();await page.getByTestId("bucket-gap").click();await expect(page).toHaveURL(/bucket=gap/);await expect(page.getByText("创建响应卡")).toBeVisible();await expect(page.getByRole("button",{name:"分配"})).toHaveCount(0);
  await page.goto(`/app/org/tasks/${T}/progress`);await expect(page.getByText("已完成 1 项；总量未知")).toBeVisible();await expect(page.locator("[role=progressbar]")).toHaveCount(0);
  mkdirSync(output,{recursive:true});await page.screenshot({path:join(output,"progress-unknown.png"),fullPage:true});writeFileSync(join(output,"result.json"),JSON.stringify({passed:true,checks:["explicit-extraction","bounded-query","URL-filter","no-invented-progress","no-future-controls"]},null,2));
});
test("stream denial clears task data and stops retries",async({page})=>{const f=await fixture(page,{denial:true});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await expect(page.getByRole("alert")).toContainText("访问");await expect(page.getByText("合成验收要求")).toHaveCount(0);await page.waitForTimeout(1500);expect(f.streams()).toBe(1);});
test("archive uses exact revision and renders member management read-only",async({page})=>{const f=await fixture(page);await page.goto(`/app/org/tasks/${T}/members`);await expect(page.getByText("合成负责人")).toBeVisible();await page.getByRole("button",{name:"归档任务",exact:true}).click();await page.getByRole("dialog").getByRole("textbox",{name:/原因/}).fill("验收归档");await page.getByRole("button",{name:"确认归档",exact:true}).click();await expect(page.getByText("已归档",{exact:true}).first()).toBeVisible();expect(f.mutations[0].body).toEqual({expected_revision:1,reason:"验收归档"});await expect(page.getByRole("button",{name:"添加成员",exact:true})).toBeDisabled();});

const frame = data => `data: ${JSON.stringify(data)}\n\n`;
test("duplicate event invalidation, reconnect, and expired cursor reset", async ({page}) => {
  const event={event_id:U,org_id:O,task_id:T,cursor:"opaque-next",payload:{type:"board_changed",invalidate_all:true},created_at:"2026-10-05T00:00:00Z"};
  const f=await fixture(page,{streamFrames:n=>n===1?frame(event)+frame(event):frame({type:"reset_required",reason:"retention_expired",head_cursor:"opaque-next"})});
  await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await expect(page.getByText("合成验收要求")).toBeVisible();await expect.poll(f.streams).toBeGreaterThanOrEqual(2);await expect.poll(f.boards).toBeGreaterThanOrEqual(2);expect(f.boards()).toBeLessThan(6);
  await page.setViewportSize({width:390,height:844});await page.getByTestId("bucket-gap").focus();await page.keyboard.press("Enter");await expect(page).toHaveURL(/bucket=gap/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  mkdirSync(output,{recursive:true});await page.screenshot({path:join(output,"board-mobile.png"),fullPage:true});
});
test("repeated transport failures enter bounded polling and org switch clears content",async({page})=>{
  const f=await fixture(page);await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await expect(page.getByText("合成验收要求")).toBeVisible();await expect.poll(f.polls,{timeout:18000}).toBeGreaterThan(0);
  await page.evaluate(()=>window.dispatchEvent(new Event("bid:org-reset")));await expect(page.getByText("合成验收要求")).toHaveCount(0);const before=f.polls();await page.waitForTimeout(5500);expect(f.polls()).toBe(before);
});
test("member add, contributor domains and explicit handover",async({page})=>{
  const f=await fixture(page);await page.goto(`/app/org/tasks/${T}/members`);await page.getByRole("button",{name:"添加成员",exact:true}).click();const dialog=page.getByRole("dialog");await dialog.locator(".el-select").first().click();await page.getByRole("option",{name:/合成技术成员/}).click();await dialog.locator(".el-select").nth(1).click();await page.getByRole("option",{name:"协作者",exact:true}).click();await dialog.locator(".el-checkbox").filter({hasText:"技术"}).click();await dialog.getByRole("textbox",{name:/原因/}).fill("协作验收");await dialog.getByRole("button",{name:"保存成员"}).click();await expect(page.getByRole("cell",{name:"合成技术成员",exact:true})).toBeVisible();expect(f.mutations[0].body).toEqual({expected_revision:1,reason:"协作验收",role:"contributor",review_domains:["technical"]});await page.getByRole("button",{name:"交接负责人",exact:true}).click();await page.getByRole("dialog").locator(".el-select").first().click();await page.getByRole("option",{name:/合成商务接任者/}).click();await page.getByRole("dialog").getByRole("textbox",{name:/原因/}).fill("交接验收");await page.getByRole("button",{name:"确认交接",exact:true}).click();await expect(page.getByRole("cell",{name:"合成商务接任者",exact:true})).toBeVisible();expect(f.mutations[1].body).toEqual({expected_revision:2,reason:"交接验收",target_user_id:K,previous_owner_role:"observer",previous_owner_review_domains:[]});await expect(page.getByRole("button",{name:"添加成员",exact:true})).toHaveCount(0);
});
test("revision conflict does not replay a human mutation",async({page})=>{const f=await fixture(page,{conflict:true});await page.goto(`/app/org/tasks/${T}/members`);await page.getByRole("button",{name:"归档任务",exact:true}).click();await page.getByRole("dialog").getByRole("textbox",{name:/原因/}).fill("冲突验收");await page.getByRole("button",{name:"确认归档",exact:true}).click();await expect(page.getByRole("dialog").getByRole("alert")).toContainText("未重试");await expect(page.getByRole("button",{name:"确认归档",exact:true})).toBeDisabled();expect(f.mutations.length).toBe(1);});

test("server pagination resets its cursor after filters and viewers see no management controls",async({page})=>{const f=await fixture(page,{paginated:true,role:"viewer"});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await expect(page.getByText("合成验收要求")).toBeVisible();await page.getByRole("button",{name:"下一页",exact:true}).click();await expect.poll(()=>f.boardQueries.at(-1).cursor).toBe("opaque-page2");await page.getByTestId("bucket-gap").click();await expect.poll(()=>f.boardQueries.at(-1).bucket).toBe("gap");expect(f.boardQueries.at(-1).cursor).toBeUndefined();await page.goto(`/app/org/tasks/${T}/members`);await expect(page.getByRole("button",{name:"添加成员",exact:true})).toHaveCount(0);await expect(page.getByRole("button",{name:"归档任务",exact:true})).toHaveCount(0);});

for (const configuration of [{name:"archived",archived:true,taskRole:"owner"},{name:"observer",archived:false,taskRole:"observer"}]) {
  test(`existing task entry hides work for ${configuration.name}`,async({page})=>{await fixture(page,configuration);await page.goto(`/app/org/tasks/${T}`);await expect(page.getByRole("heading",{name:"合成验收任务",exact:true})).toBeVisible();if(configuration.archived)await expect(page.getByRole("alert")).toContainText("已归档");await expect(page.locator("form.upload")).toHaveCount(0);await expect(page.getByRole("button",{name:"开始解析",exact:true})).toHaveCount(0);});
}
