// Failure scenarios specified before implementation: implicit extraction selection,
// unbounded filters/page fetches, invented progress, hidden-tab polling, unauthenticated
// SSE, duplicate event reload storms, permission-loss stale content, stale revision
// write retry, archived member writes, and future-slice placeholder controls.
import { test, expect } from "@playwright/test";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, join, extname, basename } from "node:path";
const output = resolve(process.env.E2E_OUTPUT ?? "../data/work/team-workflow-acceptance/browser");
const T = "00000000-0000-0000-0000-000000000001", O = "00000000-0000-0000-0000-000000000002", U = "00000000-0000-0000-0000-000000000003", J = "00000000-0000-0000-0000-000000000004";
const K="00000000-0000-0000-0000-000000000005";
const C="00000000-0000-0000-0000-000000000006", H="00000000-0000-0000-0000-000000000007", M="00000000-0000-0000-0000-000000000008";
const result = (command, data={}, items=[], ok=true) => ({ok,command,data,items,warnings:[],cost:{llm_tokens:0,ocr_pages:0,usd:"0",basis:"actual",charge:"0",task_amount:"0",billing_currency:null,unpriced_calls:0,unresolved_calls:0},duration_ms:0});
const workflow = () => ({org_id:O,task_id:T,owner_user_id:U,state:"active",revision:1,access_epoch:1,last_event_cursor:"opaque-snapshot",co_sign_starred:false,rule_revision:1,archived_at:null,archived_by_user_id:null});
const row = () => ({requirement_id:U,title:"合成验收要求",category:"technical",starred:true,bucket:"gap",card_id:null,card_revision:null,card_state:null,eligibility:null,assignment_revision:0,co_sign:null,comment_thread_count:0,flags:{human_needs_material:false,model_needs_material_hint:false,certificate_date_advisory:false,final_export_prototype_blocked:false},owner_user_id:null,review_domain:"technical",blockers:["missing_card"],next_actions:[{code:"create_card",target:{kind:"requirement",id:U},eligible_user_ids:[U],eligible_domains:[]}]});
test.beforeEach(async ({page}) => {
  await page.addInitScript(({O,U})=>sessionStorage.setItem("bid.org.session", JSON.stringify({session:"synthetic-only-session",orgId:O,userId:U})),{O,U});
  if(process.env.E2E_STATIC_DIR) { const directory=resolve(process.env.E2E_STATIC_DIR); await page.route(url=>url.pathname.startsWith("/app/"),route=>{const pathname=new URL(route.request().url()).pathname;const file=pathname.startsWith("/app/assets/")?join(directory,"assets",basename(pathname)):join(directory,"index.html");return route.fulfill({contentType:{".html":"text/html",".js":"text/javascript",".css":"text/css"}[extname(file)]??"application/octet-stream",body:readFileSync(file)});}); }
});
async function fixture(page,{denial=false,streamFrames=null,conflict=false,role="bidder",paginated=false,archived=false,taskRole="owner",withCard=false,lostComment=false,foreignThread=false,threadPages=false,nextAction=null,viewerContributor=false,boardFailures=0,delayThreads=false,boardRetryAfter=null,pollSnapshotFailure=false}={}) {
  let boards=0, streams=0, mutations=[];
  let state={...workflow(),last_event_cursor:"opaque-workflow",state:archived?"archived":"active",archived_at:archived?"2026-10-05T00:00:00Z":null,archived_by_user_id:archived?U:null};
  let memberRows=[{org_id:O,task_id:T,user_id:U,display_label:"合成负责人",role:taskRole,active:true,review_domains:taskRole==="observer"?[]:["commercial"],revision:1}];
  let pollCalls=0;
  if(taskRole!=="owner")state.owner_user_id=K;
  if(role==="viewer"){state.owner_user_id=K;memberRows[0].role="observer";memberRows[0].review_domains=[];}
  if(withCard)memberRows.push({org_id:O,task_id:T,user_id:J,display_label:"合成技术成员",role:"contributor",active:true,review_domains:["technical"],revision:1});
  let boardRow={...row(),...(withCard?{card_id:C,card_revision:2,card_state:"confirmed",eligibility:"eligible",bucket:"confirmed",blockers:[]}: {})};
  if(viewerContributor)memberRows.push({org_id:O,task_id:T,user_id:K,display_label:"合成只读协作者",role:"contributor",active:true,review_domains:[],revision:1});
  if(nextAction)boardRow.next_actions=[typeof nextAction==="string"?{code:nextAction,target:{kind:"requirement",id:U},eligible_user_ids:[U],eligible_domains:[]}:nextAction];
  let threadReads=0,commentReads=0,lost=false;
  const streamCheckpoints=[];
  let releaseThreads;const threadGate=delayThreads?new Promise(resolve=>{releaseThreads=resolve;}):null;
  const thread={id:H,org_id:O,task_id:T,card_id:foreignThread?K:C,created_card_revision_id:M,revision:1,created_by_user_id:U,created_at:"2026-10-05T00:00:00Z",last_message_at:"2026-10-05T00:00:00Z",message_count:1};
  const comments=[],receipts=new Map();
  if(nextAction?.target?.kind==="thread"){comments.push({id:M,org_id:O,task_id:T,card_id:C,thread_id:H,author_user_id:J,body:"提及验收",mentioned_user_ids:[U],client_request_id:K,created_at:"2026-10-05T00:00:00Z"});boardRow.comment_thread_count=1;}
  const pageMeta=(items,threadId=null)=>({org_id:O,task_id:T,card_id:C,thread_id:threadId,next_cursor:null,returned:items.length,has_more:false});
  const boardQueries=[];
  await page.route(url=>!url.pathname.startsWith("/app/"),async route=>{
    const request=route.request(),url=new URL(request.url()),path=url.pathname;
    expect(request.headers().authorization).toBe("Bearer synthetic-only-session");expect(request.headers()["x-org-id"]).toBe(O);
    if(path==="/org/current")return route.fulfill({json:result("org current",{org_id:O,user_id:U,role})});
    if(path===`/tasks/${T}`)return route.fulfill({json:result("task show",{id:T,name:"合成验收任务",model_redaction_enabled:true})});
    if(path===`/tasks/${T}/documents`||path===`/tasks/${T}/jobs`||path===`/tasks/${T}/exports`)return route.fulfill({json:result("task list",{},[])});
    if(path==="/confidential-fields"||path==="/confidential-values")return route.fulfill({json:result("confidential list",{},[])});
    if(path===`/tasks/${T}/extractions`)return route.fulfill({json:result("req history",{},[{job_id:J,status:"succeeded"}])});
    if(path===`/tasks/${T}/events`){streams++;streamCheckpoints.push(request.headers()["last-event-id"]);expect(request.headers()["last-event-id"]).toBeTruthy();if(streamFrames)return route.fulfill({contentType:"text/event-stream",body:streamFrames(streams)});return route.fulfill({status:denial?403:503,json:result("task events",{error:{code:denial?"forbidden":"network_unavailable",message:"unavailable",exit_code:denial?4:3}},[],false)});}
    if(path===`/tasks/${T}/events/poll`){pollCalls++;const reset=pollSnapshotFailure&&pollCalls===1;if(reset){boardFailures=1;boardRetryAfter="8";}return route.fulfill({json:result("task events",{org_id:O,task_id:T,next_cursor:"opaque-next",head_cursor:"opaque-next",has_more:false,reset_required:reset?{type:"reset_required",reason:"retention_expired",head_cursor:"opaque-next"}:null})});}
    if(path===`/tasks/${T}/workflow`)return route.fulfill({json:result("task workflow",{workflow:state})});
    if(path===`/tasks/${T}/board`){boards++;boardQueries.push(Object.fromEntries(url.searchParams));expect(url.searchParams.get("extraction_job_id")).toBe(J);expect(Number(url.searchParams.get("limit"))).toBeLessThanOrEqual(100);if(boardFailures-->0)return route.fulfill({status:503,headers:boardRetryAfter?{"Retry-After":boardRetryAfter}:{},json:result("task board",{error:{code:"board_busy",message:"Snapshot unavailable",exit_code:3}},[],false)});return route.fulfill({json:result("task board",{org_id:O,task_id:T,extraction_job_id:J,workflow:state,counts:{total:1,gap:1,draft_card:0,pending_review:0,needs_material:0,confirmed:0,comply_only:0},matching:1,returned:1,next_cursor:paginated&&!url.searchParams.has("cursor")?"opaque-page2":null,event_cursor:"opaque-snapshot",budget:{org_id:O,task_id:T,revision:1,limit:"100",currency:"USD",state:"active",spent:"0",reserved:"0",available:"100",unpriced_calls:0,unresolved_calls:0,history_complete:true,as_of:new Date().toISOString()},jobs:[],activity:[],as_of:new Date().toISOString(),refresh_by:new Date(Date.now()+30000).toISOString()},[boardRow])});}
    if(path===`/tasks/${T}/progress`)return route.fulfill({json:result("task progress",{org_id:O,task_id:T,workflow:state,event_cursor:"opaque-snapshot",next_cursor:null,as_of:new Date().toISOString(),returned:1},[{job_id:J,state:"running",attempts:1,progress:{completed:1,total:null}}])});
    if(path===`/tasks/${T}/members`)return route.fulfill({json:result("task member list",{org_id:O,task_id:T,next_cursor:null,returned:memberRows.length,has_more:false},memberRows)});
    if(path===`/tasks/${T}/member-candidates`)return route.fulfill({json:result("task member candidates",{org_id:O,task_id:T,next_cursor:null,returned:3,has_more:false},[{org_id:O,user_id:U,display_label:"合成负责人",org_role:"bidder",active:true},{org_id:O,user_id:J,display_label:"合成技术成员",org_role:"technical",active:true},{org_id:O,user_id:K,display_label:"合成商务接任者",org_role:viewerContributor?"viewer":"bidder",active:true}])});
    if(path===`/tasks/${T}/requirements/${U}/assignment`){const body=request.postDataJSON();mutations.push({path,body});if(conflict)return route.fulfill({status:409,json:result("card assign",{error:{code:"revision_conflict",message:"Conflict",exit_code:2}},[],false)});expect(url.searchParams.get("extraction_job_id")).toBe(J);boardRow={...boardRow,assignment_revision:boardRow.assignment_revision+1,owner_user_id:body.assignee_user_id};return route.fulfill({json:result("card assign",{assignment:{org_id:O,task_id:T,extraction_job_id:J,requirement_id:U,revision:boardRow.assignment_revision,assignee_user_id:body.assignee_user_id,changed_by_user_id:U,changed_at:new Date().toISOString()}})});}
    if(path===`/cards/${C}/threads`&&request.method()==="GET"){threadReads++;if(threadGate)await threadGate;const items=comments.length||foreignThread?[{...thread,message_count:comments.length||1}]:[];const meta=pageMeta(items);if(threadPages&&!url.searchParams.has("cursor")){meta.next_cursor="opaque-threads-page2";meta.has_more=true;}return route.fulfill({json:result("card thread list",meta,items)});}
    if(path===`/cards/${C}/threads/${H}/comments`&&request.method()==="GET"){commentReads++;return route.fulfill({json:result("card comment list",pageMeta(comments,H),comments)});}
    if((path===`/cards/${C}/threads`||path===`/cards/${C}/threads/${H}/comments`)&&request.method()==="POST"){
      const body=request.postDataJSON();mutations.push({path,body});if(conflict)return route.fulfill({status:409,json:result("card thread create",{error:{code:"revision_conflict",message:"Conflict",exit_code:2}},[],false)});
      let receipt=receipts.get(body.client_request_id);if(!receipt){const comment={...body,id:`00000000-0000-0000-0000-${String(8+comments.length).padStart(12,"0")}`,org_id:O,task_id:T,card_id:C,thread_id:H,author_user_id:U,created_at:"2026-10-05T00:00:00Z"};delete comment.expected_card_revision;comments.push(comment);boardRow={...boardRow,comment_thread_count:1};receipt=path.endsWith("/comments")?{comment}:{thread,first_comment:comment};receipts.set(body.client_request_id,receipt);}
      if(lostComment&&!lost){lost=true;return route.abort("connectionreset");}return route.fulfill({json:result(path.endsWith("/comments")?"card comment add":"card thread create",receipt)});
    }
    if(request.method()!=="GET"){mutations.push({path,body:request.postDataJSON()});if(conflict)return route.fulfill({status:409,json:result("task member set",{error:{code:"revision_conflict",message:"Conflict",exit_code:2}},[],false)});if(path.endsWith(`/members/${J}`))memberRows.push({org_id:O,task_id:T,user_id:J,display_label:"合成技术成员",role:request.postDataJSON().role,active:true,review_domains:request.postDataJSON().review_domains,revision:1});if(path.endsWith('/handover')){state.owner_user_id=request.postDataJSON().target_user_id;if(!memberRows.some(m=>m.user_id===state.owner_user_id))memberRows.push({org_id:O,task_id:T,user_id:K,display_label:"合成商务接任者",active:true,review_domains:["commercial"],role:"owner",revision:1});memberRows=memberRows.map(m=>({...m,role:m.user_id===state.owner_user_id?'owner':m.user_id===U?request.postDataJSON().previous_owner_role:m.role}));}state={...state,revision:state.revision+1,state:path.endsWith("/archive")?"archived":state.state,archived_at:path.endsWith("/archive")?new Date().toISOString():state.archived_at,archived_by_user_id:path.endsWith("/archive")?U:state.archived_by_user_id};return route.fulfill({json:result("task archive",{workflow:state})});}
    return route.fulfill({status:404,json:result("task read",{error:{code:"not_found",message:"Not found",exit_code:4}},[],false)});
  });return {boards:()=>boards,streams:()=>streams,mutations,polls:()=>pollCalls,boardQueries,threadReads:()=>threadReads,commentReads:()=>commentReads,comments,streamCheckpoints,releaseThreads:()=>releaseThreads?.(),acceptThreads:()=>{thread.card_id=C;foreignThread=false;}};
}
test("explicit extraction, bounded filters and progress fallback",async({page})=>{
  const f=await fixture(page);await page.goto(`/app/org/tasks/${T}/board`);await expect(page.getByRole("heading",{name:"任务看板"})).toBeVisible();expect(f.boards()).toBe(0);
  await page.getByTestId("extraction-select").click();await page.getByRole("option").first().click();await expect(page.getByText("合成验收要求")).toBeVisible();await page.getByTestId("bucket-gap").click();await expect(page).toHaveURL(/bucket=gap/);await expect(page.getByText("创建响应卡")).toBeVisible();await expect(page.getByRole("button",{name:/会签|签署|审阅规则/})).toHaveCount(0);await page.getByRole("button",{name:"分配与讨论",exact:true}).click();await expect(page.getByRole("dialog").getByRole("button",{name:"保存分配",exact:true})).toBeVisible();await page.getByRole("button",{name:"关闭协作面板",exact:true}).click();
  await page.goto(`/app/org/tasks/${T}/progress`);await expect(page.getByText("已完成 1 项；总量未知")).toBeVisible();await expect(page.locator("[role=progressbar]")).toHaveCount(0);
  mkdirSync(output,{recursive:true});await page.screenshot({path:join(output,"progress-unknown.png"),fullPage:true});writeFileSync(join(output,"result.json"),JSON.stringify({passed:true,checks:["explicit-extraction","bounded-query","URL-filter","no-invented-progress","no-future-controls"]},null,2));
});
test("stream denial clears task data and stops retries",async({page})=>{const f=await fixture(page,{denial:true});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await expect(page.getByRole("alert")).toContainText("访问");await expect(page.getByText("合成验收要求")).toHaveCount(0);await page.waitForTimeout(1500);expect(f.streams()).toBe(1);});
test("archive uses exact revision and renders member management read-only",async({page})=>{const f=await fixture(page);await page.goto(`/app/org/tasks/${T}/members`);await expect(page.getByText("合成负责人")).toBeVisible();await page.getByRole("button",{name:"归档任务",exact:true}).click();await page.getByRole("dialog").getByRole("textbox",{name:/原因/}).fill("验收归档");await page.getByRole("button",{name:"确认归档",exact:true}).click();await expect(page.getByText("已归档",{exact:true}).first()).toBeVisible();expect(f.mutations[0].body).toEqual({expected_revision:1,reason:"验收归档"});await expect(page.getByRole("button",{name:"添加成员",exact:true})).toBeDisabled();});

const frame = data => `data: ${JSON.stringify(data)}\n\n`;
test("duplicate event invalidation, reconnect, and expired cursor reset", async ({page}) => {
  const event={event_id:U,org_id:O,task_id:T,cursor:"opaque-next",payload:{type:"board_changed",invalidate_all:true},created_at:"2026-10-05T00:00:00Z"};
  const f=await fixture(page,{streamFrames:n=>n===1?frame(event)+frame(event):frame({type:"reset_required",reason:"retention_expired",head_cursor:"opaque-next"})});
  await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await expect(page.getByText("合成验收要求")).toBeVisible();await expect.poll(f.streams).toBeGreaterThanOrEqual(2);await expect.poll(f.boards).toBeGreaterThanOrEqual(2);expect(f.boards()).toBeLessThan(6);
  await page.setViewportSize({width:390,height:844});await page.getByTestId("bucket-gap").focus();await page.keyboard.press("Enter");await expect(page).toHaveURL(/bucket=gap/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  mkdirSync(output,{recursive:true});await page.screenshot({path:join(output,"board-mobile.png"),fullPage:true});
});
test("repeated transport failures enter bounded polling and org switch clears content",async({page})=>{
  const f=await fixture(page);await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await expect(page.getByText("合成验收要求")).toBeVisible();await expect.poll(f.polls,{timeout:18000}).toBeGreaterThan(0);
  await page.evaluate(()=>window.dispatchEvent(new Event("bid:org-reset")));await expect(page.getByText("合成验收要求")).toHaveCount(0);const before=f.polls();await page.waitForTimeout(5500);expect(f.polls()).toBe(before);
});
test("member add, contributor domains and explicit handover",async({page})=>{
  const f=await fixture(page);await page.goto(`/app/org/tasks/${T}/members`);await page.getByRole("button",{name:"添加成员",exact:true}).click();const dialog=page.getByRole("dialog");await dialog.locator(".el-select").first().click();await page.getByRole("option",{name:/合成技术成员/}).click();await dialog.locator(".el-select").nth(1).click();await page.getByRole("option",{name:"协作者",exact:true}).click();await dialog.locator(".el-checkbox").filter({hasText:"技术"}).click();await dialog.getByRole("textbox",{name:/原因/}).fill("协作验收");await dialog.getByRole("button",{name:"保存成员"}).click();await expect(page.getByRole("cell",{name:"合成技术成员",exact:true})).toBeVisible();expect(f.mutations[0].body).toEqual({expected_revision:1,reason:"协作验收",role:"contributor",review_domains:["technical"]});await page.getByRole("button",{name:"交接负责人",exact:true}).click();await page.getByRole("dialog").locator(".el-select").first().click();await page.getByRole("option",{name:/合成商务接任者/}).click();await page.getByRole("dialog").getByRole("textbox",{name:/原因/}).fill("交接验收");await page.getByRole("button",{name:"确认交接",exact:true}).click();await expect(page.getByRole("cell",{name:"合成商务接任者",exact:true})).toBeVisible();expect(f.mutations[1].body).toEqual({expected_revision:2,reason:"交接验收",target_user_id:K,previous_owner_role:"observer",previous_owner_review_domains:[]});await expect(page.getByRole("button",{name:"添加成员",exact:true})).toHaveCount(0);
});
test("revision conflict does not replay a human mutation",async({page})=>{const f=await fixture(page,{conflict:true});await page.goto(`/app/org/tasks/${T}/members`);await page.getByRole("button",{name:"归档任务",exact:true}).click();await page.getByRole("dialog").getByRole("textbox",{name:/原因/}).fill("冲突验收");await page.getByRole("button",{name:"确认归档",exact:true}).click();await expect(page.getByRole("dialog").getByRole("alert")).toContainText("未重试");await expect(page.getByRole("button",{name:"确认归档",exact:true})).toBeDisabled();expect(f.mutations.length).toBe(1);});

test("server pagination resets its cursor after filters and viewers see no management controls",async({page})=>{const f=await fixture(page,{paginated:true,role:"viewer"});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await expect(page.getByText("合成验收要求")).toBeVisible();await page.getByRole("button",{name:"下一页",exact:true}).click();await expect.poll(()=>f.boardQueries.at(-1).cursor).toBe("opaque-page2");await page.getByTestId("bucket-gap").click();await expect.poll(()=>f.boardQueries.at(-1).bucket).toBe("gap");expect(f.boardQueries.at(-1).cursor).toBeUndefined();await page.goto(`/app/org/tasks/${T}/members`);await expect(page.getByRole("button",{name:"添加成员",exact:true})).toHaveCount(0);await expect(page.getByRole("button",{name:"归档任务",exact:true})).toHaveCount(0);});

for (const configuration of [{name:"archived",archived:true,taskRole:"owner"},{name:"observer",archived:false,taskRole:"observer"}]) {
  test(`existing task entry hides work for ${configuration.name}`,async({page})=>{await fixture(page,configuration);await page.goto(`/app/org/tasks/${T}`);await expect(page.getByRole("heading",{name:"合成验收任务",exact:true})).toBeVisible();if(configuration.archived)await expect(page.getByRole("alert")).toContainText("已归档");await expect(page.locator("form.upload")).toHaveCount(0);await expect(page.getByRole("button",{name:"开始解析",exact:true})).toHaveCount(0);});
}

// Slice 2 failures specified before implementation: assignment revision/reason loss,
// viewer discussion denial, HTML execution, foreign thread binding, overlong bodies,
// stale automatic writes, response-loss duplicate comments, and persisted drafts.
test("assignment uses the displayed requirement revision and explicit reason",async({page})=>{
  const f=await fixture(page);await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await page.getByRole("button",{name:"分配与讨论"}).click();const panel=page.getByRole("dialog");await panel.getByTestId("assignment-assignee").click();await page.getByRole("option",{name:"合成负责人",exact:true}).click();await panel.getByTestId("assignment-reason").fill("负责材料准备");await panel.getByRole("button",{name:"保存分配"}).click();await expect.poll(()=>f.mutations.length).toBe(1);expect(f.mutations[0].body).toEqual({expected_assignment_revision:0,assignee_user_id:U,reason:"负责材料准备"});await expect(panel.getByText("分配已保存")).toBeVisible();
});
test("assignment conflict keeps reason but cannot replay stale revision",async({page})=>{
  const f=await fixture(page,{conflict:true});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await page.getByRole("button",{name:"分配与讨论"}).click();await page.getByTestId("assignment-reason").fill("并发验收");await page.getByRole("button",{name:"保存分配"}).click();await expect(page.getByRole("dialog").getByRole("alert")).toContainText("未重试");await expect(page.getByRole("button",{name:"保存分配"})).toBeDisabled();expect(f.mutations.length).toBe(1);
});
test("viewer comments on confirmed cards render escaped text and replies",async({page})=>{
  const f=await fixture(page,{role:"viewer",withCard:true});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await page.getByRole("button",{name:"分配与讨论"}).click();const panel=page.getByRole("dialog");await expect(panel.getByRole("button",{name:"保存分配"})).toHaveCount(0);await panel.getByTestId("comment-body").fill('<img src=x onerror="window.injected=true">验收');await panel.getByTestId("comment-mentions").click();await page.getByRole("option",{name:"合成技术成员",exact:true}).click();await panel.getByRole("button",{name:"创建讨论",exact:true}).click();await expect(panel.locator(".comment-body")).toContainText("<img src=x");await expect(panel.locator(".comment-body img")).toHaveCount(0);expect(await page.evaluate(()=>window.injected)).toBeUndefined();expect(f.mutations[0].body.expected_card_revision).toBe(2);expect(f.mutations[0].body.mentioned_user_ids).toEqual([J]);await panel.getByTestId("comment-body").fill("回复内容");await panel.getByRole("button",{name:"发送回复",exact:true}).click();await expect.poll(()=>f.mutations.length).toBe(2);expect(f.mutations[1].body).not.toHaveProperty("expected_card_revision");expect(f.mutations[1].body).not.toHaveProperty("expected_thread_revision");expect(f.mutations[1].body.client_request_id).not.toBe(f.mutations[0].body.client_request_id);
  mkdirSync(output,{recursive:true});await page.screenshot({path:join(output,"viewer-discussion.png"),fullPage:true});writeFileSync(join(output,"slice2-result.json"),JSON.stringify({passed:true,checks:["viewer-human-comment","escaped-body","current-task-mention","append-only-reply"]},null,2));
});
test("lost comment receipt requires explicit retry with the same immutable request",async({page})=>{
  const f=await fixture(page,{withCard:true,lostComment:true});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await page.getByRole("button",{name:"分配与讨论"}).click();await page.getByTestId("comment-body").fill("响应丢失验收");await page.getByRole("button",{name:"创建讨论",exact:true}).click();await expect(page.getByRole("button",{name:"重试同一请求",exact:true})).toBeVisible();await expect(page.getByTestId("comment-body")).toBeDisabled();expect(f.mutations.length).toBe(1);await page.getByRole("button",{name:"重试同一请求",exact:true}).click();await expect.poll(()=>f.mutations.length).toBe(2);expect(f.mutations[1].body).toEqual(f.mutations[0].body);expect(f.comments.length).toBe(1);
});
test("archived cards remain readable without assignment or discussion writes",async({page})=>{
  await fixture(page,{withCard:true,archived:true});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await page.getByRole("button",{name:"分配与讨论"}).click();await expect(page.getByRole("dialog").getByText("已归档任务只读")).toBeVisible();await expect(page.getByRole("button",{name:"创建讨论",exact:true})).toHaveCount(0);await expect(page.getByRole("button",{name:"保存分配"})).toHaveCount(0);
});
test("foreign thread is rejected and an org reset clears panel drafts",async({page})=>{
  const f=await fixture(page,{withCard:true,foreignThread:true});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await page.getByRole("button",{name:"分配与讨论"}).click();await expect(page.getByRole("alert").last()).toContainText("范围");await expect(page.getByTestId("comment-body")).toHaveCount(0);await page.waitForTimeout(1200);expect(f.streamCheckpoints).not.toContain("opaque-workflow");expect(f.streamCheckpoints.length).toBeGreaterThan(0);expect(f.streamCheckpoints.every(Boolean)).toBe(true);await page.evaluate(()=>window.dispatchEvent(new Event("bid:org-reset")));await expect(page.getByRole("dialog")).toHaveCount(0);
});
test("comment bounds and discard warning protect in-memory drafts",async({page})=>{
  const f=await fixture(page,{withCard:true});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await page.getByRole("button",{name:"分配与讨论"}).click();await page.getByTestId("comment-body").fill("x".repeat(4001));await expect(page.getByRole("button",{name:"创建讨论",exact:true})).toBeDisabled();expect(f.mutations.length).toBe(0);await page.getByTestId("comment-body").fill("只在当前内存的草稿");await page.getByRole("button",{name:"关闭协作面板"}).click();await expect(page.getByRole("dialog").filter({hasText:"放弃未保存"})).toBeVisible();await page.getByRole("button",{name:"取消",exact:true}).last().click();await expect(page.getByTestId("comment-body")).toHaveValue("只在当前内存的草稿");expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain("只在当前内存的草稿");
});
test("SSE invalidation reloads discussion counts and bounded thread pages",async({page})=>{
  const f=await fixture(page,{withCard:true,threadPages:true,streamFrames:()=>frame({event_id:M,org_id:O,task_id:T,cursor:"opaque-comment",payload:{type:"board_changed",invalidate_all:true},created_at:"2026-10-05T00:00:00Z"})});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await page.getByRole("button",{name:"分配与讨论"}).click();await expect.poll(f.threadReads).toBeGreaterThan(1);await page.getByRole("button",{name:"下一页讨论",exact:true}).click();await expect(page.getByRole("button",{name:"上一页讨论",exact:true})).toBeEnabled();
});

test("assignment next action opens the authorized assignment panel",async({page})=>{
  await fixture(page,{nextAction:"assign"});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await page.getByRole("button",{name:"\u5206\u914d",exact:true}).click();await expect(page.getByRole("dialog").getByTestId("assignment-reason")).toBeVisible();
});

test("org viewer contributor is excluded from assignment but remains a task mention",async({page})=>{
  const f=await fixture(page,{withCard:true,viewerContributor:true});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await page.getByRole("button",{name:"\u5206\u914d\u4e0e\u8ba8\u8bba"}).click();const panel=page.getByRole("dialog");await panel.getByTestId("assignment-assignee").click();await expect(page.getByRole("option",{name:"\u5408\u6210\u53ea\u8bfb\u534f\u4f5c\u8005",exact:true})).toHaveCount(0);await page.keyboard.press("Escape");await panel.getByTestId("comment-mentions").click();await expect(page.getByRole("option",{name:"\u5408\u6210\u53ea\u8bfb\u534f\u4f5c\u8005",exact:true})).toBeVisible();expect(f.mutations.length).toBe(0);
});
test("thread view next action opens that thread's authorized comment page",async({page})=>{
  const f=await fixture(page,{withCard:true,nextAction:{code:"view",target:{kind:"thread",id:H},eligible_user_ids:[U],eligible_domains:[]}});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await page.getByRole("button",{name:"\u67e5\u770b",exact:true}).click();await expect(page.getByRole("dialog").getByRole("button",{name:"\u53d1\u9001\u56de\u590d",exact:true})).toBeVisible();await expect.poll(f.commentReads).toBeGreaterThan(0);
});

// Regression failures recorded before the live-start fix: a failed initial snapshot
// must not admit an uncheckpointed stream; bounded snapshot retries must recover;
// a reset must cancel pending admission and ignore an old completed snapshot.
test("initial snapshot failure retries before admitting an SSE connection",async({page})=>{
  const f=await fixture(page,{boardFailures:1});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await expect(page.getByRole("alert")).toContainText("board_busy");expect(f.streams()).toBe(0);await expect(page.getByRole("heading",{level:3,name:"★ 合成验收要求",exact:true})).toBeVisible();expect(f.boards()).toBeGreaterThan(1);await expect(page.getByRole("alert")).toHaveCount(0);await expect.poll(f.streams).toBeGreaterThan(0);expect(f.streamCheckpoints[0]).toBe("opaque-snapshot");expect(f.boards()).toBeLessThan(5);
});
test("failed discussion snapshot can recover without disrupting the board stream",async({page})=>{
  const f=await fixture(page,{withCard:true,foreignThread:true});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await page.getByRole("button",{name:"\u5206\u914d\u4e0e\u8ba8\u8bba",exact:true}).click();await expect(page.getByRole("dialog").getByRole("alert")).toContainText("\u8303\u56f4");expect(f.streamCheckpoints).not.toContain("opaque-workflow");f.acceptThreads();await expect(page.getByTestId("comment-body")).toBeVisible();await expect.poll(()=>f.streamCheckpoints.includes("opaque-workflow")).toBe(true);expect(f.streamCheckpoints).toContain("opaque-snapshot");expect(f.streamCheckpoints.every(Boolean)).toBe(true);await page.getByTestId("comment-body").fill("待清理草稿");expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain("待清理草稿");await page.evaluate(()=>window.dispatchEvent(new Event("bid:org-reset")));await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.getByTestId("comment-body")).toHaveCount(0);await expect(page.getByText("待清理草稿",{exact:true})).toHaveCount(0);const streams=f.streams();await page.waitForTimeout(1500);expect(f.streams()).toBe(streams);expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain("待清理草稿");
});
test("org reset cancels snapshot retry and a delayed panel snapshot admission",async({page})=>{
  const f=await fixture(page,{withCard:true,delayThreads:true});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await page.getByRole("button",{name:"\u5206\u914d\u4e0e\u8ba8\u8bba",exact:true}).click();await expect.poll(f.threadReads).toBe(1);await page.evaluate(()=>window.dispatchEvent(new Event("bid:org-reset")));await expect(page.getByRole("dialog")).toHaveCount(0);const streams=f.streams();f.releaseThreads();await page.waitForTimeout(1500);expect(f.streams()).toBe(streams);expect(f.streamCheckpoints).not.toContain("opaque-workflow");await expect(page.getByTestId("comment-body")).toHaveCount(0);
});
test("org reset stops retrying an unavailable first board snapshot",async({page})=>{
  const f=await fixture(page,{boardFailures:99});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await expect(page.getByRole("alert")).toContainText("board_busy");await page.evaluate(()=>window.dispatchEvent(new Event("bid:org-reset")));const reads=f.boards();await page.waitForTimeout(1500);expect(f.boards()).toBe(reads);expect(f.streams()).toBe(0);
});

test("failed snapshot admission honors Retry-After before its next read",async({page})=>{
  const f=await fixture(page,{boardFailures:1,boardRetryAfter:"2"});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await expect(page.getByRole("alert")).toContainText("board_busy");await page.waitForTimeout(1100);expect(f.boards()).toBe(1);expect(f.streams()).toBe(0);await expect(page.getByRole("heading",{level:3,name:"★ 合成验收要求",exact:true})).toBeVisible();expect(f.boards()).toBeGreaterThan(1);await expect(page.getByRole("alert")).toHaveCount(0);await expect.poll(f.streams).toBeGreaterThan(0);expect(f.streamCheckpoints[0]).toBe("opaque-snapshot");
});

test("poll reset waits for a rate-limited fresh snapshot before polling again",async({page})=>{
  const f=await fixture(page,{pollSnapshotFailure:true});await page.goto(`/app/org/tasks/${T}/board?job=${J}`);await expect.poll(f.polls,{timeout:18000}).toBeGreaterThan(0);await expect(page.getByRole("alert")).toContainText("board_busy");await page.waitForTimeout(5200);expect(f.boards()).toBe(2);expect(f.polls()).toBe(1);await expect(page.getByRole("heading",{level:3,name:"★ 合成验收要求",exact:true})).toBeVisible({timeout:12000});expect(f.boards()).toBeGreaterThan(2);await expect(page.getByRole("alert")).toHaveCount(0);await expect.poll(f.polls).toBeGreaterThan(1);expect(f.streamCheckpoints.every(Boolean)).toBe(true);
});
