// Failure scenarios before implementation: foreign org/revision; unbounded reads;
// stale preview and hash mismatch; omitted DOCX; authority loss; unsaved edits;
// legacy binding; automatic task upgrades; unexpected persistent content.
import { test, expect } from "@playwright/test";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const work = join(root, "data/work");
// Each resource kind owns a child directory even when a combined run supplies one base.
const outputBase = resolve(process.env.E2E_OUTPUT ?? join(work, "management-pages-validation/browser"));
const output = join(outputBase, "templates");
function inside(base, path) { const rel = relative(base, path); return rel !== ".." && !rel.startsWith(`..${process.platform === "win32" ? "\\" : "/"}`) && !rel.startsWith("/"); }
if (!inside(work, outputBase) || !inside(join(work,"management-pages-validation"),outputBase)) throw new Error("E2E_OUTPUT must be inside data/work/management-pages-validation");
let ancestor = output; while (!existsSync(ancestor)) ancestor = dirname(ancestor);
if (!inside(realpathSync(root), realpathSync(ancestor))) throw new Error("Artifact path resolves outside worktree");
const staticDir=process.env.E2E_STATIC_DIR?resolve(process.env.E2E_STATIC_DIR):null;
if(staticDir&&(!inside(root,staticDir)||!existsSync(staticDir)||!inside(realpathSync(root),realpathSync(staticDir))))throw new Error("E2E_STATIC_DIR must resolve inside the worktree");
const O="00000000-0000-0000-0000-000000000002", U="00000000-0000-0000-0000-000000000003", T="00000000-0000-0000-0000-000000000001", P="00000000-0000-0000-0000-000000000010", Q="00000000-0000-0000-0000-000000000011";
const rid=n=>`00000000-0000-0000-0000-${String(100+n).padStart(12,"0")}`;
const date="2026-10-06T00:00:00Z";
const cost={llm_tokens:0,ocr_pages:0,usd:0,basis:"zero",charge:"0",billing_currency:"USD",task_amount:"0",unpriced_calls:0,unresolved_calls:0};
const result=(command,data={},items=[],ok=true)=>({ok,command,data,items,warnings:[],cost,duration_ms:0});
const records=[],browserHealth=new WeakMap();
test.beforeEach(async({page})=>{
  const health=[];browserHealth.set(page,health);page.on("pageerror",error=>health.push(error.message));page.on("console",message=>{if(["error","warning"].includes(message.type())&&!message.text().startsWith("Failed to load resource"))health.push(message.text());});
  await page.addInitScript(({O,U})=>sessionStorage.setItem("bid.org.session",JSON.stringify({session:"synthetic-management-session",orgId:O,userId:U,orgName:"合成验收单位"})),{O,U});
  if(staticDir){const dir=staticDir;await page.route(url=>url.pathname.startsWith("/app/"),route=>{const path=new URL(route.request().url()).pathname;const file=path.startsWith("/app/assets/")?join(dir,"assets",basename(path)):join(dir,"index.html");return route.fulfill({contentType:{".html":"text/html",".js":"text/javascript",".css":"text/css"}[extname(file)]??"application/octet-stream",body:readFileSync(file)});});}
});
test.afterEach(async({page},info)=>{
  mkdirSync(output,{recursive:true});
  if(!inside(realpathSync(work),realpathSync(output)))throw new Error("Artifact symlink escapes data/work");
  const scenario=info.title.replace(/[^a-z0-9]+/gi,"-").toLowerCase();
  const health=browserHealth.get(page)??[];
  const overlay=await page.locator("vite-error-overlay").count();
  if(info.status==="passed"&&!health.length&&!overlay)await page.screenshot({path:join(output,`${scenario}.png`),fullPage:true});
  records.push({scenario:info.title,status:info.status==="passed"&&(health.length||overlay)?"failed":info.status,console_errors:health.length,framework_overlay:overlay,measurements:info.annotations.filter(item=>item.type==="measurement").map(item=>JSON.parse(item.description))});
  const builtIndex=join(root,"web/dist/index.html");
  const index=staticDir?join(staticDir,"index.html"):existsSync(builtIndex)?builtIndex:null;
  if(index&&!inside(realpathSync(root),realpathSync(index)))throw new Error("Build artifact resolves outside worktree");
  const permissions=records.filter(record=>/authority|revoked|task selection/.test(record.scenario)).map(({scenario,status})=>({scenario,status}));
  const schemaSummary={envelope_keys:["ok","command","data","items","warnings","cost","duration_ms"],cost_keys:["llm_tokens","ocr_pages","usd","basis","charge","billing_currency","task_amount","unpriced_calls","unresolved_calls"],checked_via:"api.js Result 4 parser and template org/root/revision validators before rendering",successful_render_scenarios:records.filter(record=>record.status==="passed").map(record=>record.scenario),parent_org_rejection:records.find(record=>record.scenario==="foreign binding is blocked before showing identity")?.status??"not_run",exact_revision_parent:records.find(record=>record.scenario==="direct revision UUID resolves exact historical binding parent in one read")?.status??"not_run"};
  writeFileSync(join(output,"result.json"),JSON.stringify({mode:"mocked_api",fixture_version:"template-management-v1",schema_version:"4.0",browser:"chromium",browser_version:page.context().browser()?.version()??null,build_sha256:index?createHash("sha256").update(readFileSync(index)).digest("hex"):null,base_url:process.env.E2E_BASE_URL??null,command:`cd web && E2E_BASE_URL=http://127.0.0.1:8000 ${index?'E2E_STATIC_DIR="$PWD/dist" ':''}E2E_OUTPUT=../data/work/management-pages-validation/browser node_modules/.bin/playwright test e2e/template-management.spec.js`,schema_assertion_summary:schemaSummary,permission_assertion_summary:permissions,expected_scenarios:22,complete:records.length===22,scenarios:records,passed:records.length===22&&records.every(r=>r.status==="passed")},null,2));
  expect(health,"Unexpected browser runtime or console error").toEqual([]);expect(overlay,"Framework error overlay").toBe(0);
});

const sectionKeys=["substantive","commercial","technical","comply_only","gaps","evidence_appendix"];
const sections=()=>sectionKeys.map((section,i)=>({section,heading_style_id:"Heading1",table_style_id:"TableGrid",columns:i<3?["ordinal","requirement","response","compliance"].map(key=>({key,width_percent:"25"})):[]}));
const docx=Buffer.from("UEsDBBQAAAAIAJBrRl2SCzrV4AAAAAoCAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbK2Ru1LDMBBFf0WjNhPLpKBgbKcA2kDBD+zIa1uDXqPdhOTvWcchBROgoZTu41yNmu0xeHXAQi7FVt9Vtd52zdspIylRIrV6Ys4PxpCdMABVKWMUZUglAMuxjCaDfYcRzaau741NkTHymucO3TVPOMDes3o+yvVCKehJq8fFOLNaDTl7Z4FFN4fYf6OsL4RKkmcPTS7TSgza3CTMys+AS+5Fnl1cj+oVCu8giMt8pNKbPtl9kGT1e82NnWkYnMVrfm7LJVkkcnEMvroqAVxc/bWD+OSR/n/F0vuFN+ff7j4BUEsDBBQAAAAIAJBrRl1fM5VSlQAAAAcBAAALAAAAX3JlbHMvLnJlbHONzzsOwjAMBuCrRD5AnTIwoKZdWLoiLhAlblPRPOSE1+3JwEARA6N///osd8PDr+JGnJcYFLSNhKHvTrTqUoPslpRFbYSswJWSDojZOPI6NzFRqJspsteljjxj0uaiZ8KdlHvkTwO2phitAh5tC+L8TPSPHadpMXSM5uoplB8nvhpV1jxTUXCPbNG+46aygH2Hmxf7F1BLAwQUAAAACACQa0ZdaS/ShUEBAAC3AgAAEQAAAHdvcmQvZG9jdW1lbnQueG1slVJLasMwEL1K0AEipw1pamJn202hkAMEWZ7YAv2QJnbcEOi60FW77B26732Sc1R289sU3M3MvJn3RoI3s/lGyUEFzgujEzIaRmSezuo4N3ytQOMgjLWP64SUiDam1PMSFPNDY0GH2co4xTBAV9DauNw6w8F7oQsl6U0UTahiQpN2ZWbyps22C0+uSwtsJAzquGIyIQ/A8qAcEZrO6JnTBUwPry+Hz6/9+9v++6OdYsdxv8zz3iN5u81EPvTrzCPTKCrY7XpquFEKHBdM9pYg8FIL/g9FeMTKZmm0bHprCmZ9bzJUIgfNYcls8CkXmz+UHjgenSgWz8GHYPRodB9NSKjLUE+mt9PWjpbwyFzoorGhPx5HLcWJosQLzAyiURcsYXU1LYO94BJyd9PBlTF4BYs1djA6un/6Gj1dDr1cZfoDUEsDBBQAAAAIAJBrRl1emTq4kwAAAPgAAAAcAAAAd29yZC9fcmVscy9kb2N1bWVudC54bWwucmVsc43POw7CMAwG4KtEPkDdMjCgpF1YulZcIErdh2geig2itycSC5UYGH/712dZdy+/qSdlXmMw0FQ1dK0eaLNSBrysiVVpBDawiKQLIruFvOUqJgplM8XsrZSYZ0zW3e1MeKrrM+ZvA46m6kcDuR8bULc90T92nKbV0TW6h6cgP04gy74RF9HmmcTAJ1fFAWw1Hn5q31BLAwQUAAAACACQa0ZdhW5nM6cAAAAbAQAADwAAAHdvcmQvc3R5bGVzLnhtbGWNTQ6CMBBGr9L0ABZcuGgoLNW9FxhphSb9S6ehcnsLoglhNzNvvvc13dsaMqmI2jtB61NFu7bJHNNsFJICHfIs6JhS4IxhPyoLePJBucJePlpIZY0Dyz7KEH2vELUbrGHnqrowC9rRv5BknuagBA0QYYgQRko2dJeC3hTIkq3XgAO7/E9gSvsXkJqytmFb4mhN8DRqZ3wsl2vU8qBcCVnRzvmbsP0AUEsBAhQDFAAAAAgAkGtGXZILOtXgAAAACgIAABMAAAAAAAAAAAAAAIABAAAAAFtDb250ZW50X1R5cGVzXS54bWxQSwECFAMUAAAACACQa0ZdXzOVUpUAAAAHAQAACwAAAAAAAAAAAAAAgAERAQAAX3JlbHMvLnJlbHNQSwECFAMUAAAACACQa0ZdaS/ShUEBAAC3AgAAEQAAAAAAAAAAAAAAgAHPAQAAd29yZC9kb2N1bWVudC54bWxQSwECFAMUAAAACACQa0ZdXpk6uJMAAAD4AAAAHAAAAAAAAAAAAAAAgAE/AwAAd29yZC9fcmVscy9kb2N1bWVudC54bWwucmVsc1BLAQIUAxQAAAAIAJBrRl2FbmczpwAAABsBAAAPAAAAAAAAAAAAAACAAQwEAAB3b3JkL3N0eWxlcy54bWxQSwUGAAAAAAUABQBAAQAA4AQAAAAA","base64");
const hash=createHash("sha256").update(docx).digest("hex"),staticHash="31c5e5a8d0343e636c2401cede45bb84ee029a594cb1e5035bd7aa64dc1604b2",B="00000000-0000-0000-0000-000000000040";
const file={name:"合成模板.docx",sha256:hash,size_bytes:docx.length,media_type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"};
async function fixture(page,options={}){
 const state={role:"admin",head:1,inactive:false,lifecycleRevision:0,taskRole:"owner",...options},writes=[],queries=[],requests=[];
 let releaseOriginal=null;
 const lifecycle=()=>({state:state.inactive?"inactive":"active",revision:state.lifecycleRevision});
 const revision=n=>({id:rid(n),org_id:O,template_id:P,revision:n,data:{name:"合成模板",project_types:["软件"],chapters:[{title:"技术响应",children:[]}]},file});
 const actions=()=>["revise","deactivate","restore","select"].map(action=>({action,allowed:action==="select"||state.role==="admin",...(action!=="select"&&state.role!=="admin"?{reason:"role_required"}:{})}));
 const meta=items=>({org_id:O,as_of:date,returned:items.length,next_cursor:null,has_more:false});
 const binding=()=>({id:B,org_id:state.foreign?Q:O,template_revision_id:rid(1),template_sha256:hash,binding_hash:"c".repeat(64),static_content_hash:staticHash,adapter_version:"docx-v1",sections:sections(),current:!state.legacy,reviewed_by:U,reviewed_at:date});
 await page.route(url=>!url.pathname.startsWith("/app/"),async route=>{
 const req=route.request(),url=new URL(req.url()),path=url.pathname.replace(/^\/v4(?=\/)/,"");requests.push({path,method:req.method()});
 const send=(command,data={},items=[])=>route.fulfill({json:result(command,data,items)});
 if(path==="/org/current")return send("org current",{org_id:O,user_id:U,role:state.role});
 if(path==="/management/resources/templates/query"){const body=req.postDataJSON();queries.push(body);const items=body.q==="无模板"?[]:[{org_id:state.foreign?Q:O,ref:{kind:"templates",resource_id:P},revision_id:rid(1),revision:1,name:"合成模板",lifecycle:lifecycle(),provenance:"declared",revised_at:date,revised_by:U,actions:actions()}];return send("resource template browse",meta(items),items);}
 if(path===`/management/resources/templates/${P}`){const n=url.searchParams.get("revision_id")?Number(url.searchParams.get("revision_id").slice(-12))-100:Number(url.searchParams.get("revision")??state.head);return send("resource template show",{org_id:O,ref:{kind:"templates",resource_id:P},current_revision:state.head,lifecycle:lifecycle(),provenance:"declared",revised_at:date,revised_by:U,actions:actions(),detail:{kind:"templates",revision:revision(n)}});}
 if(path===`/management/resources/templates/${P}/history/query`){const items=Array.from({length:state.head},(_,i)=>state.head-i).map(n=>({org_id:O,ref:{kind:"templates",resource_id:P},revision_id:rid(n),revision:n,name:"合成模板",created_at:date,created_by:U,current:n===state.head,has_file:true}));return send("resource template history",meta(items),items);}
 if(path.endsWith("/lifecycle/history/query")){const items=state.lifecycleRevision?[{id:Q,org_id:O,ref:{kind:"templates",resource_id:P},revision:state.lifecycleRevision,resource_revision:state.head,before:state.inactive?"active":"inactive",after:state.inactive?"inactive":"active",reason_code:state.inactive?"obsolete":"restored",actor_user_id:U,created_at:date}]:[];return send("resource lifecycle history",meta(items),items);}
 if(path===`/tasks/${T}/workflow`)return send("task workflow",{workflow:{org_id:O,task_id:T,state:state.archived?"archived":"active",revision:1,owner_user_id:U}});
 if(path===`/tasks/${T}/members`){const items=state.taskRole?[{org_id:O,task_id:T,user_id:U,role:state.taskRole,active:true,revision:1}]:[];return send("task members",{...meta(items),task_id:T},items);}
 if(path===`/tasks/${T}/templates`){const body=req.postDataJSON();writes.push({path,body});return send("task template add",{id:Q,org_id:O,task_id:T,template_revision_id:rid(body.revision),revision:body.revision,lot:body.lot,duplicate:false,replaced_snapshot_id:null,data:revision(body.revision).data,file});}
 if(path===`/management/resources/templates/${P}/lifecycle`){const body=req.postDataJSON();writes.push({path,body});state.inactive=body.state==="inactive";state.lifecycleRevision++;return send("resource lifecycle set",{lifecycle:lifecycle(),existing_selections:"preserved",event:{id:Q,org_id:O,ref:{kind:"templates",resource_id:P},revision:state.lifecycleRevision,resource_revision:state.head,before:state.inactive?"active":"inactive",after:body.state,reason_code:body.reason_code,actor_user_id:U,actor_kind:"session",created_at:date}});}
 if(path==="/management/export-bindings/query"){queries.push(req.postDataJSON());return send("export binding browse",meta([binding()]),[binding()]);}
 if(path===`/management/export-bindings/${B}`)return send("export binding show",binding());
 if(path===`/resources/templates/revisions/${rid(1)}/download-link`)return send("template original",{url:`/resources/templates/revisions/${rid(1)}/download?signature=synthetic`});
 if(path.endsWith("/download")){
  if(state.delayOriginal)await new Promise(resolve=>{releaseOriginal=resolve;});
  const bytes=Buffer.from(docx);if(state.corruptOriginal)bytes[bytes.length-1]^=1;
  return route.fulfill({contentType:file.media_type,body:bytes});
 }
 if(path==="/export-template-bindings"){const body=req.postDataJSON();writes.push({path,body});if(state.denied)return route.fulfill({status:403,json:result("export binding create",{error:{code:"forbidden",message:"Forbidden",exit_code:4}},[],false)});if(!body.dry_run&&state.mismatch)return route.fulfill({status:409,json:result("export binding create",{error:{code:"export_static_hash_conflict",message:"Static content changed",exit_code:2}},[],false)});return send("export binding create",body.dry_run?{dry_run:true,template_revision_id:rid(1),template_sha256:hash,static_content_hash:staticHash,adapter_version:"docx-v1",anchors:sectionKeys.map((section,i)=>({section,paragraph:i+2,section_index:0})),issues:[]}:binding());}
 if(path==="/resources/templates"||path===`/resources/templates/${P}/revisions`){writes.push({path,body:req.postDataBuffer().toString()});if(state.conflict){state.conflict=false;state.head++;return route.fulfill({status:409,json:result("resource template update",{error:{code:"revision_conflict",message:"Changed",exit_code:4}},[],false)});}state.head++;return send("resource template update",revision(state.head));}
 if(req.method()==="GET"&&path==="/health")return route.fulfill({json:{ok:true,command:"health",data:{status:"ok",version:"4.0",real_llm_configured:false,org_signup_enabled:false},items:[],warnings:[],cost:{llm_tokens:0,ocr_pages:0,usd:0},duration_ms:0}});
 throw new Error(`Unexpected template request ${req.method()} ${path}`);
 });return {state,writes,queries,requests,releaseOriginal:()=>releaseOriginal?.()};
}
const bindingsPath=`/app/org/templates/${P}/revisions/${rid(1)}/bindings`;
async function configure(page){for(const key of sectionKeys){await page.getByLabel(`${key} 标题样式 ID`,{exact:true}).fill("Heading1");await page.getByLabel(`${key} 表格样式 ID`,{exact:true}).fill("TableGrid");}}
test("bounded template browse and private search",async({page})=>{const f=await fixture(page);await page.goto("/app/org/templates");await expect(page.getByRole("heading",{name:"模板库",exact:true})).toBeVisible();await page.getByLabel("搜索模板",{exact:true}).fill("无模板");await expect(page.getByText("没有符合条件的模板")).toBeVisible();expect(f.queries.at(-1)).toMatchObject({q:"无模板",cursor:null,limit:25});expect(f.requests.some(r=>r.path==="/resources/templates"&&r.method==="GET")).toBe(false);expect(await page.evaluate(()=>JSON.stringify({...sessionStorage,...localStorage}))).not.toContain("无模板");});
test("revision requires fresh DOCX and conflict retains draft",async({page})=>{const f=await fixture(page,{conflict:true});await page.goto(`/app/org/templates/${P}`);await page.getByRole("button",{name:"修订模板",exact:true}).click();await page.getByLabel("模板名称",{exact:true}).fill("保留的模板草稿");await expect(page.getByRole("button",{name:"保存模板",exact:true})).toBeDisabled();await page.getByLabel("模板 DOCX",{exact:true}).setInputFiles({name:"fresh.docx",mimeType:file.media_type,buffer:docx});await page.getByRole("button",{name:"保存模板",exact:true}).click();await expect(page.getByLabel("模板名称",{exact:true})).toHaveValue("保留的模板草稿");await expect(page.getByRole("alert").filter({hasText:/草稿已保留/}).first()).toBeVisible();expect(f.writes).toHaveLength(1);expect(f.writes[0].body).toContain('filename="fresh.docx"');});
test("six sections preview exact hashes explicit static review then create",async({page})=>{
 const f=await fixture(page,{delayOriginal:true});await page.goto(bindingsPath);await configure(page);await page.getByRole("button",{name:"预览绑定",exact:true}).click();
 const review=page.getByLabel("我已核对本修订原件中的全部静态内容",{exact:true}),create=page.getByRole("button",{name:"确认创建绑定",exact:true});
 await expect(review).toHaveCount(1);await expect(review).toBeDisabled();await expect(create).toBeDisabled();
 const downloaded=page.waitForEvent("download");await page.getByRole("button",{name:"下载原件核对静态内容",exact:true}).click();
 await expect.poll(()=>f.requests.some(request=>request.path.endsWith("/download"))).toBe(true);
 await expect(review).toBeDisabled();await expect(create).toBeDisabled();expect(f.writes).toHaveLength(1);
 f.releaseOriginal();await downloaded;await expect(review).toBeEnabled();await expect(review).not.toBeChecked();await expect(create).toBeDisabled();
 await review.check();await create.click();await expect(page.getByRole("status").filter({hasText:"已创建绑定"})).toBeVisible();
 expect(f.writes).toHaveLength(2);expect(f.writes[0].body).toMatchObject({dry_run:true,expected_template_sha256:hash});expect(f.writes[1].body).toMatchObject({dry_run:false,expected_template_sha256:hash,expected_static_content_hash:staticHash});expect(f.writes[1].body.sections.map(s=>s.section)).toEqual(sectionKeys);
});
test("binding edits invalidate review and preview",async({page})=>{const f=await fixture(page);await page.goto(bindingsPath);await configure(page);await page.getByRole("button",{name:"预览绑定",exact:true}).click();await expect(page.getByText("静态内容哈希",{exact:true})).toBeVisible();await page.getByLabel("substantive 标题样式 ID",{exact:true}).fill("Heading2");await expect(page.getByRole("button",{name:"确认创建绑定",exact:true})).toHaveCount(0);expect(f.writes).toHaveLength(1);});
test("static hash mismatch clears gate without retry",async({page})=>{
 const f=await fixture(page,{mismatch:true,corruptOriginal:true});await page.goto(bindingsPath);await configure(page);await page.getByRole("button",{name:"预览绑定",exact:true}).click();
 const review=page.getByLabel("我已核对本修订原件中的全部静态内容",{exact:true});await expect(review).toHaveCount(1);await expect(review).toBeDisabled();
 await page.getByRole("button",{name:"下载原件核对静态内容",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"原件哈希不符合契约"})).toBeVisible();
 await expect(review).toBeDisabled();await expect(page.getByRole("button",{name:"确认创建绑定",exact:true})).toBeDisabled();expect(f.writes).toHaveLength(1);
 f.state.corruptOriginal=false;const downloaded=page.waitForEvent("download");await page.getByRole("button",{name:"下载原件核对静态内容",exact:true}).click();await downloaded;await expect(review).toBeEnabled();await review.check();
 await page.getByRole("button",{name:"确认创建绑定",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:/哈希|hash/})).toBeVisible();await expect(page.getByRole("button",{name:"确认创建绑定",exact:true})).toHaveCount(0);expect(f.writes).toHaveLength(2);
});
for(const role of ["bidder","technical","viewer"])test(`binding authority ${role}`,async({page})=>{const f=await fixture(page,{role,legacy:true});await page.goto(bindingsPath);await expect(page.getByRole("button",{name:"预览绑定",exact:true})).toHaveCount(0);if(role==="bidder")await expect(page.getByText("旧版绑定不能用于导出",{exact:true})).toBeVisible();else expect(f.requests.some(r=>r.path.startsWith("/management/export-bindings"))).toBe(false);expect(f.writes).toHaveLength(0);});
test("org reset clears binding input and preview",async({page})=>{const f=await fixture(page);await page.goto(bindingsPath);await configure(page);await page.getByRole("button",{name:"预览绑定",exact:true}).click();await page.evaluate(()=>window.dispatchEvent(new Event("bid:org-reset")));await expect(page.getByRole("button",{name:"确认创建绑定",exact:true})).toHaveCount(0);await expect(page.getByLabel("substantive 标题样式 ID",{exact:true})).toHaveCount(0);expect(f.writes).toHaveLength(1);});
test("foreign binding is blocked before showing identity",async({page})=>{await fixture(page,{foreign:true});await page.goto(bindingsPath);await expect(page.getByRole("alert").filter({hasText:/范围/})).toBeVisible();await expect(page.getByText(B,{exact:true})).toHaveCount(0);});

test("create template uploads DOCX and declared metadata without pin writes",async({page})=>{const f=await fixture(page);await page.goto("/app/org/templates");await page.getByRole("button",{name:"新增模板",exact:true}).click();await page.getByLabel("模板名称",{exact:true}).fill("新模板声明");await page.getByLabel("适用项目类型",{exact:true}).fill("软件\n服务");await page.getByLabel("模板 DOCX",{exact:true}).setInputFiles({name:"new.docx",mimeType:file.media_type,buffer:docx});await page.getByRole("button",{name:"保存模板",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"已创建模板"})).toBeVisible();expect(f.writes).toHaveLength(1);expect(f.writes[0].path).toBe("/resources/templates");expect(f.writes[0].body).toContain('filename="new.docx"');expect(f.writes[0].body).toContain('"project_types":["软件","服务"]');});
test("template lifecycle preserves content and existing task pins",async({page})=>{const f=await fixture(page);await page.goto(`/app/org/templates/${P}`);await page.getByRole("button",{name:"停用模板",exact:true}).click();await page.getByRole("button",{name:"确认停用",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"已有任务固定版本保留"})).toBeVisible();expect(f.writes[0].body).toMatchObject({expected_revision:1,expected_lifecycle_revision:0,state:"inactive"});await page.getByRole("button",{name:"恢复模板",exact:true}).click();await page.getByRole("button",{name:"确认恢复",exact:true}).click();await expect.poll(()=>f.writes.length).toBe(2);expect(f.writes[1].body).toMatchObject({expected_revision:1,expected_lifecycle_revision:1,state:"active",reason_code:"restored"});expect(f.state.head).toBe(1);});
for(const role of ["bidder","technical"])test(`explicit historical template task selection pins exact immutable revision ${role}`,async({page})=>{const f=await fixture(page,{head:2,role});await page.goto(`/app/org/templates/${P}?revision=1&task=${T}`);await expect(page.getByRole("button",{name:"修订模板",exact:true})).toHaveCount(0);await page.getByRole("button",{name:"选择到任务",exact:true}).click();await page.getByLabel("分包（可选）",{exact:true}).fill("包一");await page.getByRole("button",{name:"确认选择修订 1",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"任务已固定修订 1"})).toBeVisible();expect(f.writes).toHaveLength(1);expect(f.writes[0]).toMatchObject({path:`/tasks/${T}/templates`,body:{template_id:P,revision:1,lot:"包一"}});});
for(const scenario of [{role:"technical",taskRole:"reviewer"},{role:"viewer"},{role:"admin",taskRole:"observer"},{role:"admin",taskRole:null},{role:"bidder",archived:true}])test(`template task authority ${scenario.role} ${scenario.taskRole??"none"} ${!!scenario.archived}`,async({page})=>{const f=await fixture(page,scenario);await page.goto(`/app/org/templates/${P}?task=${T}`);await expect(page.getByRole("heading",{name:"合成模板",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"选择到任务",exact:true})).toHaveCount(0);expect(f.writes).toHaveLength(0);});
test("open binding revoked authority clears pending static content decision",async({page})=>{const f=await fixture(page);await page.goto(bindingsPath);await configure(page);await page.getByRole("button",{name:"预览绑定",exact:true}).click();await page.getByRole("button",{name:"下载原件核对静态内容",exact:true}).click();const review=page.getByLabel("我已核对本修订原件中的全部静态内容",{exact:true});await expect(review).toHaveCount(1);await expect(review).toBeEnabled();await review.check();f.state.denied=true;await page.getByRole("button",{name:"确认创建绑定",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:/无权|Forbidden/})).toBeVisible();await expect(page.getByLabel("substantive 标题样式 ID",{exact:true})).toHaveCount(0);expect(f.writes).toHaveLength(2);});
test("direct revision UUID resolves exact historical binding parent in one read",async({page})=>{const f=await fixture(page,{head:2});await page.goto(bindingsPath);await expect(page.getByText(/合成模板 · 内容修订 1 · 原件/)).toBeVisible();expect(f.requests.filter(r=>r.path===`/management/resources/templates/${P}`)).toHaveLength(1);expect(f.requests.some(r=>r.path.endsWith("/history/query"))).toBe(false);});
test("narrow-screen binding editor protects unsaved keyboard input",async({page})=>{await fixture(page);await page.setViewportSize({width:390,height:844});await page.goto(bindingsPath);await page.getByLabel("substantive 标题样式 ID",{exact:true}).fill("未保存样式");await page.getByLabel("substantive 标题样式 ID",{exact:true}).press("Tab");await page.getByRole("link",{name:"模板详情",exact:true}).click();await expect(page.getByRole("dialog").filter({hasText:"放弃未保存"})).toBeVisible();await page.getByRole("button",{name:"取消",exact:true}).last().click();await expect(page.getByLabel("substantive 标题样式 ID",{exact:true})).toHaveValue("未保存样式");expect(await page.evaluate(()=>JSON.stringify({...sessionStorage,...localStorage}))).not.toContain("未保存样式");});
