import { ApiError, orgSession } from './api.js';
import { orgRequest } from './org.js';
export const kinds={business_licence:'营业执照',qualification_scan:'资格扫描件',contract:'合同',performance_record:'业绩材料'};
export const fields={registration_details:'登记信息',performance_summary:'业绩声明',standard_wording:'标准表述'};
export const reviewStates={pending:'待审阅',approved:'已接受内部使用',rejected:'已驳回',revoked:'已撤回接受'};
export const nextActions={review_uploaded_file:'审阅上传原件',upload_corrected_revision:'上传更正修订',assign_reviewer:'重新指定审阅者',link_declaration:'关联精确声明',select_for_task:'选择到任务',archive_page:'归档原件页',review_page_privacy:'审阅此页隐私',redact_page:'等待遮挡流程',replace_source:'替换来源',annotate_page:'准备标注',wait_for_annotation_enablement:'等待标注接入',inspect_history:'核对历史'};
export const blockers={archive_inactive:'附件已停用',archive_review_pending:'原件待审阅',archive_review_rejected:'原件已驳回',archive_review_revoked:'原件接受已撤回',reviewer_unavailable:'审阅者已离开，需要重新指定',profile_link_missing:'尚未关联声明',profile_link_inactive:'声明关联已停用',profile_selection_changed:'任务资料选择已变化',attachment_selection_inactive:'任务附件选择已停用',task_archived:'任务已归档',source_not_archived:'此页尚未归档',source_integrity_failure:'来源完整性检查失败',privacy_pending:'此页隐私待审阅',needs_redaction:'此页需要遮挡，首版未启用遮挡',privacy_withdrawn:'隐私审阅已撤回',extraction_required:'需要先抽取要求',annotation_adapter_not_enabled:'附件标注接入尚未启用'};
export const attachmentRequest=(method,path,body,options={})=>orgRequest(method,path,body,{...options,contractVersion:4});
export function scoped(value,taskId){if(value.org_id!==orgSession.get()?.orgId||(taskId&&value.task_id!==taskId))throw new ApiError(502,'invalid_response','附件响应范围不符合契约');return value;}
export function checkedPage(result,taskId){if(!result.data||!Number.isInteger(result.data.limit)||result.data.limit<1||result.data.limit>100||result.items.length>result.data.limit||!(result.data.next_cursor===null||typeof result.data.next_cursor==='string'))throw new ApiError(502,'invalid_response','附件分页不符合契约');result.items.forEach(row=>scoped(row,taskId));return result;}
export async function signedBlob(linkPath,expectedPath,expectedHash=null){const result=await attachmentRequest('GET',linkPath),url=new URL(result.data.url,window.location.origin);if(url.origin!==window.location.origin||url.pathname!==expectedPath||url.hash||!url.searchParams.has('signature')||result.data.expires_in!==300)throw new ApiError(502,'invalid_response','附件链接范围不符合契约');const blob=await attachmentRequest('GET',result.data.url,undefined,{binary:true});if(expectedHash){const digest=await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()),hash=Array.from(new Uint8Array(digest),value=>value.toString(16).padStart(2,'0')).join('');if(hash!==expectedHash)throw new ApiError(502,'attachment_integrity','附件预览像素哈希不符');}return blob;}
